### ISSUE TITLE
Ability to add custom attributes  

### ISSUE THREAD

**Issue by hutber** [iamhosseindhv/notistack#101]
I'm sure how useful this would be to other users, but for our BDD tests we are using custom data-attribute. `data-getTestById`.

Would it be possible to add custom attributes 
```  enqueueSnackbar(displayMessage, { variant, attribute: {"data-testById":"snackbar"}, });```
For example

**Comment by iamhosseindhv** [comment]
@hutber 

Any data you pass in `options` parameter of `enqueueSnackbar` gets passed down to the snackbar element. So it think you could do something like:

```javascript 
this.props.enqueueSnackbar('I love snacks', {
    'data-gettestbyid': 'my custom attribute',
});
```

<img width="660" alt="Screenshot 2019-04-02 at 22 31 45" src="https://user-images.githubusercontent.com/26996372/55437580-245ce080-5597-11e9-9a86-177c04888edb.png">

Feel free to let me know if this didn't answer your question.

**Comment by hauptrolle** [comment]
This does not work with typescript because the interface does not allow additional attributes. Any chance to get a fix for this?

**Comment by samuelpucat** [comment]
@iamhosseindhv

As of v3, using [migration guide](https://notistack.com/migration#breaking-changes) 

```
<SnackbarProvider
-    data-test="test"
+    SnackbarProps={{
+        'data-test': 'test',
+    }}
>
</SnackbarProvider>

enqueueSnackbar('message', {
-    'data-test': 'test',
+    SnackbarProps: {
+       'data-test': 'test',
+    },
})
```

typescript returns this error:

> No overload matches this call.
  Overload 1 of 2, '(props: SnackbarProviderProps | Readonly<SnackbarProviderProps>): SnackbarProvider', gave the following error.
    Object literal may only specify known properties, and ''data-test'' does not exist in type 'HTMLAttributes<HTMLDivElement>'...

Can we allow using data-* attributes?

**Comment by jameslawson** [comment]
I have the same issue that @samuelpucat has.
Imo, the docs should be updated as the Typescript included in the docs is not enough to compile; there isn't much guidance on how to use SnackbarProps to add custom data attributes (feedback for you: @iamhosseindhv)

Fwiw, for anyone coming and discovering this issue, this worked for me:

```typescript
// top of the file
interface SnackbarProps extends React.HTMLAttributes<HTMLDivElement> {
  'data-testid'?: string;
}
```

```typescript
// inside the component
<SnackbarProvider
  SnackbarProps={
    {
      'data-testid': 'foo',
    } as SnackbarProps
  }
>
  { /*...*/ }
</SnackbarProvider>
```

This is inspired by [this solution](https://stackoverflow.com/a/61482645/3649209)
