### ISSUE TITLE
Ability to retrieve number of snackbars inside queue

### ISSUE THREAD

**Issue by kedpak** [iamhosseindhv/notistack#102]
Hello, is there a way to know how many snackbars are currently in the Queue? So let's say the maxSnack size for a component is set to 3. I set the option to have the snack bars persist on the screen.
 Now,  Lets say the enqueueSnackbar() function is called three times, so there are exactly three snackbars in the queue and displayed on the screen. However, I can't find a way to actually obtain the current length of this queue . So if I call enqueueSnackbar() one more time, the oldest snackbar will pop off (as expected) and a new snackbar will be pushed in. However, I want the ability to check if the queue is full (length of 3).

Is there a way to know from inside the component how many snack bars are inside the Queue?  Thanks.

**Comment by iamhosseindhv** [comment]
Hey @kedpak  👍🏼

No unfortunately, currently there's no way of knowing number of snacks in the queue or in the view, as they're managed internally by `SnackbarProvider` component. 

I think there's a pretty low change of this feature getting into the library, as I think it'll introduce complexities while serving a small number of use-cases.
