### ISSUE TITLE
[FR] Multiple actions support

### ISSUE THREAD

**Issue by YBogomolov** [iamhosseindhv/notistack#107]
### Motivation

Currently Notistack supports only one possible action, while sometimes it is useful to have multiple actions on the snack. Such actions may include a pair of buttons: one for closing the persistent snack, and the second one for displaying a modal dialog with error details.

### Implementation idea

Remove `<span>` which wraps `action` in [SnackbarItem](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarItem/SnackbarItem.js#L121), or check if `action` is actually an array and `map` through it.

**Comment by iamhosseindhv** [comment]
This is next on the [list](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md) to be implemented.

**Comment by iamhosseindhv** [comment]
Fixed. Refer to #110 for more info.
