### ISSUE TITLE
Unable to provide CSS class on < Snackbar > directly

### ISSUE THREAD

**Issue by BornaP** [iamhosseindhv/notistack#11]
Is there a way to override CSS on <Snackbar> element directly?

**Comment by iamhosseindhv** [comment]
Please edit [this sandbox](https://codesandbox.io/embed/github/iamhosseindhv/notistack/tree/master/demo??hidenavigation=1&module=%2FApp.js&codemirror=1) and apply what you're trying to achieve, then share the example url here.

**Comment by BornaP** [comment]
I'm trying to apply CSS class directly to `<Snackbar />` element. One example of it would be changing elements position property from fixed to absolute (ie. I'm trying to position snackbars relative to container, not window). 

I believe it can easily be solved with passing `classesSnackbar` or something similar to https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarItem/SnackbarItem.js#L53

What do you think? If it makes sense, I can make PR for it.

**Comment by iamhosseindhv** [comment]
I believe you can do so using `classes` property of snackbar. see docs [here](https://material-ui.com/api/snackbar/#css-api)

```javascript
const styles = {
  snack: {
    position: 'absolute',
    height: 50,
    bottom: 70,
    left: 10,
    backgroundColor: 'red',
  },
};

const App = ({ classes }) => (
  <SnackbarProvider 
    maxSnack={3}
    classes={{ 
      root: classes.snack,
    }}
  >
    <MessageButtons />
  </SnackbarProvider>
);

export default withStyles(styles)(App)
```

link to SANDBOX EXAMPLE: https://codesandbox.io/s/j9k0063q5

**Comment by BornaP** [comment]
That's the issue. Classes root set's it to SnackbarItem, not Snackbar component. I need to position Snackbar's `<div>` relative to container. Root element of whole plugin therefore is not accessible with `classes` prop.

**Comment by iamhosseindhv** [comment]
I see @BornaP , `classes.root` in [this line](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarItem/SnackbarItem.styles.js#L9) has to be renamed to avoid name collision with Snackbar `classes.root` prop. 

And `classes` needs to get passed down to the Snackbar component.

**Comment by iamhosseindhv** [comment]
Fix commit: https://github.com/iamhosseindhv/notistack/commit/2eaaa50e3912185f1483a59f161be3226fa43f16

By upgrading to `v0.3.7` @BornaP , you should by able to apply css classes to Snackbar root (in the same way in example above).

**Comment by iamhosseindhv** [comment]
Closed due to fix and/or inactivity. feel free to reopen.

**Comment by AndreKlenert** [comment]
The bottom css in root is useless as it is overwritten with inline style. Is there any way to set the bottom or top css without being overwritten? I need to set the top css parameter to a specific value...

**Comment by matsgm** [comment]
> The bottom css in root is useless as it is overwritten with inline style. Is there any way to set the bottom or top css without being overwritten? I need to set the top css parameter to a specific value...

You can try using marginBottom or marginTop instead.

**Comment by matsgm** [comment]
I would like to reopen this. On devices with bottom navigation, I can´t seem to place the notification container above the bottom navigation, so I can use multiple notifications.

**Comment by KoenLav** [comment]
@matsgm and others, this is actually possible but undocumented:

`<SnackbarProvider classes={{ containerRoot: classes.snackbarContainer }}>`

**Comment by iamhosseindhv** [comment]
Documentation can be found here: https://iamhosseindhv.com/notistack/api#classes

**Comment by KoenLav** [comment]
@iamhosseindhv apologies, I missed containerRoot there.

I guess this issue can be closed then?

**Comment by iamhosseindhv** [comment]
Yeah maybe title of the issue is not applicable anymore. 

The reason I have this issue open is that I'd like us all to have a way to dynamically change the position of snackbar container.

Say you're developing a web app with bottom navigation. Currently you can change bottom position of snackbar container. but not all of the pages have bottom navigation. You should have a way of toggling between different mode/positions as user navigates between different pages.

**Comment by iamhosseindhv** [comment]
As per comment above
