### ISSUE TITLE
Can't get usage to work with either Hooks or HOC

### ISSUE THREAD

**Issue by roberthchapman** [iamhosseindhv/notistack#115]
Hi,

I have tried using this as a hook, with the following function/component, but it always gives the message that "Hooks can only be called inside the body of a function component"

```javascript
import { useSnackbar } from 'notistack';
export const Snackbar = (message:string) => {
    const { enqueueSnackbar } = useSnackbar();
    enqueueSnackbar(message, {variant: 'error'});
}
```

This is then called from my class component.

I have also tried it using a HOC (using Typescript).  I have made sure to use WithSnackbarProps (the props for my page are "IPageProps & WithSnackbarProps") and to wrap my component in withSnackbar.  I have done this sort of thing many times but for some reason, it always says that this.props.enqueueSnackbar is not a function.  I'm really not sure why it isn't injecting the two properties.

What am I missing with the usage of notistack, I have failed to get it to work with both methods?

Thanks, Rob

**Comment by iamhosseindhv** [comment]
@roberthchapman 
As the error message suggests, you're not calling enqueueSnackbar from within a functional component. 
Here's a working example: 
```javascript
export const Button = () => {
    const { enqueueSnackbar } = useSnackbar();
    return (
        <button onClick={() => {
            enqueueSnackbar('my message goes here', { variant: true });
        }}>
            button
        </button>
    )
}
```

**Comment by amendoza4** [comment]
Hi. @iamhosseindhv are we only allowed to call enqueueSnackbar on onClick event? Can we call it conditionally, like if I have a boolean variable, when that variable is true call enqueueSnackbar(), when that changed to false, call closeSnackbar().
