### ISSUE TITLE
HELP REQUIRED, Calling enqueueSnackbar from outside a component

### ISSUE THREAD

**Issue by p34m5** [iamhosseindhv/notistack#117]
Hi,

Thank you for the great library. I have a question and couldn't find any answer for it. Is it possible to call enqueueSnackbar from outside a component?

When I try to call it somewhere else (for example inside an action), it does not do anything.

Any solutions?

Thanks.

**Comment by iamhosseindhv** [comment]
@p34m5 Solutions presented here may help:
https://github.com/iamhosseindhv/notistack/issues/30

**Comment by godmar** [comment]
> I have a question and couldn't find any answer for it.

A tip for next time: [search the issues](https://github.com/iamhosseindhv/notistack/issues?utf8=%E2%9C%93&q=is%3Aissue+outside+component)
