### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by slavikdenis** [iamhosseindhv/notistack#12]
It would be great if there would be a CHANGELOG to see whats new :)

Love this extension <3

**Comment by iamhosseindhv** [comment]
Happy to hear you like notistack and thanks for pointing this out @slavikdenis.

[`CHANGELOG.md`](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md) has been created. It'd be populated as we improve notistack and release new versions.
