### ISSUE TITLE
enqeueuSnackbar options.action as a function - failed prop type

### ISSUE THREAD

**Issue by the-vampiire** [iamhosseindhv/notistack#121]
Not able to use an `options.action` function property on `enqueueSnackbar`. Receiving failed prop type warnings

## Expected Behavior
from the [docs example](https://iamhosseindhv.com/notistack#action-for-all-snackbars) expected to be able to pass an `options.action` function of the form

```js
props.enqeueuSnackbar(
  'message',
  {
    action: key => (
      // things to render that consume the key parameter
    );
  }
);
```

## Current Behavior
does not render `action` return value. receiving the following console warnings:

```sh
Failed prop type: Invalid prop `action` supplied to `Snackbar`, expected a ReactNode.
                
Functions are not valid as a React child.
This may happen if you return a Component instead of <Component /> from render.
Or maybe you meant to call this function rather than return it.
```

## Steps to Reproduce
Link: [link to codesandbox example of bug](https://codesandbox.io/s/4q864q892x?fontsize=14)

1. open the console tab
2. click the button

also fails when using the `actions` function defined in the docs (commented out)
works if you provide child directly rather than using a callback (commented out)

## Context
i would like to use the `options.action` property to provide a dismiss button to the snackbars

## Your Environment
this all took place in the [codesandbox example environment](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/simple-example??hidenavigation=1&module=%2FApp.js) linked from the readme. the only changes made were to the `App.js` file to display the error

**Comment by iamhosseindhv** [comment]
@the-vampiire Updating notistack version to the latest solved the issue. I'll update `package.json` for examples as well.
