### ISSUE TITLE
Be able to close all snackbars

### ISSUE THREAD

**Issue by alexisab** [iamhosseindhv/notistack#122]
It will be nice to be able to close all snackbars by calling the `closeSnackbar` function without parameters. It can be tedious to store all snackbar IDs to do that.

For example, I would use this feature to close all snackbars when my user navigate to another page.

**Comment by iamhosseindhv** [comment]
Seems like a good idea @alexisab 👍🏼. I'll keep the issue and add this to future version.

**Comment by alexisab** [comment]
Great ! Thank you for your awesome work :smile:

**Comment by FabianoLothor** [comment]
Some news about this feature?

I cannot found nothing about this on docs: https://iamhosseindhv.com/notistack

**Comment by alexisab** [comment]
I've submitted a PR #123 to fix the README documentation that has been merged but I didn't touched the website

**Comment by iamhosseindhv** [comment]
Readme stuff has been moved to docs website: 

https://iamhosseindhv.com/notistack#closesnackbar
