### ISSUE TITLE
Ability to provide custom children prop to SnackbarItem through SnackbarProvider

### ISSUE THREAD

**Issue by elys1um** [iamhosseindhv/notistack#127]
I'd like to customize every snackbar I display without having to pass the same `children` property to `enqueueSnackbar` as `options`.
Usually, to customize every snackbar, the prop would be set on the `SnackbarProvider` which passes it down to every `SnackbarItem`. Since `children` is a prop that's already used by the `SnackbarProvider` to render its own children, this is not possible.

I'm proposing to add a new `snackbarChildren` prop on the SnackbarProvider which would be passed down as `children` to `SnackbarItem`

Code snippets:
`children` prop is destructured [here](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarProvider.js#L202).
Take the `snackbarChildren` prop here as well and pass as children to `SnackbarItem`

**Comment by iamhosseindhv** [comment]
@elys1um I agree this would be useful and will be added to the library. However, this is part of a larger set of changes that simply internals in notistack, and therefore might take longer to get published. 

Unfortunately, you'll have to use `children` in options parameter of `enqueueSnackbar` in the meantime.
