### ISSUE TITLE
SnackbarProvider start to complain about `base` and `message` classes

### ISSUE THREAD

**Issue by gencer** [iamhosseindhv/notistack#128]
## Expected Behavior
I should be able to style `base` and `message` parts of snackbar classes in `SnackbarProvider`.

## Current Behavior
Latest version breaks this and my app start to gave errors.

## Steps to Reproduce
```
  <SnackbarProvider maxSnack={5}
    classes={{
      variantSuccess: classes.success,
      variantError: classes.error,
      variantWarning: classes.warning,
      variantInfo: classes.info,
      root: classes.root,
      base: classes.base,   <= HERE
      message: classes.message, <= AND HERE
    }}
  </SnackbarProvider>
```

See, It was working few days ago. After I upgraded yarn packages along with notistack, it stop working. Now it complains about `base` and `message` parts. And when I remove those classes, my snackbar looks ugly (due to loss of styling).

## Error

```
TS2322: Type '{ variantSuccess: any; variantError: any; variantWarning: any; variantInfo: any; root: any; message: any; base: any; }' is not assignable to type 'Partial<Record<CombinedClassKey,string>>'.
  Object literal may only specify known properties, and 'message' does not exist in type 'Partial<Record<CombinedClassKey, string>>'.
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.8.6  |
| React        |  16       |
| Browser      |  Chrome       |

It was working and now it is not. What changed?

**Comment by iamhosseindhv** [comment]
The type error is expected: 

https://github.com/iamhosseindhv/notistack/blob/master/src/index.d.ts#L36

we only allow material-ui `SnackbarClassnames` and variant classnames to be passed:

```javascript
export type NotistackClassKey = 'variantSuccess' | 'variantError' | 'variantInfo' | 'variantWarning';
```
And nothing has changed in recent versions regarding this.
