### ISSUE TITLE
Export context so we can consume it using new contextType

### ISSUE THREAD

**Issue by pantharshit00** [iamhosseindhv/notistack#13]
Yesterday React 16.6 was released and introduced the new `static contextType` in the class
https://reactjs.org/blog/2018/10/23/react-v-16-6.html#static-contexttype

So can you please export the `SnackBarNext` context so that we may consume this component using this new API, we only need to export it :smile: . You may also export the `SnackbarContext`

I can make a PR if you say

**Comment by pantharshit00** [comment]
@iamhosseindhv any update?

**Comment by iamhosseindhv** [comment]
@pantharshit00  Do you have a specific use case in mind that requires access to `SnackbarContext`/`SnackbarContextNext`?

**Comment by iamhosseindhv** [comment]
`SnackbarContextNext` will be exported in next version. I've added this to [CHANGELOG](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md).

**Comment by iamhosseindhv** [comment]
You can access SnackbarContext in the following way:

```javascript
import { SnackbarContextNext } from 'notistack/build/SnackbarContext'
```
