### ISSUE TITLE
Why no onShow callback?

### ISSUE THREAD

**Issue by kg-currenxie** [iamhosseindhv/notistack#131]
## Context
We want to play a sound for specific notifications. However if you queue up 10 notifications, while having for example a maximum of 3, the sounds wouldn't sync with each notification.

## Expected Behavior
We should be able to know when a notification becomes visible (because it can come from the queue).

## Current Behavior
We would have to play 10 sounds at the moment when we queue the notifications. That would play all 10 sounds, rather than the amount that are actually visible.

**Comment by iamhosseindhv** [comment]
Have you tried passing `onEntered` callback in the options parameter of `enqueueSnackbar`?
https://iamhosseindhv.com/notistack/api

**Comment by kg-currenxie** [comment]
Oops, sorry. I was just looking at the examples, and not the full reference 😅
