### ISSUE TITLE
On examples of documentation, on Custom Snackbar, if you open two snackbars and expend one, it will overlap the other

### ISSUE THREAD

**Issue by conmeconte** [iamhosseindhv/notistack#132]
## Expected Behavior
When one of the snackbar is expended, the other snackbar should reposition to not overlap with the expended snackbar

## Current Behavior
When there are two expendable snackbars and one is expended, it overlaps the other

## Steps to Reproduce
Go to https://iamhosseindhv.com/notistack/demos#custom-snackbar. On custom snackbar demo, click the button to open two snackbars(you might have to click twice within short time interval to have two snackbars on the screen). 
Expend the bottom snack bar. 
You will see that the expended snackbar is overlapped with the other snackbar. 

## Context
I have a need to display two expendable snackbars on the same screen, and because of this issue, the title or content of the individual snackbar is blocked. 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.8.6  |
| React        | 16.8.5        |
| Browser      |   Chrome Version 74.0.3729.169 (Official Build) (64-bit)      |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
#167
