### ISSUE TITLE
useSnackbar: Cannot read property 'handleEnqueueSnackbar' of undefined

### ISSUE THREAD

**Issue by dp21g** [iamhosseindhv/notistack#133]
## Expected Behavior

Should load without error when consuming via hook.
`const { enqueueSnackbar, closeSnackbar } = useSnackbar();`

## Current Behavior

    Throws an error `Cannot read property 'handleEnqueueSnackbar' of undefined`.

## Steps to Reproduce

Link: https://codesandbox.io/s/strange-bird-jclt4

1. import useSnackbar
2. add `const { enqueueSnackbar, closeSnackbar } = useSnackbar();`
Page should now fail and show an error.

**Comment by iamhosseindhv** [comment]
You forgot to wrap your app inside a `SnackbarProvider`. See [basic usage](https://iamhosseindhv.com/notistack) for more info.

working example: 
https://codesandbox.io/s/gifted-https-ply3y

**Comment by dp21g** [comment]
![Doh!!!](https://media.giphy.com/media/xT5LMzIK1AdZJ4cYW4/giphy.gif)

Thank you!

**Comment by Miniland1333** [comment]
Do you think it would be worthwhile if the error message was more explicit? Something like:
`Cannot read property 'handleEnqueueSnackbar' of undefined. Are you sure that you wrapped your app in SnackbarProvider?`

**Comment by michaeljwiebe** [comment]
@Miniland1333 yes that would be nice, but this is a standard error coming from a higher level than notistack. i'm thinking it would be really complicated/impossible to handle that in this package.

**Comment by MernDev0603** [comment]
great!!!!!

**Comment by SashaDesigN** [comment]
I just did all as explained in the sample it didn't worked for me
I have NextJS App, for dev it works good for production build it gives me that error
