### ISSUE TITLE
notistack overrides the app's font

### ISSUE THREAD

**Issue by khanhdinovative** [iamhosseindhv/notistack#135]
## Expected Behavior
notistack should not override the web fonts

## Current Behavior
It overrides the font whenever it appears on the screen

## Steps to Reproduce
Just use material-ui with the custom font, unlike default Roboto

![font override](https://user-images.githubusercontent.com/47027388/59728345-ddac8780-9263-11e9-8ac7-1b7214705ad7.gif)

## Your Environment
I use CRA

| Tech         | Version |
|--------------|---------|
| Notistack | v0.8.6  |
| React        |  v16.8.6       |
| Browser      |    Chrome     |
|@material-ui/core |v4.1.1 |
|@material-ui/icons |v4.2.0 |
|@material-ui/pickers |v3.1.1 |
|@material-ui/styles |v4.1.1 |

**Comment by DASPRiD** [comment]
I think I had that problem recently: Make sure to have the SnackbarProvider **inside** the MutiThemeProvider.

**Comment by iamhosseindhv** [comment]
Thanks @DASPRiD 
Please confirm if the solution above solves your issue, otherwise please provide a sandbox reproduction.

Thanks.

**Comment by vbourgeois** [comment]
Hello,

I have the same issue. It is reproducible using Mui 4.1.3 using a custom font for typography and notistack 0.8.8.
Moving SnackbarProvider inside the MutiThemeProvider didn't solve the issue for me.

**Comment by a-pavlov-parc** [comment]
There is still the issue
