### ISSUE TITLE
Swipe to dismiss

### ISSUE THREAD

**Issue by pctestjfarz** [iamhosseindhv/notistack#138]
Yes, I was wondering if there was a way to make the notifications dismiss on swipe for when someone accesses my website on mobile.  I currently have a close button but was trying to figure out how to make them close on swipe as well.

Thanks,
Jon

**Comment by iamhosseindhv** [comment]
That's a great feature and a part of major changes in notistack. Added to the CHANGELOG.

**Comment by Yuripetusko** [comment]
Is this implemented? Can't see it in documentation

**Comment by micktg** [comment]
Bump. I would really like this feature.
