### ISSUE TITLE
Error when using yarn plug'n'play: prop-types missing from dependencies

### ISSUE THREAD

**Issue by dgreuel** [iamhosseindhv/notistack#139]
Package "notistack@0.8.7" (via "/Users/dan/Library/Caches/Yarn/v4/npm-notistack-0.8.7-02776a28232f27b0aae669572170bacac1a88b70/node_modules/notistack/build/SnackbarItem/SnackbarItem.js") is trying to require the package "prop-types" (via "prop-types") without it being listed in its dependencies (react, react-dom, @material-ui/core, classnames, hoist-non-react-statics, react-is, notistack)

**Comment by iamhosseindhv** [comment]
Thanks for pointing this out. fix has been published as version `v0.8.8`

**Comment by jhrinoa** [comment]
Oh. sorry and thanks for fixing this. I should have tested thoroughly especially when dealing with package.json. Lesson learned. Thanks.
