### ISSUE TITLE
multiple snackbars at once

### ISSUE THREAD

**Issue by ysgk** [iamhosseindhv/notistack#14]
First, thanks for this project 😍 

I want show multiple flash messages on page load,  but I can't do that. (Maybe because notistack uses `new Date().getTime()` for its component's key prop?)

```js
// This code shows only the last flash message.
componentDidMount() {
  const { enqueueSnackbar, flashes } = this.props
  flashes.forEach(flash => {
    enqueueSnackbar(flash.message)
  })
}
```

I found a workaround for this, but I think this is a little hacky.
```js
componentDidMount() {
  const { enqueueSnackbar, flashes } = this.props
  setTimeout(() => {
    flashes.forEach(flash => {
     enqueueSnackbar(flash.message)
    })
  })
}
```

Do you have any plan to support such a case?

**Comment by iamhosseindhv** [comment]
#15 is on its way and will fix this issue.

so you'll be able to do something like: 
```javascript
componentDidMount = () => flashes.forEach(this.props.enqueueSnackbar);
```

**Comment by iamhosseindhv** [comment]
@ysgk this fix is available in the latest version.

**Comment by ysgk** [comment]
Thank you for your kindness. It works fine now!
