### ISSUE TITLE
Snackbar resizing

### ISSUE THREAD

**Issue by axel-habermaier** [iamhosseindhv/notistack#141]
Hello,

when the height of a snackbar changes (i.e., when the browser window is resized or when a expansion panel is used as in the demo), multiple snackbars can overlap each other. The problem seems to be that the y-position of a snackbar is computed from the snackbar heights, which are only updated on component mount.

Is there a workaround?

Thanks
Axel

**Comment by iamhosseindhv** [comment]
Working in this feature/fix. Any help is appreciated. #167
