### ISSUE TITLE
StrictMode changing behaviour of enqueued notifications

### ISSUE THREAD

**Issue by justynspooner** [iamhosseindhv/notistack#143]
When wrapping the demo app in `<React.StrictMode />` the behaviour of enqueued notifications changes.

## Expected Behavior
When enqueuing a new notification, it should dismiss the previous one in order to show the new one straight away.

## Current Behavior
When enqueuing a new notification, it doesn't display until the auto hiding timeout for the previous notification has been hit. Then it shows the newly enqueued notification.

## Steps to Reproduce
Open the following code sandbox which is the basic demo with <React.StrictMode /> wrapping the app. Enqueue some notifications and notice how old notifications are not dismissed when new ones are enqueued.

[![Edit notistack-simple-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/notistack-simple-example-1swum?fontsize=14)

```
<React.StrictMode>
      <SnackbarProvider maxSnack={1}>
            <MyApp />
      </SnackbarProvider>
</React.StrictMode>
```

If I create a production build of the code, then it works fine as StrictMode is not being used. In development though, the behaviour is changed.

**Comment by iamhosseindhv** [comment]
That's due to use of `RootRef` component in `SnackbarItem.js` which now has been removed in #167 .
Merging that PR should fix the issue.
