### ISSUE TITLE
Cannot read property 'handleEnqueueSnackbar' of undefined

### ISSUE THREAD

**Issue by sajja94** [iamhosseindhv/notistack#145]
i try to use notistack like following. but it given 'Uncaught TypeError: Cannot read property 'handleEnqueueSnackbar' of undefined'

`import { SnackbarProvider, useSnackbar } from 'notistack';
const ConfigureRateList = ()=>{ const { enqueueSnackbar } = useSnackbar(); //codes... return( <SnackbarProvider maxSnack={3}> // codes.... </SnackbarProvider > ) }`

**Comment by iamhosseindhv** [comment]
@sajja94  `useSnackbar` or `withSnackbar` should be at least one level down the tree. meaning that they're not accessible in the component where you wrap your app in a `SnackbarProvider`. and are accessible in the children of that component.

**Comment by jgentes** [comment]
The getting started guide shows this use case, does it not?
https://notistack.com/getting-started

```
import { SnackbarProvider, enqueueSnackbar } from 'notistack'

const App = () => {
  return (
    <div>
      <SnackbarProvider />
      <button onClick={() => enqueueSnackbar('That was easy!')}>Show snackbar</button>
    </div>
  )
}
```
