### ISSUE TITLE
Documentation: active snackbar from notistack can resets theme colors

### ISSUE THREAD

**Issue by keul** [iamhosseindhv/notistack#146]
## Expected Behavior

Snackbars item opened by notistack should not change the global theme, and it's not doing it, but documentation can lead users to wrong nesting.

## Steps to Reproduce

Take the codesanbox link below. I'm more or less reproducing what docs says:

```
<SnackbarProvider maxSnack={3}>
    <App />
</SnackbarProvider>
```

...but I've also a custom `ThemeProvider`

https://codesandbox.io/s/notistack-issue-3673u

## Context

The issue is easily fixable: the `SnackbarProvider` component should be wrapped _inside_ the custom `ThemeProvider`, but documentation is not helping.

I think that a clear indication about this can save debug time or issue report.

**Comment by iamhosseindhv** [comment]
Thanks @keul ❤️
The following line has been added to the docs [website](https://iamhosseindhv.com/notistack): 
```
Note: If you're using material-ui ThemeProvider, make sure SnackbarProvider is a child of it.
```

Hopefully it be useful in future.
