### ISSUE TITLE
SnackbarProvider persist attribute

### ISSUE THREAD

**Issue by FabianoLothor** [iamhosseindhv/notistack#148]
Exist some way that I can set all SB as persist?

My idea:

```jsx
<SnackbarProvider
            persist
    >
...
```

**Comment by iamhosseindhv** [comment]
Applying `persist` to all snackbars wouldn't make sense because it has no effect. oldest snackbar will be dismissed anyway, when `maxSnack` is reached. 
https://iamhosseindhv.com/notistack/demos#persist-snackbar

**Comment by FabianoLothor** [comment]
> Applying `persist` to all snackbars wouldn't make sense because it has no effect. oldest snackbar will be dismissed anyway, when `maxSnack` is reached.
> https://iamhosseindhv.com/notistack/demos#persist-snackbar

Yes, but so what?

If I want that all of my snacks are persist I need to explicit this in all calls, this is a lot of unnecessarily work.

**Comment by FabianoLothor** [comment]
The problem is not the snack dismissed when another will trigger, the problem here is the snack close after five seconds.

I need that my user see the alert.

**Comment by iamhosseindhv** [comment]
@FabianoLothor  for your usecase `persist` is not the right prop to use.

```jsx
<SnackbarProvider
    autoHideDuration={null}
>
```

**Comment by FabianoLothor** [comment]
> @FabianoLothor for your usecase `persist` is not the right prop to use. Try using the following instead.
> 
> ```js-jsx
> <SnackbarProvider
>     autoHideDuration={null}
> >
> ```

Ty! o/
