### ISSUE TITLE
the message always delay

### ISSUE THREAD

**Issue by thomas81528262** [iamhosseindhv/notistack#149]
## Context

    The user always complain about no response after they do the action.
    Now the temporary solution is modified the code in every page, do you have other solution?
```javascript
const showMsg = ({ msg, persist, variant }) => {

    const now = new Date();
    const timeStr = dateFormat(now, "m/d, H:MM:ss");

    closeSnackbar();
    enqueueSnackbar(`${msg}   (${timeStr})` , {
      persist,
      variant,
      action: key => (
        <IconButton aria-label="delete" className={classes.margin} onClick={() => { closeSnackbar(key) }}>
          <DeleteIcon />
        </IconButton>
      )
    });
```

![captured (3)](https://user-images.githubusercontent.com/20622045/61970734-3b826c80-af92-11e9-8bea-23f046720f66.gif)

**Comment by iamhosseindhv** [comment]
Please elaborate a bit more. Will reopen the issue if it still persists.
