### ISSUE TITLE
Be able to add a close snack bar action button to SnackBarProvider

### ISSUE THREAD

**Issue by njetsy** [iamhosseindhv/notistack#156]
## Expected Behavior
This is more of a feature request, but it would be very helpful and save a lot of boilerplate code to be able to add a dismiss button as the action prop in the SnackBarProvider.

## Current Behavior
There is no way to define a dismiss button as the action in the SnackBarProvider since the closeSnackbar function is not accessible at the same level as the SnackBarProvider (Unless I missed something??).

## Context
I really like this library and would like to replace the current notification dependency we are using with it. We have to have a dismiss button/icon on all of our notifications though and there is a lot of added boilerplate to have to add the additional action button to every single enqueSnackbar call. 

I was trying to think of a few different solutions but wasn't sure which was the most practical. Passing a reference to the close function in addition to the key in the finalAction might work. Or adding a separate prop to the SnackBarProvider to show a dismiss button could be another option. Adding a global SnackItem "template" similar to the children prop in enqueSnackbar could be another solution. But in that case you would still want access to all other other props like variant.

**Comment by Zhouzi** [comment]
For the record, what you are looking for used to be a default. You should be able to implement it back this way:

```js
import { IconButton } from '@material-ui/core';
import { Close as IconClose } from '@material-ui/icons';
import { useSnackbar } from 'notistack';
import * as React from 'react';

function SnackbarCloseButton({ key }) {
  const { closeSnackbar } = useSnackbar();

  return (
    <IconButton onClick={() => closeSnackbar(key)}>
      <IconClose />
    </IconButton>
  );
}

export default SnackbarCloseButton;
```

```js
<SnackbarProvider action={key => <SnackbarCloseButton key={key} />}>
  ...
</SnackbarProvider>
```

**Comment by njetsy** [comment]
Ah yes, this is great! Thank your for the assist! I just had to change the key prop to id since key is a restricted word. Thanks again!

**Comment by jonenst** [comment]
The following works too, without creating additional components.. Are there any downsides ?
```jsx

const notistackRef = useRef();

<SnackbarProvider
            ref={notistackRef}
            action={(key) => (
                <Button
                    onClick={() => notistackRef.current.closeSnackbar(key)}
                    style={{ color: '#fff', fontSize: '20px' }}
                >
                    ✖
                </Button>
            )}
...
</SnackbarProvider>
```

**Comment by jonenst** [comment]
@Zhouzi Do you know when and why the default was changed ? Thanks

**Comment by Zhouzi** [comment]
> The following works too, without creating additional components.. Are there any downsides ?
> 
> ```js-jsx
> const notistackRef = useRef();
> 
> <SnackbarProvider
>             ref={notistackRef}
>             action={(key) => (
>                 <Button
>                     onClick={() => notistackRef.current.closeSnackbar(key)}
>                     style={{ color: '#fff', fontSize: '20px' }}
>                 >
>                     ✖
>                 </Button>
>             )}
> >
> ...
> </SnackbarProvider>
> ```

Unless documented, I would consider a component's methods a private API. For example, it would break if the methods become private or if `SnackbarProvider` becomes a function component.

> @Zhouzi Do you know when and why the default was changed ? Thanks

I wish I had given that information in my first comment. Sadly, I can't remember when it was removed (and I probably never knew why). From what I recall, in the early versions of the library you could provide a default component for the close button. Something like: `<SnackbarProvider action={<button>close</button>} />`. And it would "just work™️".

To be fair, I think it was a good choice to remove it. The new API has no magic and is easier to control.

**Comment by jonenst** [comment]
Ok thanks.

Also if the SnackbarProvider ref changes one day, we can always do something like:
```jsx
const GimmeTheRefAlready = (props) => {
  props.setref(useSnackbar());
  return null;
}
...
const ref = useRef();
<SnackbarProvider>
<GimmeTheRefAlready setref={(notistack) => {ref.current=notistack}}/>
...
</SnackbarProvider>
```

I wonder if we can simplify this further

**Comment by myou11** [comment]
> For the record, what you are looking for used to be a default. You should be able to implement it back this way:
> 
> ```js
> import { IconButton } from '@material-ui/core';
> import { Close as IconClose } from '@material-ui/icons';
> import { useSnackbar } from 'notistack';
> import * as React from 'react';
> 
> function SnackbarCloseButton({ key }) {
>   const { closeSnackbar } = useSnackbar();
> 
>   return (
>     <IconButton onClick={() => closeSnackbar(key)}>
>       <IconClose />
>     </IconButton>
>   );
> }
> 
> export default SnackbarCloseButton;
> ```
> 
> ```js
> <SnackbarProvider action={key => <SnackbarCloseButton key={key} />}>
>   ...
> </SnackbarProvider>
> ```
> 
> You are right about the context. The thing is that, although the action is passed at the same level as the creation of the context, the action itself is only created further down in the tree at a point where the context is available.

Hi @Zhouzi and @iamhosseindhv, this example does not seem to work and I'm unsure as to why. If you look at this codepen, I have implemented your example slightly differently by putting the action in the enqueueSnackbar hook options. When multiple snackbars are on the screen, pressing the close icon on one of them will close all of them instead of just the one you click on. If you uncomment the action property right above the current action that I have it using, then the example will work. The issue seems to be that the `key` is not being passed to the functional component from another file when using a lambda that returns a functional component. However, if you directly return the component in the lambda, then closing the snackbars individually works as intended.
Do you know why the `key` is not being passed to the functional component in a different file?

**Comment by iamhosseindhv** [comment]
You're almost there @myou11 

`key` is a keyword in react and shouldn't be used as a prop to pass values to a component. Just rename `key` to whatever you like (also not `ref`).

```diff
this.props.enqueueSnackbar("Customise this snackbar youself.", {
      variant: "default",
      action: (key) => {
        console.log("key in handleClickWithAction:", key);
-       return <SnackbarCloseButton key={key} />;
+       return <SnackbarCloseButton id={key} />;
      }
});
```

**Comment by myou11** [comment]
Ah thank you very much @iamhosseindhv! I knew I was missing something simple; it works great now. You just made my Friday 😃

**Comment by Zhouzi** [comment]
Sorry for the confusion, I have updated the example I provided earlier to avoid clashing with the reserved keyword.

**Comment by myou11** [comment]
No worries @Zhouzi, I should have realized key was reserved. I thought the console would tell me, but I guess not 🤷‍♂️  Thanks for keeping the example up to date!

**Comment by iamhosseindhv** [comment]
@myou11 Follow up  https://reactjs.org/warnings/special-props.html

**Comment by NicholasMcGrath** [comment]
> ```js
> snackbarKey
> ```

This through me off, using the prop name key does not work but other names do

**Comment by adjenks** [comment]
> The following works too, without creating additional components.. Are there any downsides ?
> 
> ```js
> const notistackRef = useRef();
> 
> <SnackbarProvider
>             ref={notistackRef}
>             action={(key) => (
>                 <Button
>                     onClick={() => notistackRef.current.closeSnackbar(key)}
>                     style={{ color: '#fff', fontSize: '20px' }}
>                 >
>                     ✖
>                 </Button>
>             )}
> >
> ...
> </SnackbarProvider>
> ```

Thanks for the easy copy paste. I just changed it a bit to not use the ref:

```jsx
import { SnackbarProvider, enqueueSnackbar, closeSnackbar } from 'notistack'

const app = <SnackbarProvider
    autoHideDuration={60000}
    maxSnack={5}
    action={(key) => (
        <Button
            onClick={() => closeSnackbar(key)}
            style={{ color: '#fff', fontSize: '20px' }}
        >
        ✖
        </Button>
)}
>
...
</SnackbarProvider>
```
