### ISSUE TITLE
Multiple deprecated dependencies

### ISSUE THREAD

**Issue by somahargitai** [iamhosseindhv/notistack#157]
When installing, I receive multiple messages about deprecated dependencies

I have tried to add notistack to my project
+ notistack@0.8.9

Current project:
"react": "^16.6.3",

received deprecated messages like:
```
deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained.
deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy 
deprecated fsevents@1.2.4: Way too old
```

It does not look like something safe

**Comment by iamhosseindhv** [comment]
Can you run `npm ls core-js`, `npm ls core-js` and `npm ls core-js` in your project's root directory and share the outputs here. Thanks

**Comment by iamhosseindhv** [comment]
closed for now due to inactivity.
