### ISSUE TITLE
Snackbar didn't hide if click multiple times on it.

### ISSUE THREAD

**Issue by jocage** [iamhosseindhv/notistack#158]
If click multiple times (10-15 for example) on opened Snackbar, message stay active and didn't hide.
Reproduced on the demo as well: 
[codesandbox](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/simple-example??hidenavigation=1&module=%2FApp.js)

**Comment by iamhosseindhv** [comment]
Do you mean the snackbar itself or dismiss button? Snackbars aren't supposed to get dismissed when clicked on them

**Comment by jocage** [comment]
Snackbar itself. 
Snackbar hide after 5 sec (with default props), but in this time stay in place after clicking in them.
Also if click 5-10 times should wait mode then 5 sed till Snackbar will hide.

**Comment by iamhosseindhv** [comment]
Could you share a gif/video of the scenario you're describing please.

**Comment by iamhosseindhv** [comment]
closed for now due to inactivity.
