### ISSUE TITLE
Enqueue snackbar without hooks or HOC

### ISSUE THREAD

**Issue by amirqasemi74** [iamhosseindhv/notistack#159]
I need to enqueue snackbar without using hooks or hocs...
```js
import { enqueueSnackbar } from 'notistack';

class UserViewModel {
  didMount(){
    try {
       ...
    }catch(e){
       enqueueSnackbar(e.message);
    }
  }
}
```

like `react-toastify`...

**Comment by iamhosseindhv** [comment]
Hopefully that has fixes your issue. closed due to inactivity.

**Comment by amirqasemi74** [comment]
i think if you provide this solution inside your library as feature is better than every one who want to use it like me wrap your library in to it's own...
it could be a cool feature...
