### ISSUE TITLE
Change Display Order of Snack for Top Anchor

### ISSUE THREAD

**Issue by david-chau** [iamhosseindhv/notistack#160]
Is there a way to sort the notifications for top anchor?
I would like the latest snack to pop up on top of the queue instead of bottom (simliar to bottom anchor) if the position is in the top.

Demo: https://codesandbox.io/embed/notistack-example-3ek56

**Comment by david-chau** [comment]
Adding screenshot for reference, it should display Snack #3-1 instead of #1-3.

![image](https://user-images.githubusercontent.com/49044127/64437707-c7f57400-d094-11e9-8c5f-7b02fe449392.png)

**Comment by iamhosseindhv** [comment]
This is a nice feature. 👍🏼 I've added it to the CHANGELOG and it's be implemented in the next releases.

**Comment by vbstreetz** [comment]
Hey. Did this ever land in master?

**Comment by superwesker1988** [comment]
Hi @iamhosseindhv , what is the props for configuring this feature?

**Comment by iamhosseindhv** [comment]
Nope, This hasn't been implemented yet.

**Comment by avennn** [comment]
any progress on this issue?
