### ISSUE TITLE
maxSnack doesn't work when call a lot enqueueSnackbars coincidentally 

### ISSUE THREAD

**Issue by tomzaku** [iamhosseindhv/notistack#161]
maxSnack doesn't work when calling a lot of enqueueSnackbars coincidentally 

## Expected Behavior
They should hide snack bar if the current stack bar exceed maxSnack

## Current Behavior

Show all notifications without hiding 
## Steps to Reproduce

Link: https://codesandbox.io/s/notistack-redux-example-gyw9u

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.?.?  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
duplicate #38
