### ISSUE TITLE
Time in queue

### ISSUE THREAD

**Issue by alenxmedia** [iamhosseindhv/notistack#162]
Hello,

 I send multiple messages at the same time.  autoHideDuration is set to 5 sec. Their await auto hide time stacks up in the queue, so if I send 3 messages the last message will be shown for 15 sec. 
Is there a way to avoid autoHideDuration stacking up, so the message is displayed only for 5 sec.?

**Comment by iamhosseindhv** [comment]
@alenxmedia 

what I'm experiencing is that snackbars get dismissed after `autoHideDuration` of 5 secs in the gif below. No sign of accumulation.

![Kapture 2019-09-11 at 22 29 22](https://user-images.githubusercontent.com/26996372/64736978-c4724a80-d4e3-11e9-9959-3b610239ab86.gif)


Can you provide a reproduction of the issue you're describing?

**Comment by alenxmedia** [comment]
Hello, 
Thanks for looking into this. Here is recording of my app:
![Recr](https://user-images.githubusercontent.com/22632395/64763137-b8b47180-d53f-11e9-872e-94fd019114b2.gif)

Here is my code:
```
let snackOptions = {
			variant: "error",
			preventDuplicate: true,
			autoHideDuration: 4000
		}
this.props.enqueueSnackbar("Error 1.", snackOptions);
this.props.enqueueSnackbar("Error 2.", snackOptions);
```

**Comment by kaienbcjdoapwkfldue** [comment]
I am experiencing the same, the times accumulate

**Comment by el1f** [comment]
It would be extremely helpful if you guys were able to take the time to replicate the issue in an environment like codesandbox or something similar :)

**Comment by TheLogan** [comment]
I don't think it's environment, cause I have stacking on the demo site too, I tried it in both Firefox and Chrome though, and both of them accumulated the time, so the 3rd snackbar took 3 times as long time as the first one.

**Comment by iamhosseindhv** [comment]
Guys reproduction is needed to to any furthur

**Comment by TheLogan** [comment]
In case someone is looking for a workaround this snippet will do the trick
```
createSnackbar(message: string, options: OptionsObject) {
    this.props.enqueueSnackbar(message, options);
    setTimeout(() => {
      this.props.closeSnackbar(options.key);
    }, 2000);
  }
```
