### ISSUE TITLE
Huge file size

### ISSUE THREAD

**Issue by mehmetkose** [iamhosseindhv/notistack#163]
Seems like it's even bigger than react. How can be possible? 

![withsnackbar](https://user-images.githubusercontent.com/706678/64710997-9a0f9580-d4c1-11e9-9822-5e211e787faf.png)

**Comment by oliviertassinari** [comment]
Dropping MUI v3 support https://github.com/iamhosseindhv/notistack/blob/73ecdf9cc991008f8e4cbbde6acb3102c9d4c711/src/SnackbarItem/SnackbarItem.styles.js#L41

and using `clsx` instead of `classnames` could help a bit

https://github.com/iamhosseindhv/notistack/blob/73ecdf9cc991008f8e4cbbde6acb3102c9d4c711/src/SnackbarItem/SnackbarItem.js#L2

**Comment by oliviertassinari** [comment]
- Migration from the class to the hook API (for the internal building of the library would help.
- The usage of https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types would help

**Comment by andrewmclagan** [comment]
Yes, it is rather large: https://bundlephobia.com/result?p=notistack@0.9.6

**Comment by oliviertassinari** [comment]
Another leverage I have just thought of. Instead of a custom alert component, we could explore using this one: https://material-ui.com/components/alert/.

**Comment by andrewmclagan** [comment]
Agreed. Currently for a notifications stack, its pretty huge. Its about the same size as react-router.

**Comment by oliviertassinari** [comment]
@andrewmclagan What other dependencies do you have in your package.json? (looking for opportunities of third-party libraries to reduce bundle size)

**Comment by D1plo1d** [comment]
Just installed notistack 0.9.11 and it adds ~50KB to my builds using `parcel build --experimental-scope-hoisting`. I'm hoping more bundle size optimizations can be done. On a small preact + material-ui page notistack that 50KB is 20% of my 250KB bundle.

**Comment by iamhosseindhv** [comment]
Of course improving bundle size is an ongoing thing and there's always room for improvement, but https://github.com/iamhosseindhv/notistack/pull/268 made a good step towards a smaller bundle size.
<img width="623" alt="Screenshot 2020-05-15 at 03 19 22" src="https://user-images.githubusercontent.com/26996372/82004477-e87dc100-965a-11ea-9f24-a2855a3936a5.png">
Closing this but always open for suggestions.
