### ISSUE TITLE
React Hook useEffect has a missing dependency: 'enqueueSnackbar'.

### ISSUE THREAD

**Issue by grubxy** [iamhosseindhv/notistack#165]
there is a warning 'React Hook useEffect has a missing dependency: 'enqueueSnackbar'.' when use enqueueSnackbar in useEffect.

**Comment by iamhosseindhv** [comment]
That's probably a linting warning that be fixed by passing an empty array:

```javascript
useEffect(() => {
      
}, []); // <-- this guy
```

Let me know if that didn't solve the issue.

**Comment by grubxy** [comment]
"[]" didn't solve the warning..
I add a param like this,there is no warning,is this method ok?
```
 const { enqueueSnackbar } = useSnackbar();
useEffect(() => {
  }, [enqueueSnackbar])
```

**Comment by grubxy** [comment]
@iamhosseindhv
