### ISSUE TITLE
An option for full screen width and zero margin

### ISSUE THREAD

**Issue by nick-cromwell** [iamhosseindhv/notistack#170]
I had this working previously but with the refactored SnackbarContainer I'm unable to override the makeStyles classes. It would be great to have options to stretch the snackbar the full screen width and have zero margin.

**Comment by iamhosseindhv** [comment]
If you need this asap, you could use https://github.com/iamhosseindhv/notistack/pull/172 by doing the following:

```javascript
const styles = {
    snackContainer: {
        backgroundColor: 'orange',
        bottom: '0px !important',
        left: '0px !important',
        right: '0px !important',
        // etc.
    }
}


<SnackbarProvider 
    classes={{ containerAnchorOriginBottomLeft: classes.snackContainer }}
>
```

these keys are allowed: 

```typescript
export type ContainerClassKey =
    | 'containerAnchorOriginTopCenter'
    | 'containerAnchorOriginBottomCenter'
    | 'containerAnchorOriginTopRight'
    | 'containerAnchorOriginBottomRight'
    | 'containerAnchorOriginTopLeft'
    | 'containerAnchorOriginBottomLeft';
```

**Comment by nick-cromwell** [comment]
Thanks, I'll give this a try.

**Comment by matchmakers69** [comment]
hi, have an issue to set Snackbar 100% width I am using typescript and MUI5 with Typescript

**Comment by iamhosseindhv** [comment]
@matchmakers69  I might be able to help if you provide a minimal working example / reproduction.
