### ISSUE TITLE
Without MUI?

### ISSUE THREAD

**Issue by FabianoLothor** [iamhosseindhv/notistack#171]
Is it possible  use this library without MUI?

**Comment by iamhosseindhv** [comment]
Not yet but support will be added in near future. Stay tuned ❤️

**Comment by FabianoLothor** [comment]
Some issue about this?

**Comment by Brettm12345** [comment]
@FabianoLothor take a look at [react-toastify](https://github.com/fkhadra/react-toastify)

**Comment by iamhosseindhv** [comment]
We now have an issue open for this: # 184 @FabianoLothor
