### ISSUE TITLE
SnackbarProvider impossible nesting

### ISSUE THREAD

**Issue by IraSkyx** [iamhosseindhv/notistack#174]
I believe there's not duplicate 

## Expected Behavior
Nesting SnackbarProvider should be possible, so we can override global behavior (like maxSnack, classes) on certain parts of an application. 

## Current Behavior
Nothing appears when you nest SnackbarProviders

## Steps to Reproduce

1. Put SnackbarProvider on top of your app
2. Place a second one whenever you want at component level 
3. Enqueue a snack from within the second Provider
4. Observe nothing appears

## Your Environment
Chrome 77.0.3865.90
Notistack 0.9.0
react 16.10.1

**Comment by el1f** [comment]
I don't think this is a very straightforward approach to the use case you're presenting. Generally speaking, you'd want your notification manager, especially when it's implemented in the way that it's done in this specific project, to be as consistent in its behaviours as possible. If you want to implement multiple Providers with multiple behaviours I think that the best and less error-prone way to do it would probably be to have different providers encapsulate different sections of your app without a parent SnackbarProvider.

**Comment by iamhosseindhv** [comment]
Given that most of the aspects of presenting snackbars can be massively overridden using options parameter of `enqueueSnackbar`, I don't see this as a priority/good practice.

Thanks for raising the issue though.
