### ISSUE TITLE
Extend functionality with `createPortal` approach

### ISSUE THREAD

**Issue by PeterMK85** [iamhosseindhv/notistack#178]
To able to target the root html element, the render place of `notistack`

**Comment by PeterMK85** [comment]
First glance plan:
Something like an optional prop to the provider, and if that exist, on the return, it should render into the defined selector element
https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarProvider.js#L201

More about portals:
https://reactjs.org/docs/portals.html

**Comment by PeterMK85** [comment]
@iamhosseindhv  wdyt?

**Comment by iamhosseindhv** [comment]
closing as corresponding PR is under review https://github.com/iamhosseindhv/notistack/pull/179
