### ISSUE TITLE
error: MOUNT ERROR TypeError: Cannot read property 'handleEnqueueSnackbar' of undefined

### ISSUE THREAD

**Issue by ziqri-tiketcom** [iamhosseindhv/notistack#183]
can u help me about this issue

**Comment by iamhosseindhv** [comment]
This is most likely happening because you've forgot to wrapp your app in a `SnackbarProvider`. see [basic usage](https://iamhosseindhv.com/notistack) docs for more info. If you have wrappend your and still have an issue, please provide some code.
