### ISSUE TITLE
Notistack without Material-UI? [POLL] 👍👎

### ISSUE THREAD

**Issue by iamhosseindhv** [iamhosseindhv/notistack#184]
This is not the first time I get asked this. 
> Is there any way to use notistack without material-ui dependency? 

People reached out to me in github issues, Instagram DMs and email, saying that they'd love to use notistack but their app is not built on Material-ui and therefore are not willing to add it as a dependency just for notistack.

**Upvote** 👍 this issue if you think notistack's target audience should be anyone that uses React, and not just material-ui users. Or let me know if you think otherwise. 

Worth mentioning that in both cases the API will remain untouched.

**Comment by hrafaelveloso** [comment]
Given the simplicity of integration, I think this package could be open to the whole React community. Regarding Material-UI dependency, is there a need to support Material-UI v3? This would reduce the bundle size according to the comment [of @oliviertassinari](https://github.com/iamhosseindhv/notistack/issues/163#issuecomment-540031672)

**Comment by FabianoLothor** [comment]
Some news about this issue?

**Comment by andrewmclagan** [comment]
A suggestions would be to create a mono repo with multiple packages under a new organisation with "drivers" for other UI libraries:

`yarn add @notistack/core @notistack/material-ui`

OR  

`yarn add @notistack/core @notistack/antd`

This abstraction could even be projected further and have drivers for UI rendering libraries:

 `yarn add @notistack/core @notistack/vue @notistack/vuetify`

**Comment by oliviertassinari** [comment]
@iamhosseindhv It would be awesome to see it used without following the Material Design specification! It's definitely something Material-UI wants to support. "Material to build UI" ;).

**Comment by NathTech** [comment]
+1 Yes please. sans material-ui would be lovely. I'm using react-bootstrap...

**Comment by vizardkill** [comment]
any news, about integrating material ui?.


I would love to see this package in material ui

**Comment by icharge** [comment]
Any update about this?

**Comment by ktrzos** [comment]
Are there any plans on removing Material UI dependency from this project? This issue exists for 1 year now...

**Comment by jameswilson** [comment]
We're in the same boat as others here.  We've rolled our own UI, but wanted to outsource this one component, because it is a fairly self-contained problem space, and one that nearly any decoupled app would need when communicating with backends, to notify of asynchronous errors and such.  Sadly the peerDependencies are not mentioned on npmjs.org project page nor on github project page.     

Adding this to our project added 96kb for Material-ui  +  34kb for this package (gzipped).   Thus we've opted for react-toastify instead which is 9kb gzipped. 😿

**Comment by tim-bloxsome** [comment]
>  Sadly the peerDependencies are not mentioned on npmjs.com project page nor on github project page.

I second that.

**Comment by iamhosseindhv** [comment]
Definitely this is a work in progress. You can track the progress in alpha branch. Downloadable from `npm i notistack@alpha`. which will be published as v2 as there are some breaking changes. With alpha version you'll have absolute control over the appearance of your snackbars.

Currently the only thing we're dependent on is Transition components (Slide, Grow, ...) from MUI. Once those are re-used or reimplemented, you'll be able to use notistack without MUI.

Any help with that is appreciated.

**Comment by Jammar** [comment]
I'd use this package if it worked w/o Material. big up!

**Comment by adam-pheedloop** [comment]
+1 for an option to use without the Material UI dependency

**Comment by ibrahimawadhamid** [comment]
+1 for use without material UI

**Comment by apevesting** [comment]
Any updates on this? This poll was open over 2 years ago...

**Comment by jsdaniell** [comment]
+1 for use without Material-UI

**Comment by carlospence** [comment]
I would have loved to use this package for a new project but because of the dependency on MUI which was not even stated on github or npmjs. I have been using react-toastify but wanted something more beautiful. I will be using react-hot-toast for this particular project and might check out notistack in later project.

+1 vote for use without Material-UI

**Comment by ibrahimawadhamid** [comment]
> I would have loved to use this package for a new project but because of the dependency on MUI which was not even stated on github or npmjs. I have been using react-toastify but wanted something more beautiful. I will be using react-hot-toast for this particular project and might check out notistack in later project.
> 
> +1 vote for use without Material-UI

Thanks for mentioning a few other options out there, I think i will use react-hot-toast from now on.

**Comment by iamhosseindhv** [comment]
Thanks everyone for the upvotes. You can track the progress here #421
