### ISSUE TITLE
Material-ui Typography deprecation warnings

### ISSUE THREAD

**Issue by JakubPetriska** [iamhosseindhv/notistack#19]
## Expected Behavior
No errors should show up.

## Current Behavior
Material UI error about using deprecated typography variant is shown.
![47221049-be4b1b00-d3b3-11e8-95ea-77847795ff2f](https://user-images.githubusercontent.com/5531859/47864782-c2872780-ddfa-11e8-9e94-55645a78b637.png)

| Tech         | Version |
|--------------|---------|
| Notistack | 0.3.7  |
| React        | 16.5.1 |
| Material UI        | 3.2.2 |
| Browser      | Chrome |

**Comment by kubalobo** [comment]
Propably something quite similar here:
![image](https://user-images.githubusercontent.com/3520560/47879204-50293e00-de20-11e8-9dc4-4c3ad61735b9.png)

**Comment by thaiKari** [comment]
I get the same as @kubalobo

**Comment by thaiKari** [comment]
Problem was solved for me when I upgraded to the newest version of material ui  :)

**Comment by JakubPetriska** [comment]
@iamhosseindhv I actually am using the new Typography variants.

**Comment by iamhosseindhv** [comment]
Have you tried isolating / commenting out notistack to make sure the warning is comming from notistack?  @jakubpetriska

If you think it's a notistack issue, please reproduce the warning and provide a link to codesandbox.

**Comment by JakubPetriska** [comment]
Yes I did and it confirmed that notistack is the issue. Ok I will try to reproduce that and post it here.

**Comment by JakubPetriska** [comment]
@iamhosseindhv The error can be seen in [this](https://codesandbox.io/s/3q0ooqz8l1) codesandbox. It's the minimal `notistack` usage example from [here](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/demo??hidenavigation=1&module=%2FApp.js) but I updated the `material-ui` dependency to version 3.2.2. The same thing happens for `material-ui` 3.4.0.

**Comment by iamhosseindhv** [comment]
@JakubPetriska  Downloaded the sandbox and I don't get any warning. 
Run `npm ls @material-ui/core  -g` and check if you have the same version of material-ui installed. (note the `-g` flag)

I'll have an eye on this issue in case more people complained about it.

**Comment by JakubPetriska** [comment]
The error happens in the sandbox. I didn't try to download it. Why is there a `-g` flag?

**Comment by iamhosseindhv** [comment]
To compare material/notistack versions installed under `/usr/local/lib` and your working directory. 

According to [docs](https://docs.npmjs.com/cli/ls), "List packages in the global install prefix instead of in the current project." So I was wondering maybe you have different versions of material/notistack installed globally and your working directory. 

What I just said might be irrelevant to the problem though.

**Comment by JakubPetriska** [comment]
I don't have either installed globally, which the output of the command you sent confirmed.

**Comment by pedro-dcc** [comment]
This happens to me too, and is notistack for sure... Any news how to fix?

**Comment by iamhosseindhv** [comment]
@pedro-dcc You should not get any warning regarding "Deprecated variants", if you have done material-ui [migration instructions](https://material-ui.com/style/typography/#migration-to-typography-v2).

@JakubPetriska The reason minimal example gives us deprecation warnings is that we don't use `theme` in it. so we can't set `Typography.useNextVariant` to true. However, I've added the following loc to the minimal example to avoid getting those nasty warnings:

https://github.com/iamhosseindhv/notistack/blob/master/demo/MessageButtons.js#L47
```javascript
// Avoid material-ui warnings. more info: https://material-ui.com/style/typography/#migration-to-typography-v2
window.__MUI_USE_NEXT_TYPOGRAPHY_VARIANTS__ = true;
```

**Comment by pedro-dcc** [comment]
@iamhosseindhv you are wrong. I'm already setting "useNextVariants" to true and the warning still happened. And is when i show some notistack snackbar.
Also, with release from today i get another warning
<img width="597" alt="screenshot 2018-11-19 at 22 20 24" src="https://user-images.githubusercontent.com/42931896/48738662-99afc080-ec49-11e8-8c87-fd343935ae50.png">

**Comment by iamhosseindhv** [comment]
Provide codesandbox @pedro-dcc

**Comment by iamhosseindhv** [comment]
Thanks for the update @JakubPetriska

**Comment by pedro-dcc** [comment]
> Provide codesandbox @pedro-dcc

Sorry for coming back so late. I was wrong. I have faced this issue only because I had the snackbar provider outside MuiTheme. After put that inside the warning has gone. Thanks.
