### ISSUE TITLE
Returned ID Renders on Screen

### ISSUE THREAD

**Issue by siya-mzam** [iamhosseindhv/notistack#191]
Hello.

Thanks so much for such a useful package.
We have just started using it in our project.

We have, however, noticed that there is an ID that is returned by the SnackbarProvider that gets rendered on the screen

Here is a snapshot of it to give you an idea
![Screen Shot 2019-11-07 at 11 44 44](https://user-images.githubusercontent.com/54799715/68385376-48eaed80-0162-11ea-9e41-4c1dcb14afe7.png)

And this is where that number comes from
![Screen Shot 2019-11-07 at 13 07 43](https://user-images.githubusercontent.com/54799715/68385397-57d1a000-0162-11ea-9034-f528a985c41b.png)

Is this the intended behavior or we may remove the return and file a PR?

Thanks
Siya

**Comment by iamhosseindhv** [comment]
I'm glad this has been helpful. ❤️

`enqueueSnackbar` returns a key that you can use to reference that snackbar. It's not supposed to be displayed on the screen though. Double check your codebase to make sure you're not accidentally displaying the key. 

thanks for using notistack.
