### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by gomesalexandre** [iamhosseindhv/notistack#193]
Hi there and thanks for notistack ❤️ it's amazing! 

The only issue I see currently is that the API is not correctly documented. 
Not a big issue for me as it was really well-typed, but vanilla JS or Flow users might have an issue in understanding the API. 

I'll play a bit more with it to understand it better, and contribute something soon!

🙏

**Comment by gomesalexandre** [comment]
Oh, actually it is on a separate page on your website :D 
Probably not optimal still, as we tend to expect it on the main README... what about having it there as well?

**Comment by iamhosseindhv** [comment]
We used to have documentation on REAME. But as the API grew I found it harder and harder to organise everything nicely in a .md file. Happy to improve README to emphasise the fact that documentation can be found on the website.
