### ISSUE TITLE
Invalid prop snack.message

### ISSUE THREAD

**Issue by MareoRaft** [iamhosseindhv/notistack#197]
## Current Behavior
We have been seeing the following appear in red in the JavaScript console fairly often:

    Warning: Failed prop type: Invalid prop `snack.message` supplied to `SnackbarItem`.
        in SnackbarItem (created by WithStyles(SnackbarItem))
        in WithStyles(SnackbarItem) (created by SnackbarProvider)
        in div
        in Unknown (created by WithStyles(undefined))
        in WithStyles(undefined) (created by SnackbarProvider)
        in SnackbarProvider (at src/index.js:46)
        in ThemeProvider (at src/index.js:45)
        in Router (at src/index.js:44)
        in Provider (at src/index.js:43)
    index.js:1446
...

but we do not know why it is occuring.

## Expected Behavior
The error/warning should never occur (assuming we are using notistack correctly).

## Steps to Reproduce
I can take the time to create a codesandbox if need be.  But first, I am just wondering if anybody else has run into this issue.  Is this a known issue?  It seems like a simple issue where the `message` prop is not receiving a string, or something similar.

And yet I have not been able to pinpoint where the message gets passed in.  We are following the [redux usage example](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/redux-example) design pattern.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.5  |
| React        |  16.8.6   |
|  Redux    |  4.0.1    |
| Browser      |   Firefox 70.0.1 (64-bit)      |

**Comment by MareoRaft** [comment]
Indeed, the issue was that the `message` prop wasn't a string.  By passing in a string to `message`, the problem was fixed.

Here is the relevant code:

    const enqueueSnackbar = (notification) => {
      const key = notification.options && notification.options.key;
      return {
        type: GENERIC.ENQUEUE_SNACKBAR,
        notification: {
          // below must be a string
          message: 'whatever ultimately gets passed in here',
          key: key || new Date().getTime() + Math.random(),
        },
      };
    };

**Comment by iamhosseindhv** [comment]
That's right @MareoRaft message should be a string or React.Node
