### ISSUE TITLE
Message in custom snackbar

### ISSUE THREAD

**Issue by ly-vo** [iamhosseindhv/notistack#198]
Is there a reason, why message is not accessible in custom snackbar?

**Comment by iamhosseindhv** [comment]
I'm not sure if I follow your question

**Comment by ly-vo** [comment]
Sorry, i`ll try to explain.
Is there a way to receive message, in custom snackbar?

Now it can receive only key:
`    content: (key) => (
        <MyCustomChildren id={key} />
    ),
`
and i need smth like this:
`
    content: (key, messsage) => (
        <MyCustomChildren id={key} message={message} />
    ),
`

**Comment by iamhosseindhv** [comment]
I see how this can be useful. I'll plan on adding this feature . ❤️
