### ISSUE TITLE
Notistack outside of React Components

### ISSUE THREAD

**Issue by najisawas** [iamhosseindhv/notistack#200]
How do we feel about expanding Notistack to be used outside of react components?

For example, I'd like to write a helper function that can be embedded in to an API object where anytime I make a GET request, if there are any errors present in the response, it pops up as a notification.

I understand that Notistack is built using react context but I'm thinking this could be an additional type of import for the library that doesn't rely on using react components, and can be called from anywhere using something like `Notify.error(...)` etc. The idea comes from my previous use of `react-s-alert` (https://github.com/juliancwirko/react-s-alert) which is slightly buggy when it comes to displaying text, and doesn't use material-ui. (The example code is only called within React but we use it regularly in helper functions)

**Comment by iamhosseindhv** [comment]
Thanks for openning the issue @najisawas .

Any discussion regarding this matter goes here:
https://github.com/iamhosseindhv/notistack/issues/30

I'm considering to add this feature, but in the meantime feel free to use one of the solutions provided by the community.
