### ISSUE TITLE
SnackbarItem background style not applied

### ISSUE THREAD

**Issue by madaz** [iamhosseindhv/notistack#202]
The `<SnackbarItem/>` variant background-color is not been applied because the `MuiPaper-root` class is overriding in my application.

This is because of the jss `<style>` tag injection order where the MuiPaper styles are injected after the `<SnackbarItem/> styles

As mentioned here https://stackoverflow.com/questions/49180192/how-to-specify-the-order-in-which-the-style-sheets-appear-in-the-document

More info
https://cssinjs.org/jss-api/?v=v10.0.0#attach-style-sheets-in-a-specific-order

material-ui uses a default negative incremented index counter. https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/makeStyles/indexCounter.js  which is defaults to if no index is passed in https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/makeStyles/makeStyles.js#L197

## Expected Behavior
`<SnackbarItem/>` variants should style with background-color

![image](https://user-images.githubusercontent.com/1139901/70005417-4c349600-15b5-11ea-942b-77a0611be95a.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/1139901/70004788-48a00f80-15b3-11ea-85af-eb0e5805adea.png)

#### Cascading style rules MuiPaper overriding

![image](https://user-images.githubusercontent.com/1139901/70004864-87ce6080-15b3-11ea-9e37-1c65b4ea9012.png)

#### Style tags incorrect order

![image](https://user-images.githubusercontent.com/1139901/70005191-6a4dc680-15b4-11ea-87d6-3d3a566199c8.png)

## Proposal

Enforce notistack styles to come after Mui style tags...or at least provide a way to pass in options in the SnackbarProvider.

As a test, I got it working locally by adding `{ index: 1 }` to the `withStyles` `node_modules\notistack\build\SnackbarItem\SnackbarItem.js`

```javascript
exports.default = (0, _styles.withStyles)(_SnackbarItem3.default, { index: 1 })(SnackbarItem);
```

(or `/src/SnackbarItem/SnackbarItem.js`)
```javascript
export default withStyles(styles, { index: 1 })(SnackbarItem);
```

![image](https://user-images.githubusercontent.com/1139901/70005424-5060b380-15b5-11ea-97df-9f95375c4490.png)

#### snackbaritem styles last

![image](https://user-images.githubusercontent.com/1139901/70005514-aa617900-15b5-11ea-9f07-968d08fff917.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.6  |
| React        |   16.12.0     |
| Browser      |   Chrome      |
| OS     |   Windows 10      |
| @material-ui/core         |  4.7.1  |

**Comment by iamhosseindhv** [comment]
Thanks for reporting this. @madaz 

This has been fixed and will be published in the next version release.

**Comment by kepamuk** [comment]
> Thanks for reporting this. @madaz
> 
> This has been fixed and will be published in the next version release.

still not work in 0.9.7
