### ISSUE TITLE
Can we have an example of how to use notistack in functional component?

### ISSUE THREAD

**Issue by nilamsavani** [iamhosseindhv/notistack#205]
Hi,

I want to do the exact thing as done in [https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/redux-example](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/redux-example) but I am using functional component. 

Can anyone here create an example which has same functionality using the functional component?

**Comment by iamhosseindhv** [comment]
Let me know if this is buggy @nilamsavani :

https://codesandbox.io/s/notistack-redux-example-nj0nu

**Comment by wilsonj806** [comment]
The example looks solid, but I noticed that it doesn't use the `useDispatch` and `useSelector` hooks provided by the latest [React Redux release(v7.1.x)](https://github.com/reduxjs/react-redux/releases/tag/v7.1.0).

If that's not intentional, I can fork and post an updated CodeSandbox because I'm already trying use Notistack with the new React Redux hooks.

**Comment by iamhosseindhv** [comment]
Thanks @wilsonj806. [redux-example](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/redux-example) now uses hooks only.

**Comment by wilsonj806** [comment]
Looks good @iamhosseindhv! Just a small suggestion, but I think it's better to have the FunctionalNotifier store the displayed notifications like the below:

```js
const FunctionalNotifier = () => {
  // React Redux hooks
  const dispatch = useDispatch();
  const notifications = useSelector(state => state.app.notifications);

  // Store the displayed notifications in component state
  const [displayed, setDisplayed] = useState([]);

  const storeDisplayed = id => {
    setDisplayed(prevDisplayed => [...prevDisplayed, id]);
  };

  const removeDisplayed = id => {
    setDisplayed(prevDisplayed => [...prevDisplayed.filter(key => id !== key)]);
  };

  // doMoreStuffBelow()
}
```
