### ISSUE TITLE
notistack overrides default mui theme  settings

### ISSUE THREAD

**Issue by Sajam** [iamhosseindhv/notistack#206]
Hi all,

Thanks for this great library - it's very helpful! :-)

Recently I've noticed that when error snackbar appeared one of my icons (material-ui or mdi icon based on SvgIcon) changed color to red. When snackbar disappeared it reverted to original color.

Seems like notistack somehow overrides default material-ui styles. I was able to track it down and it was enough to remove `https://github.com/iamhosseindhv/notistack/blob/master/src/utils/constants.js#L40` (`root: {}`).

I'm not sure if it affects `notistack` anyhow else thought so I haven't made PR with this change. It would be great if someone who knows the project better can confirm if it's okay.

Thanks,
Daniel

**Comment by iamhosseindhv** [comment]
@Sajam Thanks for opening this issue.

Please make sure SnackbarProvider is a children of MaterialThemeProvider. If the problem persisted, please create a reproduction and I'll look into it. Thanks.

<img width="936" alt="Screenshot 2019-12-21 at 14 33 01" src="https://user-images.githubusercontent.com/26996372/71309371-f65a4d80-23fe-11ea-8f74-0c1cafb30f1b.png">
