### ISSUE TITLE
Notistack messages goes out of bound when it is really long in IE11

### ISSUE THREAD

**Issue by melhoos** [iamhosseindhv/notistack#207]
Hi 

When the message is really long, the text goes out of bound when using IE11. The text does not break as it does in the other browsers, like in Chrome. If the text is longer than the screen with on small devices the text longer than the screen width is lost (cannot be seen) in IE11. Please see the picture.
![image](https://i.ibb.co/4VQHNsx/longmessage.png)

## Expected Behavior

The text should not break.

## Current Behavior

The text should break when text is long or on small screen widths. 

## Steps to Reproduce

The code is available in these two links (it contains the same code). I am not able to open either codesandbox nor stackblitz in IE11.  

Link:
[![Edit upbeat-chatterjee-w5cs2](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-chatterjee-w5cs2?fontsize=14&hidenavigation=1&theme=dark)
https://stackblitz.com/edit/react-mxn4vu

1. Run the code found in either of the two links above.
2. Open the browser in IE11 
3. Click "click me!"-button

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.7 |
| React        | 16.12 |
| Browser      | IE 11.914 |

**Comment by iamhosseindhv** [comment]
I'll merge and publish the fix as soon as there's a PR open for it, closing this issue until then.
