### ISSUE TITLE
set min-width on outer container

### ISSUE THREAD

**Issue by TheLogan** [iamhosseindhv/notistack#208]
I have an issue with the width of my snackbars. most of them are quite short, like this one:
But the blue area blocks for inputs and such underneath it
![image](https://user-images.githubusercontent.com/759433/71174355-43a2b780-2265-11ea-9a56-6f07fe1bc3e7.png)

If I could add a class to the element selected in the next image that would solve it
However adding a classname to root in the classes object results in it being put further down in the nesting than the root (red arrow):
![image](https://user-images.githubusercontent.com/759433/71174277-1eae4480-2265-11ea-8779-e93068f2b26d.png)

Is there a way to do this?

**Comment by iamhosseindhv** [comment]
You can apply your styles to the container using the `classes` property. e.g. `containerAnchorOriginTopCenter`, `containerAnchorOriginBottomCenter`, ...

See https://iamhosseindhv.com/notistack/api#classes for more info.
