### ISSUE TITLE
Incorrect position in tablet mode

### ISSUE THREAD

**Issue by ilhamsa1** [iamhosseindhv/notistack#210]
## Current Behavior

 why when using tablet mode, the alert should be in the middle, but on the left?

![image](https://user-images.githubusercontent.com/33473051/72264120-bb89b500-364c-11ea-94c2-108e0b1ba67d.png)

**Comment by oliviertassinari** [comment]
It's a duplicate of #192. Seems that it wasn't solved.

**Comment by ilhamsa1** [comment]
Ahh sorry, I did not find the right keywords..
thank for response
