### ISSUE TITLE
When does `enqueueSnackbar` return `null`?

### ISSUE THREAD

**Issue by Svish** [iamhosseindhv/notistack#217]
I'm creating a wrapper for `useSnackbar` with some defaults and additions in our project, and since we're using Typescript I want the typings to be correct. And in the notistack typings there's a thing I don't quite understand:

The `enqueueSnackbar` function is typed to return `OptionsObject['key'] | null`, while `closeSnackbar` can only accept `OptionsObject['key']`.

In what sort of cases does `enqueueSnackbar` return `null`? 🤔

```js
export interface WithSnackbarProps {
    enqueueSnackbar: (message: SnackbarMessage, options?: OptionsObject) => OptionsObject['key'] | null;
    closeSnackbar: (key?: OptionsObject['key']) => void;
}
```
https://github.com/iamhosseindhv/notistack/blob/master/src/index.d.ts#L35-L38

I've tried to figure it out from the documentation and looking in the source, but couldn't really find it... 😕

**Comment by iamhosseindhv** [comment]
This is incorrect type in `index.d.ts`.
We used to return `null` when preventDuplicate props was set to `true`.

As mentioned [here](https://github.com/iamhosseindhv/notistack/pull/189#issue-335969658), as of https://github.com/iamhosseindhv/notistack/pull/189 `enqueueSnackbar` no longer return `null`.
