### ISSUE TITLE
Props from enqueueSnackbar are not forwarded to custom snackbar component

### ISSUE THREAD

**Issue by IsenrichO** [iamhosseindhv/notistack#218]
## Summary
+ When using `notistack` with a custom snackbar (via the `content` prop on the `SnackbarProvider`), config props passed to `enqueueSnackbar` are not forwarded. For example, when doing something like
```
enqueueSnackbar('This is my custom snack!', {
  variant: 'error',
  autoHideDuration: 6000,
});
```
the custom snackbar component provided to `SnackbarProvider` does not receive any part of the config object (`variant`, `autoHideDuration`, etc.).

+ Likewise, using the top-level `action` prop on `SnackbarProvider` does not pass along the action to all custom Snackbar instances.

## Expected Behavior
The `options` object passed to `enqueueSnackbar` should be passed to the invocation of the custom Snackbar component.

## Current Behavior
The custom Snackbar component does not receive any part of the `options` object. 

## Steps to Reproduce
Link: https://codesandbox.io/s/elated-browser-0ck73

1. Click the "Trigger Snack" button in the example.
2. Check the console in the CodeSandbox and see how the `action` and `variant` props are `undefined` even though `enqueueSnackbar` was called with those props.

## Context
Notistack is an awesome tool and something I'd like to leverage instead of far more verbose alternatives. I'm just finding certain gaps when it comes to using Notistack with custom snackbar components and trying to help fill those holes.

From a brief look at the code, I would wager a guess that the problem lies in [these few lines](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarItem/SnackbarItem.js#L117-L120) where `snackContent` doesn't seem to pass through props from the Provider.

## Your Environment
| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.7  |
| React        |  v16.12.0       |
| Browser      |  Chrome latest       |

**Comment by iamhosseindhv** [comment]
This is intentional. If you wish to use props that is passed to `SnackbarItem` or material-ui [Snackbar](https://material-ui.com/components/snackbars/#snackbar) component, there is support to customise appearance of snackbars.

`content` prop is intended to display something entirely different, similar to the example we have on the documentation [website](https://iamhosseindhv.com/notistack/demos#custom-snackbar).

If you think this is not reasonable, please give more details regarding what you're trying to achieve.

**Comment by IsenrichO** [comment]
> This is intentional. If you wish to use props that is passed to `SnackbarItem` or material-ui Snackbar component, there is support to customise appearance of snackbars through for example `classes` prop.
>
> `content` prop is intended to display something entirely different, similar to the example we have on the documentation website.

Yes, I don't need just different styling. I'm intentionally using a custom snackbar.

> If you think this is not reasonable, please give more details regarding what you're trying to achieve.

I don't agree with the reasoning because I think it makes the `enqueueSnackbar` api inconsistent. To illustrate by example, we can simply compare how we would dispatch a new snackbar with and without a custom Snackbar.

Without custom snackbar:
```tsx
enqueueSnackbar('This is my normal snackbar', { variant: 'warning' });
```
vs. With custom snackbar
```tsx
// Provider.tsx
<SnackbarProvider
  // Hackily spread `message` param since I have to use it as an object to give custom snackbar access to options
  content={(key, message) => <Snackbar snackKey={key} {...message} />}
/>

// some other component
enqueueSnackbar({
  message: 'Hacky way of getting options to custom snackbar',
  variant: 'warning',
});
```
So while I need custom snackbar, I would still like to be able to leverage the existing `enqueueSnackbar` because my custom snackbar still has variable behavior depending on things like the `variant`. As you can see, I'm having to rely on hacks in order to be able to actually get the `variant` (and other snackbar options) to the custom snackbar at all.

If you're at least open to supporting this, I can try my hand at a PR.

**Comment by pixel-shock** [comment]
👍 here, cause the "custom snackbar item" makes no sense at all without **every** prop passed through the enqueueSnackbar function.

**Comment by iamhosseindhv** [comment]
@IsenrichO sorry I missed your reply. 

Can you think of cases where you need a prop from enqueueSnackbar other than `variant`?

It makes complete sense to pass key, message and variant to custom component. Currently we only pass key and message.

Open to discuss and PR this. @pixel-shock

**Comment by IsenrichO** [comment]
@iamhosseindhv I think @pixel-shock said it best... **every** prop should be passed through. If `enqueueSnackbar` is given an options object, one would expect the entire object to be forwarded to the custom snackbar. 

> Can you think of cases where you need a prop from enqueueSnackbar other than `variant`?

Yes, many of them. We encounter lots of one-off cases that call for something other than the default "Dismiss" `action`, so I'd definitely like to be able to make use of that. Likewise, it'd be nice to have access to the `onClose` callback. And then there are more application-specific things that we pass around like `data-e2e` tags for E2E testing purposes. For this reason, I think it's best not to discriminate and simply always forward the options object to the custom snack; what we choose to do with the forwarded props is our problem then.

If it helps, here is a screenshot illustrating what my custom snackbar looks like for the `error` variant.

<img width="601" alt="Screen Shot 2020-03-09 at 08 31 28" src="https://user-images.githubusercontent.com/11098273/76231291-44067b00-61e2-11ea-838b-b2d2d83dfbf0.png">

**Comment by pixel-shock** [comment]
I think @IsenrichO explained it properly. 👍 
Just think about to use "notisnack" just as a "wrapper" to handle the whole logic besides the content of the snackbar. 
If you want to customize the SnackbarItems completely like custom action callouts for each custom item, not for the whole snackbar. E.g. Undo Action, Redo Action, Dismiss Action etc. 
Or in my case I have kind of a callback for the SnackbarItem which is called on close to delete some stuff out of the MongoDB. The callback is saved into the state of the SnackbarItem and if the user clicks "undo" or "cancel", then the callback is removed from the state and the SnackbarIem will just dismiss without doing anything.

**Comment by pavelspichonak** [comment]
@iamhosseindhv I understand what @pixel-shock and @IsenrichO mean and what they want. Also I understand what you mean saying 

> Can you think of cases where you need a prop from enqueueSnackbar other than variant?

Indeed all you need to pass(and you do not pass now) is **variant**. All other props are handled by  `snackbar` component from material-ui.

If you pass all options down, in this case users need to handle closing snackbar items by themself(now it is done by `snackbar` and maybe `collapse` components).

Could you please pass now **variant**? It looks like it is so small change but so necessary.

**Comment by iamhosseindhv** [comment]
@pavelspichonak I'm working on passing all options including `variant`. You can track the progress here: https://github.com/iamhosseindhv/notistack/issues/242

**Comment by ChristmasWoe** [comment]
I've met the same problem doing my custom notifications and have come up with own solution:
You can use JSON.stringify method(https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) and JSON.parse (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) to create options object and turn it into string, pass this string as message and then parse it in your custom component (or right in index.js).
**In component, where I call notistack**
`let options = {
                type: 'large',
                variant: 'success',
                message: 'Your message has been saved',
                header: 'Drafts',
            }
            this.props.enqueueSnackbar(JSON.stringify(options), {
                variant: 'success',
            });`
**Index.js**

```
const formOptions = optionsString => {
  if (optionsString == undefined) return {};
  let options = JSON.parse(optionsString);
  return options
}

ReactDOM.render(
  <SnackbarProvider maxSnack={3}
    content={(key, message) => (
      <MyComponent id={key} options={formOptions(message)} />
    )}

  >
<App />
</SnackbarProvider >

```
then access options directly from props in your component

**Comment by Bdthomson** [comment]
@ChristmasWoe Thanks, we ended up doing just that. While a bit hacky, it gets the job done!

**Comment by fegzycole** [comment]
Hey guys, I tried to do the above and it worked, but the snackbar notification appears twice on every load

**Comment by pavelspichonak** [comment]
@iamhosseindhv excuse me. But I really do not understand you. It is the main feature which a lot of people need - to be able to pass variant prop and custom props to their own custom snackbar component. But I believe that you do not implement it during 1 year or more. But you continue to release new versions of your library. Is it really so hard to implement it? I believe - no. So what is the problem????

I know that I'm not developer of this library but it looks so easy feature so I really can't understand why you can't implement so important and the **most** interesting feature for developers?

Looks like I've never wrote angry messages on github. It is the first one. Necessary library, recommended by material-ui authors, I've changed two project and still can't use it because it does not allow to use custom snackbar component which will get variant property(error, info, success) and maybe custom properties which we pass when open snackbar. It is so strange. So strange. Nothing to add.

**Comment by kadriev-ilyas** [comment]
Hello all,
I've found the next hacky solution for forwarding custom properties into the custom snackbar component via enqueueSnackbar(). Just send the object into enqueueSnackbar's first parameter instead of a simple string.

For example:
```
enqueueSnackbar({ 'Info message', variant: 'info' }, { persist: false });
enqueueSnackbar({ 'Error message', variant: 'error' }, { persist: false });
enqueueSnackbar({ 'Success message', variant: 'success' }, { persist: false });
```

And write your custom snackbar like this:
```
<SnackbarProvider
      anchorOrigin={{
        vertical: 'bottom',
        horizontal: 'center',
      }}
      content={(key, message) => (
        <MuiAlert key={key} severity={message.variant}>
          {message.message}
        </MuiAlert>
      )}
    >
      {children}
</SnackbarProvider>
```

It is not the ideal solution, but it works.

**Comment by ErfanSeidipoor** [comment]
This is my solution, using custom Hook 


```
import { useSnackbar } from 'notistack';

const useCustomSnackbar = ()=>{
    const { enqueueSnackbar_, ...others } = useSnackbar();

    const enqueueSnackbar = (message, options)=>{
        return enqueueSnackbar_(
            { message,...options },
            options
        )
    }
    return {enqueueSnackbar, ...others }
}
```


```
const { enqueueSnackbar } = useCustomSnackbar()

const ShowSnackbar = ()=>
  <button
         onClick={()=>enqueueSnackbar('Great!.', {variant:"success"})}
  >
          enqueueSnackbar
   </button>
```


```
import { SnackbarProvider } from 'notistack';
import SnackMessage from "./SnackMessage";

const Provider = ({
    children,
})=> {
    const classes = useStyles();

    return (
        <SnackbarProvider
            content={ (key, message ) => {
                return (
                    <SnackMessage
                        id={key}
                        message={message.message}
                        {...message.options}
                    />
                )
            }}
        >
            {children}
        </SnackbarProvider>
    )
}

```

**Comment by Abolfazl2647** [comment]
[i create a PR for this issue.](https://github.com/iamhosseindhv/notistack/pull/464)

**Comment by gokhantaskan** [comment]
I took a look at the source code and found another solution:

```tsx
// Notification.tsx
import { Close } from "@mui/icons-material";
import IconButton from "@mui/material/IconButton/IconButton";
import MuiSnackbarContent from "@mui/material/SnackbarContent";
import { SnackbarContent, useSnackbar } from "notistack";
import { forwardRef, useCallback } from "react";
import tw from "twin.macro";

const Notification = forwardRef((props: any, ref) => {
  const { closeSnackbar } = useSnackbar();

  const handleDismiss = useCallback(() => {
    closeSnackbar(props.id);
  }, [props.id, closeSnackbar]);

  const Action = (
    <IconButton
      color="error"
      size="small"
      onClick={handleDismiss}
    >
      <Close />
    </IconButton>
  );

  return (
    <SnackbarContent ref={ref as any}>
      <MuiSnackbarContent
        message={props.message}
        action={Action}
        variant={props.variant}
        sx={{
          ...tw`bg-black dark:(bg-white text-black)`,
        }}
      />
    </SnackbarContent>
  );
});

Notification.displayName = "Notification";
export default Notification;

// main.tsx
...
<SnackbarProvider
  Components={{
    default: Notification,
    error: Notification,
    info: Notification,
    success: Notification,
    warning: Notification,
  }}
>
...
```
Put `any` for the types here because I couldn't find a proper `SnackbarProps` matching with the data. And for the ref, I just skipped it.

Still needs some improvements, but working. Under the `SnackbarContent`, you can set your own component and do whatever you want.

There should be a better solution but I just came up with this.
