### ISSUE TITLE
Children can't be passed in EnqueueSnackbar options

### ISSUE THREAD

**Issue by nijk** [iamhosseindhv/notistack#22]
## Expected Behavior
The [documentation here](https://iamhosseindhv.com/notistack#customizing-snackbars-individually) suggests that it should be possible to use any of the ReactMui Snackbar props. So I would expect this:

```
messages.forEach(({ message }) => this.props.enqueueSnackbar(message, { children: 'Foo' }));
```

To result in each message containing the text 'Foo'.

## Current Behavior
I see the `message` instead of 'Foo'

## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.3.7  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by nijk** [comment]
^ PR here

**Comment by iamhosseindhv** [comment]
PR will be merged in the next version of notistack.
