### ISSUE TITLE
Sometimes autoHideDuration property doesn't work

### ISSUE THREAD

**Issue by VCuzmin** [iamhosseindhv/notistack#222]
Sometimes autoHideDuration property doesn't work

_**this.props.enqueueSnackbar(message, {
    variant: 'warning',
    autoHideDuration: 3000,
    action,
});**_

## Expected Behavior
  The stack should be hidden after 3 seconds

## Current Behavior
  The stack is hidden after >3 seconds

**Comment by davwheat** [comment]
https://iamhosseindhv.com/notistack/api

```
The number of milliseconds to wait before automatically calling the `onClose` function. `onClose` should then set the state of the `open` prop to hide the Snackbar. This behavior is disabled by default with the `null` value.
```

It doesn't automatically close the snackbar. It automatically calls the `onClose` function declared via props.

**Comment by VCuzmin** [comment]
Actually I have an onClose method.  But my problem is that onClose function is not called after that 3 seconds.

**Comment by iamhosseindhv** [comment]
> The number of milliseconds to wait before automatically calling the onClose function. onClose should then set the state of the open prop to hide the Snackbar. This behavior is disabled by default with the null value.

This issue slipped through somehow. Sorry for the tardy reply.

Thanks @davwheat. That did not reflect what actually happens. api reference is now updated.

@VCuzmin Without a reproduction example I'm unable to assist.
