### ISSUE TITLE
[HELP] : Close snacker programmatically. 

### ISSUE THREAD

**Issue by pratikguru** [iamhosseindhv/notistack#224]
I've been trying to close the snacker programmatically and the examples on the doc was a bit hard to comprehend. 

Could you please put an example of the callback method and how this can be used? 

Maybe a simple boiler plate code. I've used my own custom made notification component and adding the action doesn't show up on the component. Is there a callback to close the notification from within the component itself?

**Comment by iamhosseindhv** [comment]
I’m bot sure if I follow the question. Would you be able to provide some code of what you’re trying to achieve?

**Comment by pratikguru** [comment]
So I have a custom notification bar through which I want to be able to close programmatically. 

```
 this.props.enqueueSnackbar("", {
      anchorOrigin: {
        vertical: "top",
        horizontal: "left"
      },
      children: key => (
        <InformationCard
          action={key => this.props.closeSnackbar(key)}
        />
      ),
    });
```


The component `informationCard` has a button placed which calls the prop action, which is linked to `this.props.closeSnackBar(key)`. This does not seem to work? Am I missing something here?

**Comment by iamhosseindhv** [comment]
action callback that you've passed is implemented in notistack, and therefore can be used in the second parameter like the following:
```javascript
this.props.enqueueSnackbar("my message", {
     action={key => (
               <button onClick={() =>  this.props.closeSnackbar(key)}>my button</button>
     )}
});
```


But here's an example of what you're trying to achieve:
https://codesandbox.io/s/optimistic-edison-hih0o
```javascript
import { useSnackbar } from "notistack";

const InformationCard = ({ snackKey }) => {
  const { closeSnackbar } = useSnackbar();
  return (
    <div style={{ backgroundColor: "red" }}>
      <Button onClick={() => closeSnackbar(snackKey)}>custom content</Button>
    </div>
  );
};

this.props.enqueueSnackbar("", {
      children: key => <InformationCard snackKey={key} />
});
```
