### ISSUE TITLE
enqueueSnackbar options doesn't inherit props from SnackbarProvider

### ISSUE THREAD

**Issue by Druux** [iamhosseindhv/notistack#229]
As stated in the [docs](https://iamhosseindhv.com/notistack/api#enqueuesnackbar-options), it should be possible to set all the props of `SnackbarProvider` in the `enqueueSnackbar` options, right?

> ...plus all other props than can be passed as both SnackbarProvider props or enqueueSnackbar options.

If I am trying to do something like this

```
enqueueSnackbar(
        'Message',
        {
               hideIconVariant: true,
               persist: true,
               variant: 'warning'
          }
)
```
 I am receiving an error which states that `React does not recognize the 'hideIconVariant' prop on a DOM element`.

Am I misunderstanding something?

**Comment by Druux** [comment]
Seems like it is intended to not using the prop of each other. Solved this by using a custom content.

**Comment by iamhosseindhv** [comment]
Reopening to make sure I investigate this. You shouldn’t need to pass a custom content for such a small customisation.

**Comment by Druux** [comment]
Yeah sure, that would be great. I've just looked up your implementation and it should be very easy to accomplish. In a first step, it would probably help others, if we could make the documentation a bit more clear regarding the statement:

> ...plus all other props than can be passed as both SnackbarProvider props or enqueueSnackbar options.

In the first place I thought that it would be possible to use the props of `SnackbarProvider` and `enqueueSnackbar` in any of each other. But after I've experienced the issues I've taken a look on the implementation and came to this conclusio.
Please just take this as a suggestion.

**Comment by iamhosseindhv** [comment]
@Druux `hideIconVariant` is can only be passed to `SnackbarProvider`. So it'd make sense to get the warning: _React does not recognize the 'hideIconVariant' prop on a DOM element_.

The option for hiding/showing variant icon for an individual snackbar is not supported. the reason being material-ui design specification discourages inconsistency.

Also thanks for the suggestion regarding [api](https://iamhosseindhv.com/notistack/api) reference, I'll try to make it more clear.
