### ISSUE TITLE
TypeError when SnackbarProvider is a child of ThemeProvider

### ISSUE THREAD

**Issue by hutber** [iamhosseindhv/notistack#230]
When I try to use the `SnackbarProvider` inside the `ThemeProvider` it produces the following error:

`TypeError: Cannot read property 'type' of undefined`

The error does not occur if SnackBar is the parent of the ThemeProvider. However this causes my styles to be overritten by I assume notistack. I can see the inline `<style>` that are added and then removed.

## Expected Behavior
To be able to wrap the SnackBar inside Theme and render the page correctly.

## Steps to Reproduce

Wrap `SnackbarProvider` inside a `ThemeProvider`

Link:
https://codesandbox.io/s/infallible-banzai-imsv3

## Context
To be able to load the page without errors or without loading a seperate template.

| Tech            | Version |
|-----------------|---------|
| Notistack | 0.9.8  |
| React        |  16.12.0       |
| Browser      |  Chrome Latest       |
| MUI-COre         | 4.8.3        |

## WIth popup when `SnackbarProvider` is the parent of `ThemeProvider`
![image](https://user-images.githubusercontent.com/1344898/75441891-6385e400-5956-11ea-9cd1-2f830c06852c.png)

## Without popup 
![image](https://user-images.githubusercontent.com/1344898/75441921-6c76b580-5956-11ea-882f-13f49dde7676.png)

**Comment by hutber** [comment]
Interestingly, as seen in the example. If you remove the `background` style everything will function as expected.

I hope this helps somewhat for you guys in the future.

**Comment by jreker** [comment]
I have the same problem. Is there a way to fix this without removing the background style?

**Comment by crrmacarse** [comment]
I'm having this error too in typescript.

![image](https://user-images.githubusercontent.com/39759024/79557250-d4cf5100-80d4-11ea-99f5-c29f77b7e9a0.png)

My temporary fix:
```
<ThemeProvider theme={ThemeConfig(prefersDarkMode)}>
      {/*
        // @ts-ignore */}
      <SnackbarProvider hideIconVariant preventDuplicate>
       ....
      </SnackbarProvider />
</ThemeProvider/>
```

**Comment by iamhosseindhv** [comment]
@crrmacarse can you try with the new version (`v0.9.10`)?

**Comment by crrmacarse** [comment]
> @crrmacarse can you try with the new version (`v0.9.10`)?

@iamhosseindhv The unexpected style overrides is fixed. The typescript error still persist though

**Comment by davwheat** [comment]
@iamhosseindhv 

This is still an issue!

I've overridden my `theme.palette.type` to 'dark', and have also changed the value of `theme.palette.background` as can be seen in [my repo](https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/blob/2a40a88be378b5f3c048ed95f3f7be0fe27d4211/src/data/Theme.js).

When I try to show a snackbar, I get this error:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at decomposeColor (colorManipulator.js:119)
    at getLuminance (colorManipulator.js:194)
    at emphasize (colorManipulator.js:215)
    at styles (SnackbarItem.tsx:16)
    at Object.create (getStylesCreator.js:19)
    at attach (makeStyles.js:94)
    at makeStyles.js:236
    at useSynchronousEffect (makeStyles.js:188)
    at useStyles (makeStyles.js:228)
    at WithStyles (withStyles.js:55)
````

**Comment by gurjit03** [comment]
@davwheat Try removing the background from theme and then use it. It should work then

**Comment by davwheat** [comment]
@gurjit03 Yes, but I shouldn't have to do that.

**Comment by gurjit03** [comment]
@davwheat Not sure myself man, just found that this works atleast. Maybe if you have time try digging deeper into it.
