### ISSUE TITLE
How to change z-index?

### ISSUE THREAD

**Issue by devhyunjae** [iamhosseindhv/notistack#231]
<img width="1329" alt="Screen Shot 2020-02-28 at 9 31 59 PM" src="https://user-images.githubusercontent.com/12890257/75541356-e780be80-5a71-11ea-9d02-902a2305d1a2.png">

Hello,

Want to change the z-index here.
If i use fix it like this
```
const useStyles: any = makeStyles(() => ({
  root: {
    whiteSpace: 'pre-line',
    zIndex: 2000,
  },
  success: {
    backgroundColor: muiTheme.palette.common.green400,
    color: muiTheme.palette.common.black,
  },
}));

<SnackbarProvider
          classes={ {
            root: classes.root,
            variantSuccess: classes.success,
          } }
        >
```

Doesnt work. It only changes the child component

Any tip?

Thanks

**Comment by iamhosseindhv** [comment]
I'm afraid without a reproduction I'm unable to help.
Also what would you like to achieve by overriding zIndex?

**Comment by devhyunjae** [comment]
@iamhosseindhv Using MUI's Dialog and FAB and notistack all together. So z-index war happens in here. I just used original mui's snackbar and fixed the z index there

**Comment by iamhosseindhv** [comment]
@devhyunjae I’m pretty sure you can override zIndex through notistack. But again, without a reproduction I’m unable to help. You just have to make sure you’re passing the styles to the right element.

**Comment by dgreuel** [comment]
@devhyunjae @iamhosseindhv I had a similar problem and solved it by defining a custom z-index on a class (`z-alert`) and passing it in like this:

```
<SnackbarProvider
         classes={{
            variantSuccess: "alert success",
            variantError: "alert error",
            variantInfo: "alert info",
            variantWarning: "alert warning",
            containerAnchorOriginTopCenter: "z-alert"
         }}
      />
```
The issue is that although "root" sounds like it would do the job, you actually need to apply the class to the container (per anchor origin).

**Comment by mattdemichele-pearson** [comment]
In case anyone comes across this - the above solution didn't seem to work for me. 

However, after [looking at the source code](https://github.com/iamhosseindhv/notistack/blob/8c6d6bf599b5af1599a1849d7f32f59b451cec77/src/SnackbarContainer.tsx#L15), the z-index is being set via the theme - specifically `theme.zIndex.snackbar`. Just make sure that your `SnackbarProvider` is inside of your `ThemeProvider`, and then you can set it to whatever you want.

**Comment by vtlnkhn** [comment]
> In case anyone comes across this - the above solution didn't seem to work for me.
> 
> However, after [looking at the source code](https://github.com/iamhosseindhv/notistack/blob/8c6d6bf599b5af1599a1849d7f32f59b451cec77/src/SnackbarContainer.tsx#L15), the z-index is being set via the theme - specifically `theme.zIndex.snackbar`. Just make sure that your `SnackbarProvider` is inside of your `ThemeProvider`, and then you can set it to whatever you want.

you made my day bro)

**Comment by blushingpenguin** [comment]
worth noting that theme.zIndex.snackbar doesn't work in more recent versions -- it's hard coded to 1400. adding:

```css
.notistack-SnackbarContainer.z-alert {
  z-index: 10000;
}
```
and

```jsx
<SnackbarProvider classes={{containerRoot: "z-alert"}}>
```

did the job for me.

**Comment by devth** [comment]
Tried setting this in the mui theme but it doesn't seem to take effect.

**Comment by connor11528** [comment]
updated you can add a style prop to the provider now:

```ts
                  <SnackbarProvider
                    style={{ zIndex: 999999 }}
                    ...
```
