### ISSUE TITLE
Snackbar is not at the center of the window when narrowing width.

### ISSUE THREAD

**Issue by tomohiro-iwana** [iamhosseindhv/notistack#232]
## Expected Behavior
Snackbar is at the center of the window at all width.

```
anchorOrigin={{
    vertical: 'top',
    horizontal: 'center',
}}
```

## Current Behavior
Snackbar is not at the center of the window but leaning to the left when narrowing width.

```
anchorOrigin={{
    vertical: 'top',
    horizontal: 'center',
}}
```

https://iamhosseindhv.com/notistack/demos

### min-width 960px
![image](https://user-images.githubusercontent.com/32325795/76190542-95355f80-6220-11ea-8c90-8bb714c7328d.png)

### min-width 600px max-witdh 960px
![image](https://user-images.githubusercontent.com/32325795/76190576-a41c1200-6220-11ea-919e-1d7b484d5b90.png)

## max-width 600px
![image](https://user-images.githubusercontent.com/32325795/76190631-ca41b200-6220-11ea-80bd-1d0b415b89fb.png)

## Environment
Also, reproduced in my local application.
| Tech         | Version |
|--------------|---------|
| notistack | v0.9.9  |
| React        | v16.12.0 |
| Browser      | Chrome |

**Comment by iamhosseindhv** [comment]
@tomohiro-iwana Thanks for opening the issue. This is fixed and will be released in the next version.

**Comment by tomohiro-iwana** [comment]
Thank you so much!

**Comment by RooyeKhat** [comment]
Hi

In which version is this problem solved?

Thanks
