### ISSUE TITLE
Wrong prop-type for domRoot in a browser environment

### ISSUE THREAD

**Issue by davidbonnet** [iamhosseindhv/notistack#235]
## Expected Behavior
The prop-type for prop `domRoot` correctly validates a DOM element when run in a browser environment.

## Current Behavior
The prop-type for prop `domRoot` does not recognize a DOM element when run in a browser environment.

## Steps to Reproduce
Run this example: https://iamhosseindhv.com/notistack/demos#react-portal

## Context

The source code is self-explanatory: it declares `Element` while referencing it, which is impossible with `const` in ES6, while it returns `undefined` because of hoisting when transpiled down to ES5 by replacing `const` with `var`: https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarProvider.js#L302

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.9  |

**Comment by iamhosseindhv** [comment]
notistack will be pretty soon be in typescript and therefore prop-types will be removed from the source code.

**Comment by iamhosseindhv** [comment]
Prop-type have not been removed from the codebase.
