### ISSUE TITLE
ClassName for variantDefault?

### ISSUE THREAD

**Issue by Svish** [iamhosseindhv/notistack#237]
Classes for styling currently include `variantSuccess`, `variantError`, `variantInfo` and `variantWarning`. Would be helpful with a `variantDefault` as well? Maybe?

**Comment by iamhosseindhv** [comment]
currently you can use `className` prop to do so. `className`. Let me know if you feel the need for it to be called `variantDefault`.

**Comment by haofiltered** [comment]
> currently you can use `className` prop to do so. `className`. Let me know if you feel the need for it to be called `variantDefault`.

@iamhosseindhv 
Hi there, the `variant` props stopped working after using `className` on the provider file to override the default css. 
For example, if I use the `className` to override the background color to `grey`, then `{variant: 'success'}` will be `grey` as well, which I am expecting it to `green`.

I think it would be great if you can add a `variantDefault` for css override.

**Comment by dalborgo** [comment]
I confirm the difficult to obtain the desired effect without overriding the other variants.
