### ISSUE TITLE
Snackbar  with 'horizontal: center' property is not being positioned in the center on tablet and mobile devices (under 960px)

### ISSUE THREAD

**Issue by JuanmaMenendez** [iamhosseindhv/notistack#239]
Snackbar  with **'horizontal: center'** property is not being positioned in the center on tablet and mobile devices (under 960px)

The reason for this behavior is the code to center the Snackbar is inside the Media Query:

```
@media (min-width: 960px) {
.jss612 {
    left: 50%;
    transform: translateX(-50%);
}
}
```

What is the reason for this media query? I think it should be removed and keep the centering in any device width

**Comment by JuanmaMenendez** [comment]
**Note**: A workaround could be something like this:


```
const useStyles = makeStyles(() => ({
    snackBarBottomCenterStyles: {
        left: '50% !important',
        transform: 'translateX(-50%)',
        position: 'fixed',
        bottom: '20px',
        top: 'auto',
        width: 'max-content'
    },
}));
```

```
<SnackbarProvider anchorOrigin={{vertical: 'bottom', horizontal: 'center'}}
                  classes={{anchorOriginBottomCenter: classes.snackBarBottomCenterStyles}}>
...
</SnackbarProvider>
```

But honestly, I think it is better to remove the media query

**Comment by iamhosseindhv** [comment]
Duplicate #232

**Comment by RooyeKhat** [comment]
In which version is this problem solved?

**Comment by iamhosseindhv** [comment]
@RooyeKhat  `latest` Let me know if you're having any issues with it.
