### ISSUE TITLE
Test action inside snackbar with Jest + testing-library

### ISSUE THREAD

**Issue by rodrigovallades** [iamhosseindhv/notistack#245]
## Expected Behavior

I need to test the action inside my snackbar has been called using `Jest` + `testing-library`.

## Current Behavior

I can't seem to find the snackbar inside my rendered component to click it.

## Context

Example:

```
enqueueSnackbar('Hey, this is a success', {
  content: (key, message) => (
    <Alert
      data-testid="success-alert"
      onClose={() => closeSnackbar(key)}
      severity="success"
    >
      {message}
    </Alert>
  )
});
```

I need to test if `onClose` inside the `<Alert />` component has been called, but the snackbar element is not rendered inside the component that uses it.

**Comment by lijin820** [comment]
@rodrigovallades @iamhosseindhv Is there any solution for it?
