### ISSUE TITLE
Documentation website unavailable

### ISSUE THREAD

**Issue by adammwood** [iamhosseindhv/notistack#249]
The documentation website is unavailable:

`{"text":"The requested URL was not found on this server.","code":404}`

While this just looks like a hosting issue, would it be possible or easier for the documentation/demos to be within the codebase so they can be ran offline?

**Comment by iamhosseindhv** [comment]
Thanks for reporting the issue @adammwood .

I'll look into your suggestion regarding moving docs to the codebase.
