### ISSUE TITLE
How Delay enter

### ISSUE THREAD

**Issue by burzimaser** [iamhosseindhv/notistack#253]
## Expected Behavior

  I wan't delay the enter of snack but **I can't:**:
```
 const key = this.props.enqueueSnackbar('No connection!', { 
      transitionDuration: {   enter: 225, exit: 195 },
      variant: 'error',
      persist: true,
      delay: 1000,
  }); 
```
or change transitionDuration
```
this.props.enqueueSnackbar('No connection!', { 
      transitionDuration: {   enter: 2000000, exit: 195 },});
[...]
  objByKey.transitionDuration = transitionDuration: {   enter: 225, exit: 195 },});
```
I think it can be very useful.
Thanks.

**Comment by iamhosseindhv** [comment]
Whats stopping you from calling `enqueueSnackbar` in a `setTimeout`?

**Comment by burzimaser** [comment]
But is a persist... I need key for stopit. Now I use `setTimeout` and when stop the notification I check if is a `key setTimeout` or  `key enqueueSnackbar`. But I don't like my solution

**Comment by iamhosseindhv** [comment]
If I understand the problem correctly, you pass your own key:

```js
const key = 'random unique id';

const timeout = setTimeout(() => {
   enqueueSnackbar('delayed message', { key, persist: true })
}, 2000)

// cancel showing snackbar
clearTimeout(timeout)

// close programmatically if it's persistet
closeSnackbar(key)

```

**Comment by burzimaser** [comment]
> 
> 
> If I understand the problem correctly, you pass your own key:
> 
> ```js
> const key = 'random unique id';
> 
> const timeout = setTimeout(() => {
>    enqueueSnackbar('delayed message', { key, persist: true })
> }, 2000)
> 
> // cancel showing snackbar
> clearTimeout(timeout)
> 
> // close programmatically if it's persistet
> closeSnackbar(key)
> ```

This was my solution with
 ```js
notifyNoConnection() {
var key = setTimeout(() => {
      keySnackbar = this.props.enqueueSnackbar("No connection!", {
        //key,
        variant: "error",
        persist: true,
        preventDuplicate: true
      });
      this.setState({
        connection: keySnackbar 
      });
    }, 2000);
    this.setState({
      connection: key
    });
}
 notifyOnline() {
    Number.isInteger(this.state.connection) ? clearTimeout(this.state.connection) : this.closeNotify(this.state.connection);
    this.setState({
      connection: '',
    });
  }
 ```
example with two botton
https://codesandbox.io/s/cranky-water-e2qcc?fontsize=14&hidenavigation=1&theme=dark
