### ISSUE TITLE
Incapsulate useSnackbar logic

### ISSUE THREAD

**Issue by AlexanderVishnevsky** [iamhosseindhv/notistack#254]
## General information

Hi there. When I try to use useSnackbar hook I faced with problem that I shoud call it on one level according to onClick action. But is it possible to incapsulate useSnackbar inside function and call it with onClick action?

## Current Behavior
```
import { useSnackbar } from 'notistack';

const MyButton = () => {
    const { enqueueSnackbar, closeSnackbar } = useSnackbar();

    const handleClick = () => {
        enqueueSnackbar('I love hooks');
    };

    return (
        <Button onClick={handleClick}>Show snackbar</Button>
    );
}
```
## Expected Behavior
```
import { useSnackbar } from 'notistack';

const showSnackbar = (message: string) => {
    const { enqueueSnackbar, closeSnackbar } = useSnackbar();
    const handleClick = () => {
        enqueueSnackbar(message);
    };
    return handleClick;
}

const MyButton = () => {
    return (
        <Button onClick={showSnackbar('I love hooks')}>Show snackbar</Button>
    );
}
```

| Tech         | Version |
|--------------|---------|
| Notistack | lateest  |
| React        | latest        |
| Browser      |   chrome      |

**Comment by iamhosseindhv** [comment]
Thanks for opening an issue. 

That’s against react rules. Hooks must be called inside an function component and not callbacks. so no change on notistack side of the things could support what you want.
