### ISSUE TITLE
Mention the useSnackbar hook in README

### ISSUE THREAD

**Issue by tuukka** [iamhosseindhv/notistack#255]
I would have expected to learn about the `useSnackbar` hook in the README file and other documentation.

**Comment by hauptrolle** [comment]
@tuukka You can find it on the `real` documentation page: https://iamhosseindhv.com/notistack

But I agree, a mention in the Readme would be nice. Should I create a pull request for this?

**Comment by tuukka** [comment]
@hauptrolle Good catch! I read the README, the API Reference and the demos, but somehow I managed to miss that documentation page.

So +1 for a PR from me, and the API Reference and demo sections of the documentation would benefit from the addition as well, but the source for them is not public?

**Comment by hauptrolle** [comment]
@tuukka Cool, I will try to update the readme today 👍 

Unfortunately I can't find the source for the documentation website anywhere. Maybe @iamhosseindhv can help here?

**Comment by iamhosseindhv** [comment]
Thanks @tuukka @hauptrolle .

I agree having this in readme as well a docs website is useful. Unfortunately docs are part of personal website codebase which is private. I'll have to figure out an easy way for them to be public and a part of notistack repo.
