### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by DatStorm** [iamhosseindhv/notistack#257]
Try to use notistack in functional component.

## Expected Behavior
Should now throw a warning.

## Current Behavior
React.strictmode creates warning

## Steps to Reproduce
```
import React from 'react';
import { Button } from '@material-ui/core';
import { withSnackbar } from 'notistack';

const Home = (props) => {
	const handleClick = () => {
		props.enqueueSnackbar('Successfully fetched the data.');
	};

	const classes = useStyles();
	return (
		<div>
			<Button onClick={handleClick}>Test</Button>
		</div>
	);
};

export default withSnackbar(Home);

```
Versions:

```
"react": "^16.13.1",
"react-dom": "^16.13.1",
notistack": "^0.9.11",
"pondjs": "^0.9.0",
```
## to me
Let me know if I need to provide more info.

**Comment by stevenkitter** [comment]
the same question

**Comment by JoaoHenriqueBarbosa** [comment]
Same here

**Comment by ihormaslov** [comment]
Same here

**Comment by iamhosseindhv** [comment]
Seems to be working here: https://codesandbox.io/s/delicate-hill-p25hr

Unfortunately without a reproduction example I'm unable to help.

**Comment by DatStorm** [comment]
I can reproduce it here in your example: https://codesandbox.io/s/eager-haze-fkn0w?file=/index.js

otherwise chagne index.jsx render to:

```
ReactDOM.render(
  <React.StrictMode>
    <SnackbarProvider maxSnack={3}>
      <App />
    </SnackbarProvider>
  </React.StrictMode>,
  document.getElementById("root")
);
```

**Comment by iamhosseindhv** [comment]
I see the warning now. If anything this is an issue with `@material-ui/core` or `react-transition-group`.

Many thanks.

**Comment by davehowson** [comment]
Is there any solution to this besides disabling Strict Mode?

**Comment by heybenchen** [comment]
For anyone using MaterialUI, I got around this by wrapping the ThemeProvider around SnackbarProvider:

```jsx
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <SnackbarProvider maxSnack={3}>
        <App />
      </SnackbarProvider>
    </ThemeProvider>
  </React.StrictMode>,
```

**Comment by ujnimz** [comment]
I am using MaterialUI, The warning is still there after wrapping the ThemeProvider around SnackbarProvider. This is also advised on [official documentation](https://github.com/iamhosseindhv/notistack#how-to-use). 

_Note: If you're using material-ui ThemeProvider, make sure SnackbarProvider is a child of it._

**Comment by manoharreddyporeddy** [comment]
A solution is here - https://stackoverflow.com/a/66290597/984471

**Comment by DrNguyen2525** [comment]
This is an issue of MaterialUI library, and there's a [temporary solution](https://github.com/mui-org/material-ui/issues/13394#issuecomment-815452717) here before the new MaterialUI v5 is officially released.
