### ISSUE TITLE
0.3.8 Uncaught error

### ISSUE THREAD

**Issue by nowaalex** [iamhosseindhv/notistack#26]
0.3.8 throws error: `react-dom.development.js:55 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
`
after enqueueSnackbar call

**Comment by iamhosseindhv** [comment]
By demo build you mean notistack redux example [here](https://codesandbox.io/s/21o1q3p29y?module=%2Fsrc%2FApp.js)?

**Comment by nowaalex** [comment]
[All examples here](https://iamhosseindhv.com/notistack)

**Comment by iamhosseindhv** [comment]
Thanks for reporting this. demo website is now working (reverted to use `v0.3.7`).

Problem with `v0.3.8` will be fixed asap.

**Comment by iamhosseindhv** [comment]
Fix has been published. Demo website is using the latest version.
