### ISSUE TITLE
autoHideDuration option doesn't work

### ISSUE THREAD

**Issue by lukawski** [iamhosseindhv/notistack#267]
## Expected Behavior

According to docs - `Set autoHideDuration to 'undefined' if you don't want snackbars to automatically close ` - snackbar should not be closed automatically when `autoHideDuration` is set to `undefined`. 

## Current Behavior

Snackbar closes automatically after 5000 ms when `autoHideDuration` is set to `undefined`.  [SnackbarProvider.tsx](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarProvider.tsx#L61) - here you can see condition which decides what to set in `snack.autoHideDuration`. It's using `||` operator so when this prop is undefined it'll fallback to `5000`. Perhaps this condition could be changed so it checks for `undefined` explicitly. Or maybe docs needs to be update if it's desired behavior? I know about `persist` option but currently docs are a bit misleading. 

## Steps to Reproduce

Link: https://codesandbox.io/s/serene-mccarthy-olvk4?file=/MessageButtons.js:1261-1276

1. Call `enqueueSnackbar` with `autoHideDuration` set to undefined
```javascript
enqueueSnackbar('Example message', { autoHideDuration: undefined })
```

## Context

I want my snackbar not to be closed automatically but manually. 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.13 |
| React        | 16.3.1  |
| Browser      | Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) |

Thanks for great library, it's really useful and I really enjoy using it!

**Comment by iamhosseindhv** [comment]
Thanks @lukawski .

Docs have been update. You can pass `null` to stop snackbars from getting dismissed automatically.

**Comment by lukawski** [comment]
Thanks a lot.

**Comment by haimengzhang** [comment]
Setting `persist=true` in options doesn't work. The notification still gets dismissed after some durations (10 seconds). Is this a bug?
