### ISSUE TITLE
closeSnackbar does not work shortly after enqueuing it

### ISSUE THREAD

**Issue by Gareon** [iamhosseindhv/notistack#277]
## Expected Behavior
When calling `closeSnackbar` shortly after enqueuing, it should get closed.

## Current Behavior
When closing a snackbar shortly after enqueuing it (0-230ms), it persists and won't get closed.
It seems to work correctly if the entering transition is almost completed, which is round about after 240-250ms.

## Steps to Reproduce
1. Enqueue a keyed snackbar and close it shortly (0-230ms) after that.
   ```js
   enqueueSnackbar("Some message", {
     key: "test",
	 persist: true,
     variant: "default"
   });
   
   window.setTimeout(() => closeSnackbar("test"), 10);
   ```
2. Behold the persisting snackbar, which actually should get closed.

You can reproduce / verify the problem on [codesandbox.io](https://codesandbox.io/s/cool-shape-uu576?file=/MessageButtons.js).

## Context
I'm using a snackbar as a progress report, which for some fast commands should get closed a few milliseconds later.

## Your Environment

| Tech         | Version                        |
|--------------|--------------------------------|
| Notistack    | v0.9.16                        |
| React        | v16.13.1                       |
| Browser      | Google Chrome (v81.0.4044.129) |
| Material-UI  | v4.9.14                        |

**Comment by iamhosseindhv** [comment]
Thanks for reporting this @Gareon.
Fixed in https://github.com/iamhosseindhv/notistack/pull/280 and will be published as v0.9.17
