### ISSUE TITLE
onExited's arguments are different from docs

### ISSUE THREAD

**Issue by actual-size** [iamhosseindhv/notistack#279]
## Expected Behavior
The only documentation that shows the usage of onExited uses it with two arguments as such: 
```
onExited: (event, myKey) => {
    // removen this snackbar from redux store
    dispatch(removeSnackbar(myKey));
    removeDisplayed(myKey);
}
```

This works in the CodeSandbox it's given in, but in the latest version the API is different

## Current Behavior
the arguments appear to actually be `(an element (?!), reason, key)` though reason is undefined under normal circumstances. This is also the cause of #276.

## Steps to Reproduce
Link: As Gareon noted in #276, this behaviour can be found in the redux example if you add a console.log statement
https://codesandbox.io/s/priceless-vaughan-rusvb?fontsize=14&hidenavigation=1&module=%2FNotifier.js&theme=dark

## Context
Old messages in my store weren't being deleted and it was causing logic errors in my application

## Your Environment
The environment doesn't affect this behaviour

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.16  |

**Comment by iamhosseindhv** [comment]
This is bug caused by latest version of material-ui. meaning if you downgrade MUI core it'll start working:
https://github.com/mui-org/material-ui/issues/21091

Alternatively and temporarily, you can access the key as the third argument.

**Comment by iamhosseindhv** [comment]
Dup of #276
