### ISSUE TITLE
how to compose on functional components (without export default)

### ISSUE THREAD

**Issue by TITAN9389** [iamhosseindhv/notistack#28]
I have components which exports multi functions , i tried many ways to compose this on them but non worked , if anyone can help will appreciate that.
here is sample of my code (there are x3 like this one)

`export const login = creds => {
  return async () => {
    const firebase = getFirebase();
    try {
      await firebase
        .auth()
        .signInWithEmailAndPassword(creds.email, creds.password);
      /* props.enqueueSnackbar('Login success', {
        variant: 'success',
      }); */ COMMENT
    } catch (error) {
      /* props.enqueueSnackbar('Login failed', {
        variant: 'error',
      }); */ COMMENT
      console.log(error);
      throw new SubmissionError({
        _error: 'Login failed',
      });
    }
  };
};`

how can make enqueueSnackbar works here ?

**Comment by iamhosseindhv** [comment]
duplicate
