### ISSUE TITLE
Swipeable snackbars on touch enabled devices

### ISSUE THREAD

**Issue by BhargavThakrar** [iamhosseindhv/notistack#281]
Can we have a feature to remove snackbars with the help of swiping gesture on mobile devices specifically?

The browser support for touch events for mobile browsers is relatively broad - https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Browser_compatibility

Also, the implementation seems to be easy and quick, just to have `onTouchMove` event handler, track the movement and close the snackbar with transition effect in the direction of the swipe. The feature can be guarded with `swipeable` flag passed either through `enqueueSnackbar` options or as props to `SnackbarProvider`. But one disclaimer though that this flag could be overridden to false if the device is not touch enabled or browser does not support it.

Is it worth giving a shot?

**Comment by iamhosseindhv** [comment]
This is documented as future features in the CHANGELOG. #138 

Although there're other issues/features with higher priority on my list. All PRs welcome

**Comment by felipearosemena** [comment]
Bump on this. This is a major UX issue to not be able to swipe to dismiss on mobile

**Comment by t1gor** [comment]
Hi, guys. As far as I understand, `swipe-to-dismiss` feature is implemented, but I can't seem to find any mentions of it in the docs or even in the code. Could some one please provide a code sample of where to look & how to configure it?
