### ISSUE TITLE
Provide source code for https://iamhosseindhv.com/notistack/demos

### ISSUE THREAD

**Issue by rofrol** [iamhosseindhv/notistack#286]
## Expected Behavior

When I look at demos at https://iamhosseindhv.com/notistack/demos there should be link to source repository for demos or expandable code snippets.
 
## Current Behavior

No source code

## Your Environment

**Comment by iamhosseindhv** [comment]
Unfortunately I'll be closing this issue after exactly 1 year, since open sourcing the documentation website takes time and not many people have upvoted this issue.
