### ISSUE TITLE
Applying style to the root container

### ISSUE THREAD

**Issue by edoudou** [iamhosseindhv/notistack#289]
## Expected Behavior

When applying style through `classes={{root : {...}}}` to `SnackbarProvider`, the style should apply to the first div of the snackbar. 

## Current Behavior

It apply to the MuiSnackbar-root div : 
![MuiSnackbar-root](https://user-images.githubusercontent.com/4236706/86804951-b5164c00-c077-11ea-81ff-95acfc218ea7.png)

But there are more div above, and it should apply to the makeStyle-root :

![makeStyle-root](https://user-images.githubusercontent.com/4236706/86803975-c9a61480-c076-11ea-9efc-ef8c22cc33bb.png)

Instead, this div stays in the same position and block mouse event behind it, even if the Snackbar is not at this position.

## Steps to Reproduce

Link: https://codesandbox.io/s/friendly-euler-ij7ff?file=/src/AppProvider.js

1. Use the `classes` prop from the SnackbarProvider to move the snackbar.
2. Make snackbar appear.
3. Look at the HTML to see where the root of the snackbar is.

## Context

I am trying to put my Snackbar beneath the header, and still be able to click on my header.
## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.17  |
| React        | v16.12.0 |
| Browser      | any |

**Comment by gregor-dev-443** [comment]
You can apply styles to the snackbar container using `classes={{containerRoot : {...}}}`.

**Comment by StanimirIliev** [comment]
@gregor-dev-443 
> You can apply styles to the snackbar container using `classes={{containerRoot : {...}}}`.

That doesn't work either.

**Comment by iamhosseindhv** [comment]
@StanimirIliev https://codesandbox.io/s/objective-dream-grfqm

**Comment by StanimirIliev** [comment]
@iamhosseindhv Thank you!

**Comment by edoudou** [comment]
It seems to be working as expected, thank you.
