### ISSUE TITLE
how to compose on functional components (without export default)

### ISSUE THREAD

**Issue by TITAN9389** [iamhosseindhv/notistack#29]
I have components which exports multi functions , i tried many ways to compose this on them but non worked , if anyone can help will appreciate that.
here is sample of my code (there are x3 like this one)

```javascript
export const login = creds => {
  return async () => {
    const firebase = getFirebase();
    try {
      await firebase.auth().signInWithEmailAndPassword(creds.email, creds.password);
    } 
catch (error) {
      console.log(error);
      });
    }
  };
};
```

how can make enqueueSnackbar works here ?

**Comment by iamhosseindhv** [comment]
I'm not sure if I followed @TITAN9389, but if you don't have access to `props`, you can return a promise and resolve on successful sign in, and `.then` call `enqueueSnackbar`. 

I'm sure I can help more if you provide a codesandbox example.

**Comment by TITAN9389** [comment]
> I'm not sure if I followed @TITAN9389, but if you don't have access to `props`, you can return a promise and resolve on successful sign in, and `.then` call `enqueueSnackbar`.
> 
> I'm sure I can help more if you provide a codesandbox example.

its a little bit complicated to make a sample on sandbox ,i got your point about returning promise i'll try and see if i'll need further help will tell, thanks.

**Comment by iamhosseindhv** [comment]
I'm closing this but let me know if there was a problem.

```javascript
login = () => (
       new Promise((resolve) => {
            const firebase = getFirebase();
            try {
                await firebase.auth().signInWithEmailAndPassword(creds.email, creds.password);
                resolve()
            } 
            catch (error) {
                console.log(error);
            }
      });
);
```

```javascript
// in your component
login().then(() => this.props.enqueueSnackbar(...))
```
