### ISSUE TITLE
Add delay option

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [iamhosseindhv/notistack#296]
Would it make sense to make some generic solution to issue #253 part of the API? I assume there already exists a map somewhere that does the mapping from keys to notistack instances.

> 
> 
> If I understand the problem correctly, you pass your own key:
> 
> ```js
> const key = 'random unique id';
> 
> const timeout = setTimeout(() => {
>    enqueueSnackbar('delayed message', { key, persist: true })
> }, 2000)
> 
> // cancel showing snackbar
> clearTimeout(timeout)
> 
> // close programmatically if it's persistet
> closeSnackbar(key)
> ```

This was my solution with
 ```js
notifyNoConnection() {
const key = setTimeout(() => {
      const keySnackbar = this.props.enqueueSnackbar("No connection!", {
        //key,
        variant: "error",
        persist: true,
        preventDuplicate: true
      });
      this.setState({
        connection: keySnackbar 
      });
    }, 2000);
    this.setState({
      connection: key
    });
}
 notifyOnline() {
    Number.isInteger(this.state.connection) ? clearTimeout(this.state.connection) : this.closeNotify(this.state.connection);
    this.setState({
      connection: '',
    });
  }
 ```
example with two botton
https://codesandbox.io/s/cranky-water-e2qcc?fontsize=14&hidenavigation=1&theme=dark

_Originally posted by @burzimaser in https://github.com/iamhosseindhv/notistack/issues/253#issuecomment-625688554_

**Comment by iamhosseindhv** [comment]
I personally don't have time to implement this. PR's welcome

**Comment by make-github-pseudonymous-again** [comment]
While I still have not written a PR, I started using the following recipe with some success:

```typescript
const DEBOUNCE_DELAY = 500;

const debounceSnackbar = ({enqueueSnackbar, closeSnackbar}) => {
	let key: SnackbarKey;
	let timeout;
	return (message: string, options: OptionsObject) => {
		clearTimeout(timeout);
		if (key !== undefined) closeSnackbar(key);
		timeout = setTimeout(() => {
			key = enqueueSnackbar(message, options);
		}, DEBOUNCE_DELAY);
	};
};
```

Then I can use it in a component callback as follows

```js
...
const {enqueueSnackbar, closeSnackbar} = useSnackbar();
...
const onClick = async () => {
  const feedback = debounceSnackbar({enqueueSnackbar, closeSnackbar});
  feedback('Pending...', {variant: 'info', persist: true});
  try {
    await doAsyncStuff();
    feedback('Success!', {variant: 'success'});
  }
  catch (error) {
    feedback(`Error: ${error.message}`, {variant: 'error'});
  }
};
...
```

There is still a lot of room for improvement.

**Comment by dwjohnston** [comment]
+1 on this feature. My use case is that I want to have a snackbar show for a file upload progress. But for very small files I don't need to show this snackbar.
