### ISSUE TITLE
anyway to dismiss all opened Snackbar ?

### ISSUE THREAD

**Issue by ahakem** [iamhosseindhv/notistack#298]
Hello,
simply I want to make sure all snakbar are closed when I logout.

I'll not have a key for the opened one.
any way to do that?

**Comment by iamhosseindhv** [comment]
Thanks for opening an issue @ahakem .

Calling `closeSnackbar` with no key will close all the open snackbars, as well as the ones that are about to be displayed (half-way through transition animation)
