### ISSUE TITLE
Example for next.js

### ISSUE THREAD

**Issue by Manikanta-20** [iamhosseindhv/notistack#302]
# Example Request

Provide example for notistack+ material-ui+ next.js?

In my  example ,classnames are conflicting with material ui.....
If toast cames letter are changes from lowercase to uppercase and buttons color changing to pink

**Comment by iamhosseindhv** [comment]
As far as notistack is involved, you need to make sure `SnackbarProvider` is a children of `ThemeProvider`. Rest of configuration can be found in the official example: https://github.com/mui-org/material-ui/tree/master/examples/nextjs

**Comment by Maxim-Mazurok** [comment]
In my case SnackbarProvider is a child of ThemeProvider, however I get `Error: createContext only works in Client Components.` and have to use "use client" directive for notistack to work.

**Comment by libasoles** [comment]
Same with next 13 app router, notistack 3.0.1, these resolutions:

"resolutions": {
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11"
  }

I have to declare the provider client side. Any doc on how to setup notistack for app router?

**Comment by Maxim-Mazurok** [comment]
Another weirdness - I can't put SnackbarProvider into sub-component, it has to be in the `page.tsx` ;(

**Comment by samislam** [comment]
I solved the problem by doing type augmentation, 

I created a file called `notistack.d.ts`:
```ts
import { SnackbarProvider as SnackbarProviderBase } from 'notistack'
import { FC, ReactNode } from 'react'

declare module 'notistack' {
  export function SnackbarProvider(): ReactNode
}
```

**Comment by AbdElRahmanMostafa1** [comment]
You can solve the problem by creating a lib folder at the same level as app in which you add a mui.js file, like so:

```
// lib/mui.ts

"use client";
export * from "@mui/material";
```

And you import it from there (this way, other parts of the page are still Server Components):

```
// app/layout.tsx

import { Button } from "../lib/mui";
export default function Home() {
  return (
    <div>
      <Button variant="contained">Hello World</Button>
    </div>
  );
}
```

**Comment by johnsonsg** [comment]
@AbdElRahmanMostafa1 
 This doesn't make sense? could you explain more in detail if you could!  Thank you.

What seems to be happening is, If you are wrapping the SnackbarProvider around the App, which is my Layout.tsx page, because that page is not a "use client"; it will not produce the snackbar.   It only works when it is a useClient individual page.
