### ISSUE TITLE
enqueueSnackbar throws when called with key === 0

### ISSUE THREAD

**Issue by kt3k** [iamhosseindhv/notistack#304]
When we call `enqueueSnackbar` function with the options `key: 0`, the function call throws. It seems to have started from #271 (v0.9.15).

## Expected Behavior

`enqueueSnackbar()` doesn't throw with `key === 0`

## Current Behavior

`enqueueSnackbar()` throws with `key === 0`

## Steps to Reproduce

The following code throws.

```js
const { enqueueSnackbar } = useSnackbar()

useEffect(() => {
  enqueueSnackbar('hello', { key: 0 })
}, [])
```

Link:

1. https://codesandbox.io/s/nice-bhabha-czg5r?file=/App.js

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.0  |
| React        | v16.9.0        |
| Browser      |  Chrome       |

**Comment by thierrysantos** [comment]
Hello @kt3k, I will open a PR solving it.
