### ISSUE TITLE
How to display message on top of material dialog.

### ISSUE THREAD

**Issue by mukesh-pathak-by** [iamhosseindhv/notistack#307]
Even though i set highest z-index for notification it comes behind the dialog not above it.

Any way to fix this issue

**Comment by redgumnfp** [comment]
Depending on your control position, may be worth considering this:

https://codesandbox.io/s/nice-currying-t9xdn?file=/App.js

Can see various other options for Bottom/Right/Center etc too in the source file:
notistack.cjs.development.js.map

**Comment by iamhosseindhv** [comment]
Full documentation around `classes` keys of container here:
https://iamhosseindhv.com/notistack/api#classes
