### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by naskio** [iamhosseindhv/notistack#308]
I would like to suggest an option where we can specify the max length of the message that will be displayed.

something like that:
```javascript
enqueueSnackbar("this is a long message this is a long message this is a long message this is a long message", {
    variant: 'success',
   max_length: 20,
});
```
should show a snackbar with: message = "his is a long messa..."

**Comment by iamhosseindhv** [comment]
It'd be pointless to just append `...` to the message. If we do this then we also need some code to expand the snackbar so user can see the full message. In this scenario you'll need to rely to implement your own [Custom Snackbar](https://iamhosseindhv.com/notistack/demos#custom-snackbar).
