### ISSUE TITLE
Provide access to parent container

### ISSUE THREAD

**Issue by redgumnfp** [iamhosseindhv/notistack#309]
It's not currently possible to amend the parent container css, for example, amend the z-index or bottom css properties.

## Expected Behavior
I'd expect the Root to be the parent root, allowing manipulation as required, with other properties overridable, or at least a class name that could be used.

In the example below, this would be that the base-point is 70px from the bottom, but I had a previous use to improve the z-index too.

For example:
```
const useStyles = makeStyles(() => ({
  root: {
    bottom: 70,
  },
}));

```
```
<SnackbarProvider classes={classes}>
    {children}
</SnackbarProvider>
```

## Current Behavior
This class is applied to the MuiSnackbar-root, rather than the parent div, so it doesn't affect the overall position at all.

https://codesandbox.io/s/nice-currying-t9xdn?file=/App.js

## Context
In my application, I use the Bottom-Navigation bar from MUI, so I don't want Notistack to interrupt this control.

**Comment by redgumnfp** [comment]
Ah, found the class property after all that....

containerAnchorOriginBottomLeft in my case.

May be worth adding this into your documentation for future reference.

**Comment by iamhosseindhv** [comment]
https://iamhosseindhv.com/notistack/api#classes
