### ISSUE TITLE
Error: enabling checkmark for use-emoji under Custom icon variant

### ISSUE THREAD

**Issue by Jatin-007** [iamhosseindhv/notistack#31]
Enabling the checkmark for "Use Emoji" under custom icon variant throws an error after clicking on one of the snackbars. 

https://iamhosseindhv.com/notistack#custom-icon-variant

## Expected Behavior
    Expected to show a snackbar with custom emoji's for specific variant

## Current Behavior
    Throws an error for on enabling the checkbox before or after clicking the snackbar

## Steps to Reproduce

    Provide a link to a live example (you can use codesandbox.io) and an unambiguous set of steps to reproduce this bug.
    Include code to reproduce, if relevant (which it most likely is).

    This codesandbox.io template _may_ be a good starting point:
    https://codesandbox.io/embed/github/iamhosseindhv/notistack/tree/master/demo

    If YOU DO NOT take time to provide a codesandbox.io reproduction, should the COMMUNITY take time to help you?
-->
Link:
 https://iamhosseindhv.com/notistack#custom-icon-variant

## Your Environment
Tested this issue inside MacOS along with Ubuntu OS environment

![screenshot from 2018-11-28 10 44 24](https://user-images.githubusercontent.com/26683650/49174232-9a57ef00-f2fa-11e8-9a56-4955490a06fa.png)

**Comment by iamhosseindhv** [comment]
Thanks for reporting @Jatin-007. this issue is fixed and it will be published in the next version of notistack. see changelog for more info. 
https://github.com/iamhosseindhv/notistack/issues/27#issuecomment-441508797
