### ISSUE TITLE
Can't override styles 

### ISSUE THREAD

**Issue by SimonAmphora** [iamhosseindhv/notistack#310]
Hi, I'm trying to override the styles as above #215 (comment)

However, I'm facing an issue where my new styles are not taking effect due to the ```!important``` flag in the snackbarItem styles:

```
.SnackbarItem-variantSuccess-380 {
    color: #fff !important;
    background-color: #43a047 !important;
}
```
you can see an example here:
https://codesandbox.io/s/nice-kapitsa-0k7go?file=/SnackbarProvider2.js
The top row of buttons is using standard styles, the second row is using styles with ```!important```

Now I can force them with updating my styles with the ```!important``` flag but I would rather not

**Comment by SimonAmphora** [comment]
seems to be duplicate of https://github.com/iamhosseindhv/notistack/issues/305

**Comment by iamhosseindhv** [comment]
As of `v1.0.9`, you do not need to use !important anymore.
