### ISSUE TITLE
enqueueSnackbar with the same key using maxSnack=1

### ISSUE THREAD

**Issue by aMoniker** [iamhosseindhv/notistack#313]
I don't know if this is an error, or if I'm using things improperly.

Using `maxSnack=1`, I have a button that calls `enqueueSnackbar` with simple arguments (just the message & a key). The key is static.

If the button is clicked before the first Snackbar has disappeared, then it will make that Snackbar immediately disappear, and subsequent clicks will never produce another Snackbar.

However, if I wait until it disappears on its own, then clicking the button again will work.

If I use a different key each time, adding an incrementing counter to it, then I can click the button to my heart's content, and new Snackbars cycle in normally with each click. So, I should do that, or just not use a key at all. But, is this the intended behavior for using a key, or is it a bug? Thanks for taking a look.

## Expected Behavior
Snackbars with the same key can be enqueued any number of times, and enqueuing one before the previous one has finished displaying will simply replace that one.

## Current Behavior
Enqueuing a Snackbar with the same key before the previous one has disappeared will prevent all future Snackbars with that key from displaying.

## Steps to Reproduce
Click the button like a madman: https://codesandbox.io/s/sharp-cohen-zmb6h

**Comment by primal100** [comment]
I'm not exactly sure of the intended behaviour but I have a pull request that gives your expected behaviour: #303 

I've tested it locally with your code and it works.

**Comment by iamhosseindhv** [comment]
Dup #234
