### ISSUE TITLE
New line in messege

### ISSUE THREAD

**Issue by kubalobo** [iamhosseindhv/notistack#32]
Hi,
is that possible to add a new line mark in the notistack messege text?
I tried '\n' and '<br>' in many variants but its always printed as writed. 😢

**Comment by iamhosseindhv** [comment]
Hi @kubalobo, I'm not sure if it's possible. maybe material-ui [issues](https://github.com/mui-org/material-ui/issues) is a better place to ask this. However, you can pass whatever you want as the body of snackbar in options paramters of `enqueueSnackbar`.

```javascript
this.props.enqueueSnackbar('I love snacks', {
    children: (
         <div> my entirely customised snack </div>
    ),
});
```

**Comment by nijk** [comment]
@kubalobo which version of notistack are you using? The children option was fixed in v0.3.9, see issue #22

**Comment by kubalobo** [comment]
Yea, I had 0.3.7. It's working fine after update.
Thanks!

**Comment by dy** [comment]
For these googling the solution:
```js
enqueueSnackbar(msg, {
      variant: 'error',
      style: { whiteSpace: 'pre-line' }
})
```

**Comment by santiagazo** [comment]
To add to @dy's comments - be sure to use `\n` not <br/> as the `<br/>` alwas renders and so far, my testing only shows the `\n` working.

**Comment by bhanu-vegrow** [comment]
> ```js
> style: { whiteSpace: 'pre-line' }
> ```
  enqueueSnackbar(
    "Please wait while we upload the video. Do not refresh the page or \n navigate away from this page to ensure a successful upload.",
    {
      persist: true,
      variant: "info",
      style: { whiteSpace: "pre-line" },
      anchorOrigin: {
        vertical: "top",
        horizontal: "right",
      },
    }
  );
  
  I have to use both \n and style:{whitespace:"pre-line"} for it to work
