### ISSUE TITLE
missing source map files

### ISSUE THREAD

**Issue by kecsolecso** [iamhosseindhv/notistack#322]
node_modules\notistack\dist\notistack.cjs.production.min.js.map references source files like: 
`"sources":["../src/SnackbarContext.ts","../src/utils/constants.ts","../src/SnackbarContent/SnackbarContent.tsx", ....`
these are missing from bundle
In this way, it is hard to debug plus source code analyze tools are blind for this dependency

**Comment by iamhosseindhv** [comment]
This issue didn't get much traction. PRs are welcome though.
