### ISSUE TITLE
Style issue in material ui RTL theme

### ISSUE THREAD

**Issue by iammrali** [iamhosseindhv/notistack#323]
First ty for your library, i want to use it in material ui theme and open it in outside of component [(#30)](https://github.com/iamhosseindhv/notistack/issues/30), but i think it has some style issue with rtl

## Expected Behavior
Open toasts in bottom left side

## Current Behavior
Toast comes from left side but slide to right of screen

## Steps to Reproduce
See this [sandbox](https://codesandbox.io/s/nervous-tesla-idc42?file=/src/App.js)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.1  |
| React        |  v16.13.1  |

**Comment by barghi** [comment]
Same issue here

**Comment by mehrandvm** [comment]
this might not be the best solution but I fixed my problem by putting the `<SnackbarProvider>` outside of the `<ThemeProvider>` or `<StylesProvider>` component like this
`
<SnackbarProvider
      anchorOrigin={{
        vertical: 'bottom',
        horizontal: 'left',
      }}
    >
    <ThemeProvider theme={theme}>
      <StylesProvider jss={jss}>
         <div/>
      </StylesProvider>
      </ThemeProvider>
    </SnackbarProvider>
`

**Comment by iamhosseindhv** [comment]
You probably want to change the direction of `Slide` component:
```diff
enqueueSnackbar('my message', {
    variant: "error",
+   TransitionProps: { direction: "left" }
});
```

**Comment by Iran-110** [comment]
> You probably want to change the direction of `Slide` component:
> 
> ```diff
> enqueueSnackbar('my message', {
>     variant: "error",
> +   TransitionProps: { direction: "left" }
> });
> ```

I have a linter error at `{ direction: "left }`:

     TS2322: Type '{ direction: string; }' is not assignable to type 'TransitionProps'.

I use `"@mui/material": "^5.8.6"`.

**Comment by iamhosseindhv** [comment]
What version of notistack are you on @Iran-110 ? If you provide a minimal reproduction, I might be able to help.
