### ISSUE TITLE
Lack of ability to customize an action class

### ISSUE THREAD

**Issue by newsiberian** [iamhosseindhv/notistack#327]
To accomplish RTL support we need to customize `action` class, but the lib doesn't provide such possibility

## Expected Behavior

We want to see a prop `classes.action` which will be additional class to `action`

## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.1  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
You'll have full control over your snackbar in v2. Downloadable by `npm i notistack@alpha`.
