### ISSUE TITLE
Not able to set custom color for snackbar

### ISSUE THREAD

**Issue by ugolb** [iamhosseindhv/notistack#329]
Hi everyone, I'm trying to set up custom variants for snackbar, trying to do it in the same as it is specified in docs (https://iamhosseindhv.com/notistack/demos#custom-snackbar) but due to some reason it does not change colors to what I'm specifying. 

Using MUI hook withStyles
![image](https://user-images.githubusercontent.com/14921564/99428872-8357a080-2907-11eb-976b-ae2185e76d56.png)

Calling enqueueSnackbar
![image](https://user-images.githubusercontent.com/14921564/99428970-a3875f80-2907-11eb-956e-d31769959c4a.png)

and result:

![image](https://user-images.githubusercontent.com/14921564/99429032-bc901080-2907-11eb-8584-96ef91ab25da.png)

looks like colors which I've passed to SnackbarProvider does have any effect.

Can you please help with this? Is this a bug or I'm doing something wrong?

**Comment by iamhosseindhv** [comment]
I will be updating the documentation to emphasise on this. But you should be able to achieve your customisation by passing `!important` to your styles.

**Comment by ugolb** [comment]
Thanks a lot, it works now.
