### ISSUE TITLE
Sending URL links in messages? 

### ISSUE THREAD

**Issue by gregarican** [iamhosseindhv/notistack#330]
This is actually a question, but I didn't readily see how to flag it as such. This is a great project we will be utilizing for providing chat dialog for our retail customers. One of the features we'd like to implement involves our sales staff sending out clickable URL links to the customer(s) who are in the chat room we've built. For example, if the salesperson sends out a message saying, "Please purchase this item here --> https://www.example.com/purchase?foo123" then anyone viewing the chat room could tap/click the URL that appears in the dialog.

Would I need to create an inherited class from the SnackbarProvider in order to implement this custom functionality?

**Comment by iamhosseindhv** [comment]
You can pass a `React.ReactNode` as `message` to enqueue Snackbar.
Example: https://codesandbox.io/s/cranky-kalam-p554h?file=/MessageButtons.js

```js
const handleClick = () => {
    this.props.enqueueSnackbar( <a href="https://iamhosseindhv.com/notistack">Visit Documentation</a>,  {
        variant: 'info'
    }
};

```

**Comment by gregarican** [comment]
Perfect! Thanks so much for the prompt reply. Works great.
