### ISSUE TITLE
Variant style are using !important

### ISSUE THREAD

**Issue by glaucopater** [iamhosseindhv/notistack#331]
I'm customizing any type of variant: success, error, info. 

Previous code was: 
  variantSuccess: {
      backgroundColor: '#43a047',
      color: '#fff'
    },
    variantError: {
      backgroundColor: '#d32f2f',
      color: '#fff'
    },
    variantInfo: {
      backgroundColor: '#2196f3',
      color: '#fff'
    },
    variantWarning: {
      backgroundColor: '#ff9800',
      color: '#fff'
    },

Now it is:

 variantSuccess: {
            backgroundColor: '#43a047 !important', // green
            color: '#fff !important',
        },
        variantError: {
            backgroundColor: '#d32f2f !important', // dark red
            color: '#fff !important',
        },
        variantInfo: {
            backgroundColor: '#2196f3 !important', // nice blue
            color: '#fff !important',
        },
        variantWarning: {
            backgroundColor: '#ff9800 !important', // amber
            color: '#fff !important',
        },

## Expected Behavior
There should not be any !important inside the variant styles as I want to customize the style of my success, error, snackbars

## Current Behavior
Now the current version is adding !important on each class and in order to customize them:
using other !important is not feasible

## Steps to Reproduce
Upgrade to v1.0.1 version
 
 
| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.1  |

Thanks,
Glauco

**Comment by XabierL** [comment]
Yes @glaucopater is right, it only works using important
![image](https://user-images.githubusercontent.com/44481156/100649306-8b213700-3342-11eb-8900-33416a8ec757.png)

Regards,
Xabier

**Comment by PandarinDev** [comment]
Are there any plans for fixing this? It is unfortunate that `!important` is required for custom theming to work.

**Comment by iamhosseindhv** [comment]
There's not a quick fix for this. Customising variants is done a in different way now. (See https://github.com/iamhosseindhv/notistack/pull/362).
