### ISSUE TITLE
Getting console warnings when using with lastest MaterialUI alpha release.  (^5.0.0-alpha.14)

### ISSUE THREAD

**Issue by nickraphael** [iamhosseindhv/notistack#332]
I'm getting a whole bunch of console warnings when calling notistack with MaterialUI "^5.0.0-alpha.14"

Warning: Unknown event handler property `onEntering`. It will be ignored.
Warning: Unknown event handler property `onExiting`. It will be ignored.

## Expected Behavior
no warnings

## Current Behavior
I'm getting a whole bunch of console warnings when calling notistack with MaterialUI "^5.0.0-alpha.14"

Warning: Unknown event handler property `onEntering`. It will be ignored.
Warning: Unknown event handler property `onExiting`. It will be ignored.

## Steps to Reproduce
use the following dependancies in the demo...

 https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/simple-example?%3Fhidenavigation=1&module=/App.js&file=/package.json:813-1142

"dependencies": {
        "@material-ui/core": "^5.0.0-alpha.14",
        "@emotion/react": "latest",
        "@emotion/core": "^10.0.35",
        "@emotion/styled": "^10.0.27",
        "clsx": "^1.1.0",
        "notistack": "latest",
        "prop-types": "latest",
        "react": "latest",
        "react-dom": "latest"
    }

**Comment by iamhosseindhv** [comment]
Same as https://github.com/iamhosseindhv/notistack/issues/295. Will be fixed soon. PRs welcome

**Comment by iamhosseindhv** [comment]
Please update to `v1.0.2`. Let me know if the issue persists.
