### ISSUE TITLE
Material-UI: The key `container` provided to the classes prop is not implemented in ForwardRef(Collapse).

### ISSUE THREAD

**Issue by nickraphael** [iamhosseindhv/notistack#334]
Getting this error when using 1.0.2 with MaterialUI ^5.0.0-alpha.14.  Can easily reproduce with the official online demo.

## Current Behavior
Material-UI: The key `container` provided to the classes prop is not implemented in ForwardRef(Collapse).

## Steps to Reproduce

https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/redux-example?file=/package.json:276-603

Replace the dependencies with this...

  "dependencies": {
    "@material-ui/core": "^5.0.0-alpha.14",
    "notistack": "^1.0.2",
    "@emotion/react": "latest",
    "@emotion/core": "^10.0.35",
    "@emotion/styled": "^10.0.27",
    "react": "latest",
    "react-dom": "latest",
    "react-redux": "latest",
    "react-scripts": "latest",
    "redux": "latest"
  },

**Comment by iamhosseindhv** [comment]
You can now use `npm i notistack@next` to have a version compatible with MUI `next`.
