### ISSUE TITLE
Why do we need @material/core ?

### ISSUE THREAD

**Issue by gothraven** [iamhosseindhv/notistack#335]
I just installed notistack in a CRA and when i did `yarn start` I have got this error

```
Failed to compile.

./node_modules/notistack/dist/notistack.esm.js
Module not found: Can't resolve '@material-ui/core/ClickAwayListener' in '/--path--/node_modules/notistack/dist'
```
And I started asking myself why do I need @material-ui ? I don't want to use it! and why the docs doesn't even mention this ?!

## Expected Behavior
I expect this to work without me needing to install @material-ui

## Your Environment
| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.2  |
| React        | v17.0.1        |
| Browser      | chrome         |

**Comment by iamhosseindhv** [comment]
I get your point.
There is a **work in progress** to remove MUI dependency: #184 

* API docs mentions notistack is atm an extension of MUI Snackbar: https://iamhosseindhv.com/notistack/demos#material-props (I do agree the mention is not very explicit)
* MUI is listed as `peerDependency` of notistack
https://github.com/iamhosseindhv/notistack/blob/ecee3fe12f88c1431fe435bcb409e11edc252d15/package.json#L26-L29

Until a new version of notistack is released which is independent of MUI, you'll have to have it installed. This won't impact your bundle size significantly if you've enabled tree shaking.

**Comment by iamhosseindhv** [comment]
Although I'm interested to know how (if at all) you're customising styling of the snackbars @gothraven

**Comment by gothraven** [comment]
@iamhosseindhv I'm actually using the provider `content` prop to inject my own snack-bar component and I use the message param to to send whatever I want, I use nothing but the logic of showing and dismissing snack-bars

**Comment by oncet** [comment]
Such a boomer. Was really excited for trying Notistack until I got this error. I guess I'll stick with react-toastify for now.

**Comment by Yard-Daniel** [comment]
Just checked the logs and this is still a problem after 2 years and mentioned a couple of times of the past few years 😄

**Comment by iamhosseindhv** [comment]
Hey @Yard-Daniel . The alpha version is a WIP which doesn't have dependency on MUI and will be published as the stable release.
