### ISSUE TITLE
`variantDefault` class usage throws an error

### ISSUE THREAD

**Issue by newsiberian** [iamhosseindhv/notistack#342]
I added class `variantDefault` to `SnackbarProvider` `classes` and **it is works**, which is good, but it throws
```
The key `variantDefault` provided to the classes prop is not implemented in SnackbarItem.
You can only override one of the following: root,anchorOriginTopCenter,anchorOriginBottomCenter,anchorOriginTopRight,anchorOriginBottomRight,anchorOriginTopLeft,anchorOriginBottomLeft,lessPadding,variantSuccess,variantError,variantInfo,variantWarning,contentRoot,message,action,wrappedRoot,collapseContainer,collapseWrapper,collapseWrapperDense.
```

## Expected Behavior

It should allow to customize `variantDefault` w/o such warnings

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.1 |

**Comment by iamhosseindhv** [comment]
To customise default snackbar you can use `className` prop.
