### ISSUE TITLE
SnackbarContent not being exported for TypeScript

### ISSUE THREAD

**Issue by tarazena** [iamhosseindhv/notistack#343]
When we try to import SnackbarContent, Typescript cannot find it, using the import below will throw an error
```ts
import { SnackbarContent } from 'notistack';
```

Error: `Module '"../../../node_modules/notistack/dist"' has no exported member 'SnackbarContent'.`

## Expected Behavior

Able to import `SnackbarContent` with no issues
## Current Behavior

Unable to import `SnackbarContent`;
## Steps to Reproduce

import `SnackbarContent`in any `tsx` file using `import { SnackbarContent } from 'notistack';`

Link:

1.
2.
3.
4.

## Context

want to create a custom snackbar for my app

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | 1.0.3  |
| React        |    16.9.0     |
| Browser      |    any     |
| etc.         |         |

**Comment by israeldax** [comment]
There is no SnackbarContent exported from index.d.ts. The component is exported but not the type.

**Comment by iamhosseindhv** [comment]
Thanks for reporting this issue and for your patience. 
Fix is released as `v1.0.4`.
