### ISSUE TITLE
TransitionComponent: Grow not working correctly when using custom content option

### ISSUE THREAD

**Issue by slutske22** [iamhosseindhv/notistack#346]
## Expected Behavior
I am using `content: k => <CustomContent />` in the options passed to `enqueueSnackbar`.  It works just fine with the default `TransitionComponent`, or even when defining `TransitionComponent: Slide`.  I would expect the same for `TransitionComponent: Grow` or `Zoom` or `Fade`, i.e. my `CustomContent` component should transition in and out correctly with the given material UI `Transition` when queued.

## Current Behavior
The `CustomContent` just appears on screen with no enter animation when using these other Transition components.  They transition *out* just fine.  Though what's even stranger is that with Grow, it fades out, and with Fade or Zoom, it collapses out, and with Collapse, it collapses in and out correctly as expected.  Specifying these transitions works correctly without a custom `content` option.  I'm not sure if this is truly a Notistack bug or just something wrong with the way I'm using it?

### Link: [Working codesandbox demonstrating the issue](https://codesandbox.io/s/notistack-transition-issue-1y0bh)
This was forked from the redux example, as I am trying to implement this in a redux environment similar to that example.  Not sure if that has anything to do with it.

My app's implementation looks like this:

```javascript
// Custom component I want to use in options: content
const CustomSnackbar = React.forwardRef((props ref) => {

    // lots of logic to handle props, which is why I want a separate CustomSnackbar component

    return (
      <SnackbarContent
        ref={ref}
        className={() => functionOfProps() }
        message={props.message}
        action={() => functionOfProps_returnsJSX()}
      />
    );
  }
);

CustomSnackbar.displayName = "CustomSnackbar";

export default CustomSnackbar;
```

```javascript
// Use of CustomSnackbar in enqueueSnackbar
const GlobalSnackbar () => {

  const dispatch = useDispatch();
  const notifications = useSelector(state => state.snackbar);
  const { enqueueSnackbar, closeSnackbar } = useSnackbar();

  // more logic here to handle sync with redux store

  useEffect(() => {
    notifications.forEach(notification => {
      const { message, moreDetails } = notification;

      const options: OptionsObject = {
        key: generateRandomKeyFunction(),
        onClose: () => functionToRemoveNotificationFromReduxStore(key),
        TransitionComponent: Grow, // <---------------------------------------- Problem right here
        content: (k: string) => (
          <CustomSnackbar
            onClose={(): void => removeNotification(k)}
            message={message}
            moreDetails={moreDetails}
          />
        )
      };

      enqueueSnackbar(message, options);

    });
  }, [notifications, closeSnackbar, enqueueSnackbar, dispatch]);

  return null;
};
```

## Context
Trying to refactor a large app's snackbar feature using notistack, while using their existing styling / transitions / logic for custom snackbar content.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI | 4.8.3 |
| Notistack | v1.0.3  |
| React        |  16  |
| Browser      | Chrome |

**Comment by Nesvet** [comment]
Same here. Any updates?

**Comment by slutske22** [comment]
I never figured out a solution.  I decided to go with the `Slide` transition.  If my UX guy insists on using the `Grow` transition, I'm screwed 😆

**Comment by iamhosseindhv** [comment]
Believe it or not I'm on the same boat 😁. It's been a while and the community has not cared enough to investigate more and come up with a fix. Not many upvotes on this issue either. So I'm closing this as a part of house keeping.

**Comment by iamhosseindhv** [comment]
For everyone seeing this, solution is described here #475

**Comment by andyngdz** [comment]
For who is facing this issue by using the `content` prop. This is how I fix it, in your custom component, you need to extract the `style` and assign it to the first element. The `style` is passed down by the `Grow` component


This is my custom component:

```
// MyCustomComponent.tsx
....

const { style, ....yourRestProps } = props;

return <div style={style}>...</div>
```

This is my SnackbarProvider looks like:

```
<SnackbarProvider
  domRoot={document.body}
  content={key => <MyCustomComponent key={key} id={key} />}
  TransitionComponent={Grow as React.ComponentType}
  preventDuplicate
  disableWindowBlurListener
>
  {children}
</SnackbarProvider>
```
