### ISSUE TITLE
Allow for multiline snackbar messages

### ISSUE THREAD

**Issue by steinbergh** [iamhosseindhv/notistack#35]
Currently SnackBar notifications are expected to be a very specific height causing SnackBars with multiline messages to stack on top of each other,  I would like for variable heights to be accounted for or would like to have access to the TransitionProps and level prop of the SnackBarItem to customize this.

**Comment by iamhosseindhv** [comment]
I got your point. This is a must have and something that notistack has to manage internally. I'll plan for adding this to the next version.

**Comment by iamhosseindhv** [comment]
@steinbergh Fix for this is pushed to the master and will be published in the next version. see [changelog](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md) for more info.

**Comment by steinbergh** [comment]
Thanks so much!

**Comment by iamhosseindhv** [comment]
@steinbergh This is published now.
