### ISSUE TITLE
TypeError: (0 , _notistack.withSnackbar) is not a function

### ISSUE THREAD

**Issue by gel-prog** [iamhosseindhv/notistack#350]
This error (`TypeError: (0 , _notistack.withSnackbar) is not a function`) only occurs when I run the test (`react-scripts test`) for the application.

Notistack version: 0.8.8
React: 16.13.1

Example test:

```
import React from 'react';
import { shallow } from 'enzyme';
import App from './App';

it('renders without crashing', () => {
  shallow(<App />);
});
```

Component:

```
import { withSnackbar } from 'notistack';

class Dialog extends React.Component {
...
}
export default withSnackbar(Dialog);
```

App:
```
const App = () => {
  return (
      <SnackbarProvider maxSnack={3}>
        <AppFrame />
      </SnackbarProvider>
  );
};
```

After some searching, I saw that that specific type of error often was related to how the module was important. For example, using no curly braces were used. But I do use them. So I am unsure what creates the error.

**Comment by iamhosseindhv** [comment]
Please follow the Bug Report template by providing a small reproducible example.
