### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of null when using react-hooks-test-library

### ISSUE THREAD

**Issue by johanbook** [iamhosseindhv/notistack#352]
I have implemented  Snackbar component that listens to events in the document and triggers a snackbar on such an event. This works flawlessly when used in Create-React-App and in React Testing Library. However, I also have a hook that triggers a snackbar which I was hoping to test with [react-hooks-testing-library](https://github.com/testing-library/react-hooks-testing-library), however upon doing so I get the error

```
TypeError: Cannot read property 'getBoundingClientRect' of null

    > 29 |         enqueueSnackbar(message, { key: id, variant: variant });
         |         ^
      30 |       }
```

Do someone know as to why?

## Releated issues

- Same error as in https://github.com/iamhosseindhv/notistack/issues/240, but I cannot see how references plays in as I give `enqueueSnackbar'` a string message rather than a React component
- One can mock `notistack` instead, as discussed in https://github.com/iamhosseindhv/notistack/issues/203 but I'd prefer to avoid mocking if possible

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.4  |
| React        |  v17.0.1       |

## Other

If this is deemed a serious issue I'll supply a reproducible example.

**Comment by iamhosseindhv** [comment]
Could provide a reproducible example?

**Comment by johanbook** [comment]
I no longer have access to code that caused this issue. Closing issue.
