### ISSUE TITLE
Notification with persist and preventDuplicate set to true should rerender when calling multiple times.

### ISSUE THREAD

**Issue by smashboy** [iamhosseindhv/notistack#353]
Hi! When `persist` and `preventDuplicate` is set to `true` my `action` function is not getting new props, because notification is not re rendering. Is there any way to do persistent notification that can get new props when calling notification() multiple times without re opening (re animating)?

![image](https://user-images.githubusercontent.com/30213662/107772684-3a1bbf00-6d45-11eb-9ee1-be0749403dfd.png)

## Expected Behavior
`persist` and `preventDuplicate` set to `true`  should not block re rendering, but should not re animate notification

## Current Behavior
Calling notification with `persist` and `preventDuplicate` set to `true`  is not re rendering notification that causes action not receiving new props

## Context
I have three separate forms and when state in one of them is changed notification will show up, but because notification is not re rendering if state is changed in other forms when user click on button in notification action, Im getting only one form state

![image](https://user-images.githubusercontent.com/30213662/107773614-96331300-6d46-11eb-9fdc-40fdad876976.png)

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.3  |
| React        |    v16.14.0     |

**Comment by ziek-za** [comment]
Bump!

**Comment by iamhosseindhv** [comment]
Closing as this issue has not received many upvotes
