### ISSUE TITLE
[next] Upgrade peerDependencies to support material-ui v5

### ISSUE THREAD

**Issue by ApacheEx** [iamhosseindhv/notistack#355]
## Expected Behavior
when I run `npm install notistack@next` in project where I have `@material-ui/core@next` installed I should not see any errors.

## Current Behavior
![image](https://user-images.githubusercontent.com/1918108/109123052-1481b300-7752-11eb-938c-665964d5bd93.png)

## Steps to Reproduce
simply install dependency:
- `npm i @material-ui/core@next`
- `npm i notistack@next`

## Your Environment
- `node: v15.10.0`
- `npm: 7.5.3`

## Solution
update package.json + regenerate package-lock.json
![image](https://user-images.githubusercontent.com/1918108/109123525-9e318080-7752-11eb-9f20-9d56874878b2.png)

p.s thanks for really awesome project. I love it.

**Comment by iamhosseindhv** [comment]
Thanks for reporting. Please update your notistack to `next` / `notistack@1.0.6-alpha.0`

**Comment by lcdss** [comment]
> Thanks for reporting. Please update your notistack to `next` / `notistack@1.0.6-alpha.0`

`npm i notistack@next` add `^1.0.6-alpha.0` to composer.json, and after the `1.0.6` release, if you run `npm update` it'll give you an error as the `1.0.6` doesn't allow Material UI V5.
