### ISSUE TITLE
align snackbars with different message length to the anchorOrigin

### ISSUE THREAD

**Issue by martas-eiratech** [iamhosseindhv/notistack#358]
First of all, thanks a lot for creating this amazing library!

I think it would be great to align snackbars of different width to their `anchorOrigin`, e.g. if they are in bottom right, they should start from the right no matter if other snackbars appear with longer messages.

## Expected Behavior

For example in my case snackbars are in **bottom right** corner, so I would expect them to look like this:

![Screenshot from 2021-03-03 11-30-59](https://user-images.githubusercontent.com/65537538/109799515-0b8e5700-7c14-11eb-8372-5cb1463128af.png)

## Current Behavior

Currently, if a second snackbar appears with a longer message, the shorter snackbars jump to the left to be aligned with it at `flex-start` of their container.

![Screenshot from 2021-03-03 10-55-17](https://user-images.githubusercontent.com/65537538/109799891-76d82900-7c14-11eb-96f3-de2b19c91d20.png)

## How I fixed this (not ideal)

I have overridden this behavior with creating `containerRoot` class and making my way to the snackbar wrapper:

```
containerRoot: {
  '& > .MuiCollapse-container > .MuiCollapse-wrapper': {
    justifyContent: 'flex-end',
  },
},
```

## My Environment

| Tech         | Version |
|--------------|---------|
| Notistack | 1.0.5  |
| React        |  16.13.1 |
| Browser      | Chrome |

**Comment by iamhosseindhv** [comment]
Thanks for the kind words. I'm glad you're able to apply your customisation, but I don't think this should be the default behaviour of the library as RTL users mostly have their notifications on bottom-right. So having this as default behaviour wouldn't be ideal for them either.
