### ISSUE TITLE
Snackbars do not stay on screen long enough when a new one is created

### ISSUE THREAD

**Issue by ryanbrogden** [iamhosseindhv/notistack#360]
## Expected Behavior
As in version 0.9.16 when a new snackbar was created, the old one completed it's timeout before being dismissed.

## Current Behavior
From version 0.9.17 onwards the snackbar is immediately dismissed for a new one

## Steps to Reproduce
Simply set the maxSnack to 1, then create two snackbars in quick succession.

I haven't created a codesandbox for this, but it is very simple to reproduce, I am happy to put one together if needed.

## Context
This appears to be mostly an issue when the maxSnack is set to one. This means that our users are unable to read the first snackbar before the next one takes it's place.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.5  |
| React        |    16     |
| Browser      |     Chrome    |

**Comment by Temez1** [comment]
Not only with maxStack one. I'm using the default 3 and in one situation this happens to me. When the user signs in (with pop-up) and there is a notification in the stack both gets dismissed when the older one dismisses,


https://user-images.githubusercontent.com/46352445/112216956-c8c80980-8c2a-11eb-84a9-4377e8204500.mp4

**Comment by iamhosseindhv** [comment]
Dup of #204.

**Comment by diogoribeiro23** [comment]
@iamhosseindhv I just encountered the issue that @Temez1 reported. I think it is unrelated to both this one and the #204, as it works properly in the v2 but not in the v3.
Do you have any ideia on what is happening?
