### ISSUE TITLE
Forward all props from SnackbarItem to custom content, not just key and message

### ISSUE THREAD

**Issue by HerrPfister** [iamhosseindhv/notistack#361]
## Expected Behavior
I should be able to use my own component within the content of the snackbar, and have access to all props normally passed down to SnackbarContent.

## Current Behavior
Using the  content property only the key and message get passed down to my own component.
```content = content(key, snack.message);```

## Context
Currently I am trying to use Mui's Alert so that I can change the variant property to be outlined, but I also need to have the variant property from the SnackbarItem passed in to style it correctly.

**Comment by HerrPfister** [comment]
Added a PR https://github.com/iamhosseindhv/notistack/pull/362 to fix this.

**Comment by iamhosseindhv** [comment]
Dup of #242 
See my comment on #362
