### ISSUE TITLE
custom snack item can't easily receive props and features on the default ones

### ISSUE THREAD

**Issue by keul** [iamhosseindhv/notistack#364]
This is partially related to #242 

## Expected Behavior

It seems there's no way to have a custom Custom snackbar that inherit all of the features of the default ones, while IMHO the main feature of a custom snackbar would be to add custom features _without_ rewriting everything from scratch.

In my usecase: I want the very default snackbar, but my "message" is composed by a `title` and a `details` section.

## Current Behavior

The [Custom notistack example](https://www.iamhosseindhv.com/notistack/demos#custom-snackbar) is pretty clear and complete. But note that in this example we have an hardcoded "yellow" background style.

I'm able to use this pattern to display `title` and `description`, but then I loose every other feature, like customized `iconVariant` or `classes`.

Not 100% sure, but trying to look at the source I see that the issue can have origin by the use of a custom element instead of a component:

https://github.com/iamhosseindhv/notistack/blob/8c6d6bf599b5af1599a1849d7f32f59b451cec77/src/SnackbarItem/SnackbarItem.tsx#L245:L266

A custom `content` defined as:

```javascript
    content={(key, message) => (
        <MyCustomChildren id={key} message={message} />
    )}
```

…seems to not receive any of the many props passed to the default `SnackbarContent`.

**Comment by iamhosseindhv** [comment]
There's work being done about this. See my https://github.com/iamhosseindhv/notistack/pull/362#issuecomment-798734786. Feel free to propose features / agree/disagree there.
