### ISSUE TITLE
"anchorOrigin{vertical}{horizontal}" classes are applied to SnackbarContainer instead of "containerAnchorOrigin{vertical}{horiziontal}" classes

### ISSUE THREAD

**Issue by raulgg** [iamhosseindhv/notistack#365]
I'm trying to customize the style of the Snackbar and the SnackbarContainer to add an offset margin when displaying the notifications with `top` vertical origin. To do so I've created to overwrite the `top` CSS property applied by default and I've passed it down through the `classes` prop in the SnackbarProvider component.

```
<SnackbarProvider
  maxSnack={4}
  anchorOrigin={{
    vertical: "top",
    horizontal: "right"
  }}
  classes={{
    containerAnchorOriginTopLeft: snackbarTopOffsetClass,
    containerAnchorOriginTopCenter: snackbarTopOffsetClass,
    containerAnchorOriginTopRight: snackbarTopOffsetClass
  }}
  TransitionComponent={Slide}
>
```

When rendering the Snackbars the class isn't added to the SnackbarContainer component. Instead when configuring the classes to be applied instead to the `anchorOrigin{vertical}{horizontal}` classes we can see how they are being applied to both the SnackbarContainer and SnackbarItem components.

## Expected Behavior
`anchorOrigin{vertical}{horizontal}` classes should be only applied to the SnackbarItem component and `containerAnchorOrigin{vertical}{horizontal}` classes should be applied to the SnackbarContainer component.

## Current Behavior
anchorOrigin{vertical}{horizontal}` classes are applied to the `SnackbarItem` and `SnackbarContainer` components and `containerAnchorOrigin{vertical}{horizontal}` classes aren't applied at all.

## Steps to Reproduce
Link to a Codesandbox reproducible example:  https://codesandbox.io/s/notistack-classes-bug-1qonm

**Comment by iamhosseindhv** [comment]
Closed in https://github.com/iamhosseindhv/notistack/pull/366#issuecomment-826093561
