### ISSUE TITLE
Snackbar props not honored on smaller screens

### ISSUE THREAD

**Issue by rzmz** [iamhosseindhv/notistack#367]
I think a screenshot of notistack documentation website will best describe the problem:

<img width="341" alt="Screenshot 2021-04-09 at 13 06 05" src="https://user-images.githubusercontent.com/712964/114165328-0029fc00-9935-11eb-8f9a-e7fa3ad62a47.png">

The notification appears to the left of the screen, instead should be in center as selected.

**Comment by raulgg** [comment]
I've noticed this issue as well. It seems to be a CSS problem, you can add a class to the providers configuration to bypass this issue.

For the case in your screenshot I would do the following: 

```
const useStyles = makeStyles((theme) => ({
  containerTopOffset: {
    display: "flex",
    alignItems: "center",
  }
}));
```

```
<SnackbarProvider
  maxSnack={3}
  anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
  classes={{
    anchorOriginBottomCenter: classes.containerBottomCenter
  }}
>
  <MyApp />
</SnackbarProvider>
```

**Comment by rzmz** [comment]
Thanks! Will try that.

**Comment by iamhosseindhv** [comment]
I noticed this issue and the fix will be published soon. In the meantime, it's the `wrapperInner` element of `Collapse` that you need to customise.


```jsx
const useStyles = makeStyles((theme) => ({
  container: {
    [theme.breakpoints.down('xs')]: {
        '& > .MuiCollapse-container > .MuiCollapse-wrapper  > .MuiCollapse-wrapperInner ​': {
           width: '100%',  // occupy full-width on xs screens
        },
    }
 },
}));


const classes = useStyles();
return (
<SnackbarProvider
  maxSnack={3}
  anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
  classes={{
    containerRoot: classes.container
  }}
>
  <MyApp />
</SnackbarProvider>
)
```

**Comment by rzmz** [comment]
I unfortunately had no luck with neither of those solutions at first but when I changed
```anchorOriginBottomCenter: classes.containerBottomCenter```
to point to correct classname ```containerTopOffset```, solution by @raulgg works! Thanks!

**Comment by danyy1996** [comment]
> I noticed this issue and the fix will be published soon. In the meantime, it's the `wrapperInner` element of `Collapse` that you need to customise.
> 
> ```js
> const useStyles = makeStyles((theme) => ({
>   container: {
>     [theme.breakpoints.down('xs')]: {
>         '& > .MuiCollapse-container > .MuiCollapse-wrapper  > .MuiCollapse-wrapperInner ​': {
>            width: '100%',  // occupy full-width on xs screens
>         },
>     }
>  },
> }));
> 
> 
> const classes = useStyles();
> return (
> <SnackbarProvider
>   maxSnack={3}
>   anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
>   classes={{
>     containerRoot: classes.container
>   }}
> >
>   <MyApp />
> </SnackbarProvider>
> )
> ```

This didn't work for me at first. However after a minor modification it is now working! Thanks for that!

``` js
const useStyles = makeStyles((theme) => ({
  container: {
    [theme.breakpoints.down("xs")]: {
      "& .MuiCollapse-container, .MuiCollapse-container .MuiCollapse-wrapper .MuiCollapse-wrapperInner": {
        width: "100%" // occupy full-width on xs screens
      }
    }
  }
}));



```

**Comment by aeharding** [comment]
Here's my hotfix **(note: only for 100% 📱 projects, 🚫 🖥)**:

```scss
  .MuiCollapse-wrapperInner {
    // notistack broke mobile snackbar widths
    // remove once fixed: https://github.com/iamhosseindhv/notistack/issues/367
    width: 100% !important;
  }
```

**Comment by iamhosseindhv** [comment]
This is fixed in the latest release `v1.0.6`. I'd appreciate if one of you could confirm.

**Comment by danyy1996** [comment]
@iamhosseindhv I just tested on mine and I am getting the same problem :(

**Comment by aeharding** [comment]
I also confirm 1.0.6 is working for me.
