### ISSUE TITLE
Default background color

### ISSUE THREAD

**Issue by johnvonneumann7** [iamhosseindhv/notistack#369]
In the demo in the notistack documentation, the default snackbar is dark, but in the one I actually did, it is white.
I've read through the documentation and it doesn't look like I have any special settings.
What is the problem?

## Expected Behavior

![unknown1](https://user-images.githubusercontent.com/78252058/115963415-21f0c900-a55a-11eb-9d61-17a0f079bdeb.png)

## Current Behavior

![unknown](https://user-images.githubusercontent.com/78252058/115963421-2b7a3100-a55a-11eb-9b75-8e732065c2f5.png)

## Steps to Reproduce

```javascript
import React from "react";
import Button from "@material-ui/core/Button";
import { SnackbarProvider, useSnackbar } from "notistack";

function MyApp() {
  const { enqueueSnackbar } = useSnackbar();

  const handleClick = () => {
    enqueueSnackbar("I love snacks.");
  };

  return <Button onClick={handleClick}>Show snackbar</Button>;
}

export default function snack() {
  return (
    <SnackbarProvider maxSnack={3}>
      <MyApp />
    </SnackbarProvider>
  );
}
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.6  |
| React        | v17.0.1  |
| TypeScript        | v4.2.3  |

**Comment by iamhosseindhv** [comment]
Theme in the documentation website is `light`. Background is automatically turned to semi-white, if material-ui theme is set to `dark`. 

Note that this behaviour (automatic change of background according to material-ui theme) will be removed in the next major release (`alpha` branch, currently available by `npm i notistack@alpha`).
