### ISSUE TITLE
Multiple Snackbars always left aligned

### ISSUE THREAD

**Issue by whytspace** [iamhosseindhv/notistack#373]
## Current Behavior

When showing multiple Snackbars of different width, they are always left aligned in their container:

![multiple-1](https://user-images.githubusercontent.com/4341219/116401682-cd846c80-a82b-11eb-9811-1524bfc4798b.png)

## Expected Behavior

Snackbar alignment should be determined by `anchorOrigin.horizontal`

![multiple-2](https://user-images.githubusercontent.com/4341219/116402577-e0e40780-a82c-11eb-95b9-849c4a231252.png)

https://codesandbox.io/s/serene-shadow-0hlb4?file=/App.js

1. Click the "short message" button
2. Clock  the "longer message" button

## Context

Sometimes I need to display Snackbars with more content than just a few words. Especially then it comes to i18n text length is quite unpredictable.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.5  |
| React        | v16.13.1 |

**Comment by alexbakx** [comment]
I ran into this same issue, you can work around this by setting the style for the SnackbarContainer root yourself. 

`const useStyles = makeStyles({
  root: {
   alignItems: 'flex-end'
  },
});

const classes = useStyles();

<SnackbarProvider maxSnack={3} classes={{ containerRoot: classes.root }}>
</SnackbarProvider>`

**Comment by iamhosseindhv** [comment]
Thanks for reporting the issue @whytspace. This is now fixed in v1.0.7. I'd appreciate if you could confirm.

**Comment by whytspace** [comment]
@iamhosseindhv
I can confirm, works like charm now 👍 

Thanks a lot for your great work!
