### ISSUE TITLE
Behavior of autoHideDuration option when windows is unfocused

### ISSUE THREAD

**Issue by tofutree23** [iamhosseindhv/notistack#375]
## Expected Behavior
Regardless of the focus of Windows, the autoHideDuration option should work normally.

## Current Behavior
If Windows is unfocused, it will be suspended

## Steps to Reproduce
Please look at the gifs below
Link:
1. ![image](https://user-images.githubusercontent.com/44552838/117235983-bca6ad00-ae62-11eb-8a50-2083b77c779e.gif)

## Context
While using notistack with autoHideDuration option, if windows were unfocused, the autoHideDuration option is suspended. Is this a bug?

## Your Environment
It also happens on demo pages.

**Comment by iamhosseindhv** [comment]
This is [intentional](https://github.com/iamhosseindhv/notistack/blob/alpha/src/SnackbarItem/Snackbar.tsx#L103-L112) and not a bug. You can also use `disableWindowBlurListener` prop to disable this functionality.
