### ISSUE TITLE
Snackbar Progress Indicator

### ISSUE THREAD

**Issue by preyansh98** [iamhosseindhv/notistack#377]
This is more of a feature request, but it would be great to have functionality in the form of a bottom progress bar that indicates the duration till snackbar times out. 

Currently it seems very manual to incorporate that functionality, so it would be greatly appreciated as a feature! It can be a prop such as ``showProgress`` in the SnackbarProvider.

## Expected Behavior

Have a progress bar at bottom of snackbar. Similar to react-toastify

## Examples
Link:

1. https://www.npmjs.com/package/react-toastify

**Comment by iamhosseindhv** [comment]
Thanks for the suggestion @preyansh98 

I agree such feature would be a nice thing to have, but also I can assure you it won't be natively implemented in notistack using `showProgress` prop or anything of that kind.

Currently you can implement your own [custom snackbar](https://iamhosseindhv.com/notistack/demos#custom-snackbar) with a progress bar in it. And in the next major release (v2 `npm i notistack@alpha`), you'll be able to update progress of the progress bar using `enqueueSnackbar`.

Hope that's useful.
