### ISSUE TITLE
All versions with minor changes contain breaking changes ?!

### ISSUE THREAD

**Issue by valentinbourqui** [iamhosseindhv/notistack#378]
This now the third time that when I'm updating your library with a minor update version it break everything regarding the CSS and adding errors inside the console. 

For example now between 1.0.6 and 1.0.7 collapseWrapperInner is not anymore here as a css property for SnackbarProvider. 

Why you are not updating your library as a major update if there is some breaking change ?   Why your are not listing all you breaking change between your different versions ? 

I think it could be benefit for everything and it could save us time.

**Comment by iamhosseindhv** [comment]
I get your point, but `collapseWrapperInner` and other Collapse classNames were part of internal implementation of notistack. They we never meant to be used using `classes` prop, hence why they were never listed in the [documentation website](https://iamhosseindhv.com/notistack/api#classes).

[As other](https://github.com/iamhosseindhv/notistack/issues/358#issue-821033123) people [have done](https://github.com/iamhosseindhv/notistack/issues/367#issuecomment-816999247), any customisation to the Collapse component should have been done through CSS selectors. Which is still possible to do in v1.0.7. 

Btw you mentioned this was the third time, I'd appreciate if you could let me know what were the other two times, so I can prevent them for other users in the future.

✌🏼
