### ISSUE TITLE
SnackBar Shows Strange Code on UI.

### ISSUE THREAD

**Issue by Jaal-tech** [iamhosseindhv/notistack#379]
Whenever Snackbar message is triggered it shows some strange code in bottom of the body. I commented all the hierarchical components to make sure that it's the snackbar, When snackbar is triggered, it shows the strange number.

## Expected Behavior

It should not show strange seconds number in footer

## Current Behavior

When snackbar triggers it shows strange code in footer of app

## Steps to Reproduce

Link:

1. Just Trigger the snackbar.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.9.17 / v1.0.7 |
| React        |   17      |
| Browser      |   Chrome 90.0.4430.212       |
| etc.         |         |

ScreenShot
![image](https://user-images.githubusercontent.com/74218797/117985413-abe4b400-b306-11eb-9a56-79306e6704b0.png)

**Comment by iamhosseindhv** [comment]
That looks like `id` or `key` of a Snackbar. I don't see why notistack would cause it. I would've expected more people to complain about it, if that was the case. Could you provide a minimal reproduction example? @Jaal-tech

**Comment by Jaal-tech** [comment]
> That looks like `id` or `key` of a Snackbar. I don't see why notistack would cause it. I would've expected more people to complain about it, if that was the case. Could you provide a minimal reproduction example? @Jaal-tech

Yes its kind of id or key of time seconds on snackbar. On Sandbox I can't reproduce it but its only appearing on my application. any clue?

**Comment by iamhosseindhv** [comment]
Could you inspect the element and share that portion of the DOM tree?

**Comment by iamhosseindhv** [comment]
Closed due to inactivity.
