### ISSUE TITLE
Notification not centered.

### ISSUE THREAD

**Issue by angeshpc91** [iamhosseindhv/notistack#380]
This is the bug. this was introduced in the latest update.
the resolution is 365 x 640

![clipped notistack center bugg](https://user-images.githubusercontent.com/6001354/118524610-f5e0f600-b75b-11eb-9f1a-9e847b87c4db.png)

and this is the fix.
![clipped notistack center fixed](https://user-images.githubusercontent.com/6001354/118524624-f9747d00-b75b-11eb-9533-a672ff6ec96e.png)

Let me know if you want me to raise a pull request.

**Comment by iamhosseindhv** [comment]
Thanks for reporting @angeshpc91 . The fix is released as `v1.0.8`

**Comment by neo-elgiz-abbasov** [comment]
@iamhosseindhv I think this is broken again?

I see the fix you implemented [in this PR](https://github.com/iamhosseindhv/notistack/commit/a7826d3d2319cd44b6fc6083ae07c44f56b45701) applies centering to xs [but the current latest I believe is reverted back to only applying from width 600px](https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarContainer/SnackbarContainer.tsx#L74C5-L80C7)
