### ISSUE TITLE
Changing `background-color` style requires using `!important`

### ISSUE THREAD

**Issue by maciejpankanin** [iamhosseindhv/notistack#381]
## Expected Behavior
I wish I did not have to use `!important` for `background-color` while styling variants.

## Current Behavior
If I want to style variants I have to code something like that:
```ts
export const snackbarStyles = {
  variantSuccess: { backgroundColor: `${colors.apple} !important` },
  variantError: { backgroundColor: `${colors.flamingo} !important` },
  variantWarning: { backgroundColor: `${colors.orange} !important` },
  variantInfo: { backgroundColor: `${colors.mirage} !important` }
};

export default withStyles(snackbarStyles)(SnackbarProvider);
```

Which is not really good practise.

Moreover changing variants `background-color` style is impossible using `makeStyles` (without using `withStyles`).

**Comment by iamhosseindhv** [comment]
Thanks for reporting. As of v1.0.9, you do not need to use `!important` anymore.
