### ISSUE TITLE
Use theme colors for the snackbar item variants

### ISSUE THREAD

**Issue by rqbazan** [iamhosseindhv/notistack#383]
## Expected Behavior

The colors used as backgrounds in the snackbar item variants should be extracted from the theme.

## Current Behavior

There are fixed background colors:

https://github.com/iamhosseindhv/notistack/blob/f1e1e7600cd18508d199f2e274c0854d28eb6d10/src/SnackbarItem/SnackbarItem.tsx#L23-L38

## Steps to Reproduce

Irrelevant ⛔

## Context

Because of the library is using fixed colors, we're obliged to do something like https://github.com/iamhosseindhv/notistack/issues/177#issuecomment-539725566 but with the theme:

```js
const useStyles = makeStyles(theme => ({
  variantSuccess: { backgroundColor: theme.palette.success.main },
  variantError: { backgroundColor: theme.palette.error.main },
  variantWarning: { backgroundColor: theme.palette.warning.main },
  variantInfo: { backgroundColor: theme.palette.info.main },
}))
```

> The example does not take into account the following issue https://github.com/iamhosseindhv/notistack/issues/381 but I know that it requires `!important` to work properly

## Your Environment

Irrelevant ⛔

**Comment by iamhosseindhv** [comment]
Thanks for opening the issue. As of `v1.0.9`, you do not need to use `!important` anymore.

We're about to move away from Material-UI (see pinned issues). Giving users the option to customise variant colours through MUI theme, and then removing this in v2 is not ideal and I don't want to add an item the list of "Breaking Changes".

Hopefully the fact you no longer need to pass `!important` makes things easier. In v2 you have the option to use material-ui theme object to customise snackbars. (`npm i notistack@alpha`)

**Comment by rqbazan** [comment]
Hey @iamhosseindhv 👋

> In v2 you have the option to use material-ui theme object to customise snackbars. (npm i notistack@alpha)

Could you please give me an example of this customization? or maybe it's something that is WIP? 🤔

**Comment by iamhosseindhv** [comment]
See my comment https://github.com/iamhosseindhv/notistack/pull/362 @rqbazan
