### ISSUE TITLE
Show snack autoHideDuration progress per snack

### ISSUE THREAD

**Issue by LucusWebsites** [iamhosseindhv/notistack#386]
Is there any way to show the progress of the autoHideDuration per snack?

So I mean something like this (a little snackbar I wrote myself):

https://user-images.githubusercontent.com/3696955/118940658-39508580-b951-11eb-92a6-bbf20db73539.mp4

**Comment by iamhosseindhv** [comment]
I'd suggest giving `npm i notistack@2.0.1-alpha.2` a go. In next version of notistack you have access to `autoHideDuration` in your custom snackbar component and you can display the remaining time by implementing it yourself.
