### ISSUE TITLE
Support for material-ui/core@5

### ISSUE THREAD

**Issue by dryhurst** [iamhosseindhv/notistack#388]
Trying to update my project to use material-ui 5 and take advantage of my pro license. notistack is dependent on mui 4. How soon can we expect a version to support mui 5? Thanks.

**Comment by jannes-io** [comment]
I suppose currently #387 is the best way to track progress?

In our application with mui5 we don't have many issues, except for the automatic dismissal (autoHide) isn't working at all.

**Comment by iamhosseindhv** [comment]
As stated above. Track the progress there.

**Comment by Crismon96** [comment]
Hello @iamhosseindhv. First of, I love your slick snackbars and the API, thank you for it.
Did you make any progress with supporting the MUI5 alpha version. This here is the first search result for me, you wanted to update progress here but closed the ticket.
Is there any news on the subject?

**Comment by iamhosseindhv** [comment]
hi @Crismon96. THanks for the kind words.

That PR was closed by the author [see this comment](https://github.com/iamhosseindhv/notistack/pull/387#issuecomment-881417683). We now have #412 as an open issue.
