### ISSUE TITLE
Question about how the library works

### ISSUE THREAD

**Issue by i3ima** [iamhosseindhv/notistack#390]
Recently i tried to make my component for modals based on what i've seen in notistack source code.

But I don't understand where the [SnackbarProvider](https://github.com/iamhosseindhv/notistack/blob/066cb52f2c8cbdd57e1ba9c4f7937d0d603f5e50/src/SnackbarProvider.tsx) takes [domRoot ](https://github.com/iamhosseindhv/notistack/blob/066cb52f2c8cbdd57e1ba9c4f7937d0d603f5e50/src/SnackbarProvider.tsx#L269)from, for me this property undefined all the time

Can someone give me a hint?

**Comment by iamhosseindhv** [comment]
I'm not quite sure if I understand the question. However I've made this [codesandbox](https://codesandbox.io/s/quizzical-frost-qdzb9?file=/App.js) demonstrating how you could utilise `domRoot`, prop.

**Comment by iamhosseindhv** [comment]
Closed due to inactivity.
