### ISSUE TITLE
Material UI theme variables don't override the styles

### ISSUE THREAD

**Issue by VikasShashidhar** [iamhosseindhv/notistack#391]
First off, this is a great library and I am loving using it. I've been trying to use this with `material-ui` and its theme to customize the colors of the error, success and other variants of `notistack` but when I use the theme variables to define the background colors, they don't work. However, if I use a normal hex color value, it seems to work. I am unable to figure out what the issue is.

I am not sure if this is an issue with `notistack` or `material-ui`. I have setup `notistack` as per the documentation by wrapping my app with `SnackbarProvider` which is in turn wrapped with `MuiThemeProvider`.

## Expected Behavior
The variants should pick up the styles even when Material UI's theme variables are used.

## Current Behavior
The variants don't pick up the styles when Material UI's theme variables are used.

## Steps to Reproduce
Link: https://codesandbox.io/s/notistack-with-mui-theme-8pzry?file=/src/index.js

1. Click on the `Open Error Message` button. Observe that `notistack` doesn't pick up the custom styles for the error variant.
2. Click on the `Open Success Message` button. Observe that `notistack` picks up the custom styles for the success variant.

## Context
Trying to use `material-ui`'s theme variables to style the variants of `notistack`.

## Your Environment
| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.9  |
| React        | v17.0.1        |
| Material UI      | v4.11.3        |
| etc.         |         |

**Comment by VikasShashidhar** [comment]
@iamhosseindhv Any ideas about this issue?

**Comment by VikasShashidhar** [comment]
Closing as not relevant anymore.

**Comment by ggcaponetto** [comment]
@VikasShashidhar why ist this not relevant anymore?

**Comment by VikasShashidhar** [comment]
@ggcaponetto I unfortunately can't seem to remember the reason. I'll get back if I do.
