### ISSUE TITLE
How to use enqueue in axios interceptor

### ISSUE THREAD

**Issue by weeebdev** [iamhosseindhv/notistack#392]
I want to handle all exceptions inside of a axios interceptor like
```ts
export const commonExceptionHandler = (error: AxiosError) => {
  console.error('Task Manager:', error);
  return Promise.reject(error);
};
```
```ts
axios.interceptors.response.use((response: AxiosResponse) => response, commonExceptionHandler);
```

## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.?.?  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by tranquangdat1397** [comment]
same question

**Comment by iamhosseindhv** [comment]
Do any of the solutions [here](https://github.com/iamhosseindhv/notistack/issues/30) work for you? I'd suggest asking the question there.
