### ISSUE TITLE
./node_modules/notistack/dist/notistack.esm.js Attempted import error: 'makeStyles' is not exported from '@material-ui/core/styles'.

### ISSUE THREAD

**Issue by ariel-frischer** [iamhosseindhv/notistack#395]
```
./node_modules/notistack/dist/notistack.esm.js
Attempted import error: 'makeStyles' is not exported from '@material-ui/core/styles'.
```
I thought this package was working with @material-ui v5, I'm not sure what package update made things break. The weird thing is that I'm using the same dependencies as a material-ui kit that I purchased which I tested with yarn install, and is working fine. 

## Expected Behavior
No Error

## Current Behavior
Error

## Steps to Reproduce
I'm using:
```
 "notistack": "^1.0.9",
 "@material-ui/core": "^5.0.0-alpha.34",
 "@material-ui/data-grid": "^4.0.0-alpha.30",
 "@material-ui/icons": "^5.0.0-alpha.34",
 "@material-ui/lab": "^5.0.0-alpha.34",
 "@material-ui/styles": "^5.0.0-alpha.33",
 "react": "^17.0.1",
```

yarn v1.22.4
## Your Environment
Windows 10

**Comment by lcdss** [comment]
I had the same error today and I'm also using Material UI 5.0.0-alpha.34. I don't know yet why this happened, since my project dependencies didn't change. Yesterday it was working fine and now if I try to run the project it throws this error. How could this happen if only in v5.0.0-alpha.35 `makeStyles` was extract to @material-ui/styles?

**Comment by alanszp** [comment]
@lcdss  Check how you configure your dep on material-ui. Recommend to add an equal before the version so you can assure that it will always be .34

```
"@material-ui/core": "=5.0.0-alpha.34",
"@material-ui/icons": "=5.0.0-alpha.34",
"@material-ui/lab": "=5.0.0-alpha.34",
"@material-ui/system": "=5.0.0-alpha.34",
```

**Comment by xiaoyu-tamu** [comment]
> [styles] Remove makeStyles from @material-ui/core (#26382) @mnajdova

**Comment by ariel-frischer** [comment]
I see the main issue I think with yarn is that the `^` doesn't give you the exact version. I used `yarn add --exact @material-ui/core@5.0.0-alpha.34` without the caret and it seems to be fixed. Do this with the other MUI dependencies as well if needed.

**Comment by lcdss** [comment]
> @lcdss Check how you configure your dep on material-ui. Recommend to add an equal before the version so you can assure that it will always be .34
> 
> ```
> "@material-ui/core": "=5.0.0-alpha.34",
> "@material-ui/icons": "=5.0.0-alpha.34",
> "@material-ui/lab": "=5.0.0-alpha.34",
> "@material-ui/system": "=5.0.0-alpha.34",
> ```

I deleted the node_modules and installed the packages again. In the package-lock.json was specified .34 but for some reason, in the node_modules was 0.35.

**Comment by alanszp** [comment]
@lcdss  paste here your `package.json`

**Comment by lcdss** [comment]
> @lcdss paste here your `package.json`

The package.json allows the .35 version, but I didn't run `npm update` so the node_modules shouldn't be with the .35 version. But was easier just delete the node_modules and install the packages again. I also may have updated and don't remember. :disappointed_relieved:

**Comment by Hummel37** [comment]
@iamhosseindhv 
Will notistack support the Material UI 5 beta?

**Comment by fishyFrogFace** [comment]
Created a fix here (which afaik only will work with 5.0.0-alpha.35 and up): https://www.npmjs.com/package/notistack5.
Planning to maintain this package until the original supports v5 fully.

**Comment by Moshyfawn** [comment]
> 
> 
> Created a fix here (which afaik only will work with 5.0.0-alpha.35 and up): https://www.npmjs.com/package/notistack5.
> Planning to maintain this package until the original supports v5 fully.

Thank you, @fishyFrogFace. Your fork does work as long as you
- Install `@material-ui/styles` package that matches the version of the installed `@material-ui/core` package.
- If the version of `@material-ui/core` package is greater than `5.0.0-alpha.36` _(which is the latest version of  `@material-ui/styles` package)_, you should install `@material-ui/styles: 5.0.0-alpha.36`
- There's no `5.0.0-alpha.34` version of the  `@material-ui/styles` package, so it should to be ``5.0.0-alpha.33` to be able to use `notistack5`

I've setup [a quick codesandbox](https://codesandbox.io/s/silly-oskar-xberw) to test version compatibility etc. if needed

**Comment by lcdss** [comment]
> Created a fix here (which afaik only will work with 5.0.0-alpha.35 and up): https://www.npmjs.com/package/notistack5.
> Planning to maintain this package until the original supports v5 fully.

@fishyFrogFace  I needed to patch the notistack5 `package.json` file make it work with vitejs:

```patch
-    "module": "dist/notistack.esm.js",
+    "module": "dist/notistack5.esm.js",
```

**Comment by benediktdertinger** [comment]
@fishyFrogFace thanks for your package!

We are using it with 
```json
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@material-ui/core": "^5.0.0-beta.0",
    "@material-ui/icons": "^5.0.0-beta.0",
    "@material-ui/styles": "^5.0.0-beta.0",
    ... 
    "next": "^11.0.1",
    ...
    "notistack5": "^1.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    ...
    "typescript": "4.3.5"
```

and i get an `Unhandled Runtime Error
TypeError: Cannot read property 'snackbar' of undefined`

We tried various solutions posted in several issues but none worked. Any idea?

![Screenshot 2021-07-13 at 16 45 18](https://user-images.githubusercontent.com/6225675/125472807-c4e08475-16d4-482a-a54a-46cc555372df.png)

**Comment by Neuromancer93** [comment]
<img width="506" alt="Screen Shot 2021-07-13 at 2 52 00 PM" src="https://user-images.githubusercontent.com/47542813/125530097-0c846a25-584c-42b5-b903-22efd3041adc.png">

**Comment by Neuromancer93** [comment]
theme.zIndex.snackbar is not defined. If I go into the module and give it a value it gets past this issue, but then I get another one

**Comment by Neuromancer93** [comment]
![Screen Shot 2021-07-13 at 2 54 36 PM](https://user-images.githubusercontent.com/47542813/125530374-203eda45-5f40-4f49-994b-3cff7b670a96.png)

**Comment by Neuromancer93** [comment]
this new package no longer seems like a viable solution unless this is fixed. The owner of the original package really needs to be more responsive. Its been 2 months since the last update and people keep posting on here that there is an issue. @iamhosseindhv do you even care at this point?

**Comment by iamhosseindhv** [comment]
@Neuromancer93 Yes I do. Read my [comment](https://github.com/iamhosseindhv/notistack/pull/387#issuecomment-879465274) on the PR associated with this issue.

@Hummel37 Definitely. `next` branch (`npm i notistack@next`) is meant to be the compatible branch with v5.

I'm closing this issue as there're already a PR for it. You can track the progress on #387
