### ISSUE TITLE
Is there a way to increase the width of a snackbar?

### ISSUE THREAD

**Issue by pfournier1** [iamhosseindhv/notistack#398]
Is there a way to increase or set a fixed width of a snackbar? Overriding classes (https://iamhosseindhv.com/notistack/demos#custom-snackbar) doesn't seem to work and there is no documentation on how to modify the height/width of a snackbar
`<SnackbarProvider></SnackbarProvider>`

**Comment by ShawLocke** [comment]
I think you can use `content` to customize.
