### ISSUE TITLE
 findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by SeyyedKhandon** [iamhosseindhv/notistack#399]
Here is the error which I got when using notistack, when the snack bar disappears this error will be printed out in browser console:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by iamhosseindhv** [comment]
Duplicate of #257 #345
