### ISSUE TITLE
[2.0.1-alpha.4] - snackbars not work

### ISSUE THREAD

**Issue by kkaplita** [iamhosseindhv/notistack#400]
## Expected Behavior
Snackbar should appear.

## Current Behavior
When i use with `enqueueSnackbar` i have `Uncaught TypeError: Cannot read property 'props' of undefined`

## Steps to Reproduce
1. Install version 2.0.1-alpha.4
2. Use `SnackbarProvider`
3. Use `enqueueSnackbar('message')`

## Context
I am using material-ui 5.0.0-alpha.38

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.1-alpha.4  |
| React        | 17.0.2 |
| Browser      | Latest Google Chrome |

**Comment by iamhosseindhv** [comment]
> I am using material-ui 5.0.0-alpha.38

You should use next and not alpha. Alpha is v2 and still a work in progress. We also have https://github.com/iamhosseindhv/notistack/issues/393 to fix this same issue. I appreciate they're easy to mis take.

`next` is what people should use if they're using MUI v5. Also you need to wait for #387 to get merged first if you're using MUI `> 5.0.0-alpha.34`. If you're using `<= 5.0.0-alpha.34` use `npm i notistack@next`.
