### ISSUE TITLE
[next] Faleid on @material-ui@5.0.0-beta.0

### ISSUE THREAD

**Issue by massonetto** [iamhosseindhv/notistack#401]
Notistack failed when try use it on material-ui new beta version release.

![Captura de tela de 2021-07-03 10-24-28](https://user-images.githubusercontent.com/10254699/124355791-626b6380-dbe9-11eb-9ca3-d892d8ba7f19.png)

The new documentation say 

```
[styles] Remove withStyles from @material-ui/core (#26377) @mnajdova

The withStyles JSS utility is no longer exported from @material-ui/core. You can use @material-ui/styles instead. Make sure to add a ThemeProvider at the root of your application, as the defaultTheme is no longer available. If you are using this utility together with @material-ui/core, you should use the ThemeProvider component from @material-ui/core instead.
```

**Comment by massonetto** [comment]
> You can't even go further than `5.0.0-alpha.34` using `1.0.6-next.0` because `makeStyles` was removed from `core`.

Offcurse , for this reason i created the issue. Now, dont have any version for the new beta released.

**Comment by lcdss** [comment]
> > You can't even go further than `5.0.0-alpha.34` using `1.0.6-next.0` because `makeStyles` was removed from `core`.
> 
> Offcurse , for this reason i created the issue. Now, dont have any version for the new beta released.

It was an agreement if you didn't realize that.

**Comment by iamhosseindhv** [comment]
Duplicate  of #395 
There's PR #387 to fix this and you can track the progress there.
