### ISSUE TITLE
Snackbar elements not clickable since updating to Material-UI 4.12

### ISSUE THREAD

**Issue by daviduzumeri** [iamhosseindhv/notistack#402]
## Expected Behavior
If I put a button in the snackbar and click on it, the button should be clickable.

## Current Behavior
Clicking on the button instead is overtaken by whatever's in the layer below (so for instance if the snackbar renders over a row in a list, the list row will be clicked rather than the button on the snackbar).

## Steps to Reproduce
Link: https://codesandbox.io/s/mui-412-action-broken-u5019?file=/MessageButtons.js

1. Click on "DEFAULT"
2. Click on "My Action"
3. Nothing happens.

If you go to the material-ui import on the left and switch it back to 4.11.4, it works.

## Context
I would like to have a snackbar notification with buttons I can click on. :)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.9  |
| React        | v17.0.2 |
| Browser      |  all  |

**Comment by longzheng** [comment]
Can also there seems to be an issue with the stacking behaviour

`material-ui/core@4.12.1`

![image](https://user-images.githubusercontent.com/484912/125034259-bf788500-e0d3-11eb-90ef-7f7d4424b1b5.png)

`material-ui/core@4.11.4`

![image](https://user-images.githubusercontent.com/484912/125034589-167e5a00-e0d4-11eb-98c7-3da8c2ac0f8e.png)

**Comment by uN1ck** [comment]
Same problem with: 
TECH | VERSION 
------ | ----------
 Notistack | 1.0.9 
 React | 4.11.2 
 Browser | Chrome

**Comment by ggascoigne** [comment]
I think that this is the cause https://github.com/iamhosseindhv/notistack/issues/394

**Comment by ShawLocke** [comment]
We recently upgrade material-ui to v4.12 and notistack to v1.0.9. And it is the same as @daviduzumeri described.

**Comment by iamhosseindhv** [comment]
This isn't a bug, as I've described [here](https://github.com/iamhosseindhv/notistack/issues/394#issuecomment-879473441), there are a couple solutions:

* If you're using MUI `< v4.12.0`, use `npm i notistack` or `npm i notistack@latest`

* If you're using MUI `>= v4.12.0`, use `npm i notistack@next`. Or you could go with this suggested solution https://github.com/iamhosseindhv/notistack/issues/394#issuecomment-877688487 (recommended)

**Comment by Methuselah96** [comment]
@iamhosseindhv Would you be open to changing the peer dependency on `@material-ui/core` to reflect that then? It's quite a bad experience to upgrade material-ui to the next minor version and for things to break.
