### ISSUE TITLE
Variant not being overridden properly

### ISSUE THREAD

**Issue by ronquiaj** [iamhosseindhv/notistack#403]
## Context
Hello! I'm having issues with trying to override the default styles for Snackbars. I've been following the documentation and this is what I have so far. The code below is within my Storybooks file for a custom component that uses the notistack snackbar:

```
const Template: Story<StatusMessageStackProps> = (
  args: StatusMessageStackProps
) => (
  <SnackbarProvider
    anchorOrigin={{
      vertical: "top",
      horizontal: "center",
    }}
    maxSnack={5}
    classes={{
      variantSuccess: colors.brandGreen,
      variantError: colors.errorRed,
      variantInfo: colors.brandBlue,
      variantWarning: colors.warningOrange,
    }}
  >
    <StatusMessageStack {...args} /> // this is a custom component which uses the notistack functions
  </SnackbarProvider>
);
```

and then the component that I'm using to render the Snackbars looks like this:

```
import React, { FC } from "react";
import { useSnackbar, VariantType } from "notistack";
import { withStyles } from "@material-ui/core/styles";
import { StatusVariant } from "../../types";
import styles from "../StatusMessage/styles";

export type Props = {
  /**
   * The array of our statusMessages
   */
  messages: {
    /**
     * The text to be displayed on the alert message
     */
    description: string;
    /**
     * Color of the message
     */
    variant: StatusVariant;
    /**
     * Whether or not we want to the alert to stay persistent, usually the snackbar disappears in a few seconds otherwise
     */
    persistent: boolean;
  }[];
};

const StatusMessageStack: FC<Props> = ({ messages }: Props) => {
  const { enqueueSnackbar, closeSnackbar } = useSnackbar();
  messages.forEach((message) => {
    enqueueSnackbar(message.description, {
      variant: message.variant as VariantType,
      persist: message.persistent,
    });
  });
  return <div></div>;
};

export default withStyles(styles)(StatusMessageStack);

```

It doesn't help that I'm sort of a noob with the MaterialUI framework, but some tips and a point in the right direction would be amazing.

## Expected Behavior
This is the color of the Snackbar I'd like to to have:

![image](https://user-images.githubusercontent.com/60367655/125212047-57ab7100-e270-11eb-9aad-084d9d125fa2.png)

## Current Behavior
The default color is still being used:

![image](https://user-images.githubusercontent.com/60367655/125212054-64c86000-e270-11eb-9ede-fb5e10d5da05.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.?.?  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
```
classes={{
      variantSuccess: colors.brandGreen,
      variantError: colors.errorRed,
      variantInfo: colors.brandBlue,
      variantWarning: colors.warningOrange,
}}
```

The problem is that for example `variantSuccess` should be the `className` of some css styles, but you're passing the colour directly. Depending what version of MUI you're using, you should do something like the following:

```tsx
const useStyles = makeStyle(() => ({
  myCustomSuccess: {
      backgroundColor: colors.brandGreen,
  },
}))

const Template: Story<StatusMessageStackProps> = (props) => {
    const classes = useStyles();
    return (
        <SnackbarProvider
            classes={{
                variantSuccess: classes.myCustomSuccess,
            }}
        >
            <StatusMessageStack {...args} />
        </SnackbarProvider>
    );
}
```

If you didn't understand what I mean please share the version of MUI you're using and I'll give a code that works.
