### ISSUE TITLE
Cannot interact with element provided via action prop

### ISSUE THREAD

**Issue by fjorge-briste** [iamhosseindhv/notistack#407]
## Expected Behavior

As a User, I should be able to interact with the React element provided to the action element in the SnackbarProvider. 

## Current Behavior

When I try and interact with the action button, the onClick action does not fire, therefore all snackbars called with the persist option that are supposed to be closed with a `closeSnackbar(key)` cannot be closed.

## Steps to Reproduce

Link: https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/simple-example?file=/MessageButtons.js

1. Click on the default in the example
2. Try to click on `My Action` 

The code indicates a JS Alert should have popped up when `Dismiss` is clicked, however when testing with Firefox, Chrome, and Safari I do not receive a javascript alert.
```
<Button color="secondary" size="small" onClick={() => alert('clicked on my custom action')}>
                    My action
                </Button>
```

This appears to be related to the "@material-ui/core": "4.12.0" release as setting the the dependency to 4.11.4 explicitly seems to fix the issue

Link: https://codesandbox.io/s/amazing-chatterjee-9linf?file=/package.json:753-783

## Context

Without this I am not able to have a functional close action button on my snackbars.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.9  |
| React        |    V17.0.2    |
| Browser      | Latest Chrome, FF, Safari        |
| MUI      |     V4 Latest    |

**Comment by git-debojit** [comment]
I am also facing the same issue. It works with Material UI 4.11.4 but not with the latest version 4.12.0.

**Comment by belayaShlyapa** [comment]
Duplicated of #406

**Comment by Thuplek** [comment]
Voce pode resolver esse erro simplismente ajustando o css do componente.

`
const useStyles = makeStyles((theme) => ({
  root: {
    pointerEvents: "auto"
  }
}));

export default () => {
  const classes = useStyles();
  return (
    <SnackbarProvider maxSnack={3} classes={{ root: classes.root }}>
      <MessageButtons />
    </SnackbarProvider>
  );
};`

alterei somente App.js

link sandBox -> https://codesandbox.io/s/sweet-poincare-l4qq8?file=/App.js:176-455
