### ISSUE TITLE
gaps between snack bars disappear after MUI 4.12.0

### ISSUE THREAD

**Issue by edmonl** [iamhosseindhv/notistack#411]
MUI version 4.12.0

After https://github.com/mui-org/material-ui/pull/24084, MuiCollapse-container is renamed to MuiCollapse-root.

## Expected Behavior
Snackbars have gaps in between, and `dense` prop of `SnackbarProvider` should work and adjust the gap.

## Current Behavior
No gap between Snackbars.

## Steps to Reproduce
With MUI >= 4.12.0, show multiple snackbars.

## Context
https://github.com/mui-org/material-ui/pull/24084
https://github.com/mui-org/material-ui/releases/tag/v4.12.0

## Your Environment
| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.9  |
| Material UI Core | 4.12.1 |
| React      |  17.0.2 |

**Comment by kgrhartlage** [comment]
This also affects `pointer-events`. Clicks on the `action` button are no longer recognized and you can instead interact with elements under the snackbar.

**Comment by iamhosseindhv** [comment]
Hi Please update notistack to v1.0.10
