### ISSUE TITLE
How to move the icon to the right?

### ISSUE THREAD

**Issue by ziedhajsalah** [iamhosseindhv/notistack#414]
Is there a way to move the icon from the left to the right?

**Comment by iamhosseindhv** [comment]
You can make your own snackbar in v2 alpha. Downloadable by `npm i notistack@alpha`. See this comment: https://github.com/iamhosseindhv/notistack/issues/421#issuecomment-903198460.

This is the [default snackbar](https://github.com/iamhosseindhv/notistack/blob/alpha/src/components/MaterialDesignContent/MaterialDesignContent.tsx) displayed by notistack. You can change it however you like and pass it in `Components` prop of `SnackbarProvider`.
