### ISSUE TITLE
UseSnackbar hook throws 'Invalid hook call error' on next branch

### ISSUE THREAD

**Issue by rickstaa** [iamhosseindhv/notistack#419]
When, I try to use the  `UseSnackbar` hook in the [notistack/tree/next](https://github.com/iamhosseindhv/notistack/tree/next) branch, I receive the following error:

```bash
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
```

## Expected Behavior

The hook should work.

## Current Behavior

Something goes wrong inside the useSnackBar hook.

## Steps to Reproduce

1. Clone the [Notistack repository](https://github.com/iamhosseindhv/notistack).
2. Clone [this example repository](https://github.com/rickstaa/notistack-test).
3. Link notistack using `npm link` in the notistack folder and `npm link notistack` in the example repository folder.
4. Run `npm start`.
5. See the error appear.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | @next  |
| React-(dom)        |    v17.0.2     |
| Browser      |   firefox  91.0 (64-bit)  |

**Comment by rickstaa** [comment]
I did some debugging, but this seems to be caused by using `npm link` with CRA. A solution for this is found [here](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

**Comment by erikswed** [comment]
> I did some debugging, but this seems to be caused by using `npm link` with CRA. A solution for this is found [here](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

How did you solve this I see the same thing happened . I fork notistack and npm link it locally.
When I do the suggest test [this as you mention also](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react):
window.React2 = require('react'); // place is notistack
window.React1 = require('react'); // place in man app
console.log(window.React1 === window.React2); // this return false 

This return false so two different react is used right, but when I check the pagage.json for notisstack I see this:

```
    "peerDependencies": {
        "react": "^16.8.0 || ^17.0.0",
        "react-dom": "^16.8.0 || ^17.0.0",
        "@material-ui/core": "^4.0.0"
    },
```

So how can I use two different "react"? Any help would be great to start debugging notistack

**Comment by rickstaa** [comment]
@erikswed If I remember it correctly, I linked react in my package to the one that is found in the `../notistack/node_modules/react` folder. This is also the solution given in [the documentation](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react).

```bash
npm link ../notistack/node_modules/react
```

**Comment by rickstaa** [comment]
@erikswed Glad the solution worked out! Thanks for the heads-up! I haven't noticed that problem myself, but it might be introduced in a later version than the one I use.
