### ISSUE TITLE
Add option to persist a notification until dismissed

### ISSUE THREAD

**Issue by mckernanin** [iamhosseindhv/notistack#42]
I would like to be able to have a notification persist, until manually dismissed by the user. I'm happy to work on this and create a PR, wanted to open an issue first to make sure this is a feature you'd be open to adding.

**Comment by iamhosseindhv** [comment]
Thanks for opening the issue first @mckernanin.

You can set `autoHideDuration` prop to `null` or `undefined` to prevent snackbars from getting dismissed. However, if you've enabled stacking behaviour (i.e. `maxSnack > 1`), your notification will get dismissed by notistack when maxSnack is reached. 

You're welcome to make a PR for these cases. Suggestion implementation is to allow a new option `persist: true|false` in the options parameter of `enqueueSnackbar`, and default it to be `false`. 

I'll merge your PR or add support for this myself after 22 Jan (as I'm in the middle of university exams).

**Comment by cevr** [comment]
Hi, @iamhosseindhv. Can this be added to the documentation?

**Comment by iamhosseindhv** [comment]
Happy to say this feature is now in `master` and will be published in the next release. 
Thanks to @mckernanin for feature request and @butchmarshall for the PR. ❤️
