### ISSUE TITLE
Creating a custom hook causes infinite re-render

### ISSUE THREAD

**Issue by EdmundMai** [iamhosseindhv/notistack#420]
## Expected Behavior
I expect my custom hook for useSnackbar to not cause an infinite loop when used inside useEffect's array of dependencies

## Current Behavior
Every time I comment in my custom `showErrorSnackbar` method in my useEffect dependency array, it causes useEffect to run an infinite amount of times

It looks like the infinite loop is avoided if I only call my hook from 1 place: either inside useEffect OR outside of useEffect. If I try to use it in both, it will cause an infinite loop

## Steps to Reproduce

Comment in line 30
https://codesandbox.io/s/currying-browser-5vomm?file=/src/MyComponent.js

## Context
I'm trying to use my custom hook for useSnackbar inside of useEffect so that the snackbar shows (or doesn't show) based on a param in the URL.

## Your Environment
    "notistack": "1.0.10",

**Comment by iamhosseindhv** [comment]
Not sure if this is intentional or an accident, but `useSnackbar.js` and `useCustomHook.js` files are both empty in your reproduction example. Without looking at the code to see what they're doing, I can't make any comments.

**Comment by EdmundMai** [comment]
@iamhosseindhv Sorry about that! Updated the link: https://codesandbox.io/s/currying-browser-5vomm?file=/src/MyComponent.js

**Comment by EdmundMai** [comment]
Figured, it out: https://stackoverflow.com/questions/68855058/react-infinite-loop-when-using-custom-hook-inside-of-useeffect?noredirect=1#comment121759043_68855058
