### ISSUE TITLE
On mobile, snack bar doesn't close once it's tapped

### ISSUE THREAD

**Issue by fabyeah** [iamhosseindhv/notistack#422]
## Expected Behavior
Tapping on a snack bar should not affect the snack bar closing behavior/timer in any way.

## Current Behavior
On mobile (tested with chrome on android), when you tap a snack bar, it won't automatically go away until you tap somewhere on the page. This has irritated my users, as for error snack bars they usually try to swipe them away (not implemented yet) and when that doesn't work they would tap on the X icon on the left of the snack bar. This tap then keeps the snack bar open forever and any scrolling through the page won't close it until the user changes the page or single taps somewhere else.

## Steps to Reproduce

1. Go to https://iamhosseindhv.com/notistack/demos#variants on your mobile (tested on chrome, android)
2. open a snack bar
3. tap on it
4. wait forever

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.6 (but happens on demo page, too)  |
| React        | 17.0.2 |
| Browser      |  Chrome  |
| OS         | Android  |

**Comment by iamhosseindhv** [comment]
Closing as this issue hasn't received enough/any upvotes
