### ISSUE TITLE
no support for Material UI v5

### ISSUE THREAD

**Issue by christineschuller** [iamhosseindhv/notistack#425]
![Screenshot 2021-09-07 at 09 59 20](https://user-images.githubusercontent.com/48961728/132307289-8920483e-d684-4b2c-9dc6-71773e948539.png)

No support for MUI v5

## Expected Behavior

The page should open without problems, because there is no imported withStyles from the wrong source.

## Current Behavior

 I get the error message from the screenshot above.

## Steps to Reproduce

 With every project which uses the new MUI v5.

Link:

1. https://next.material-ui.com/guides/migration-v4/#material-ui-core-styles
2.
3.
4.

## Context

I want to stack snackbars.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | ^1.0.10 |
| React        |     ^17.0.2    |
| Browser      |         |
| MUI      |   5 beta      |

**Comment by Avyiel** [comment]
Check #421

**Comment by iamhosseindhv** [comment]
You download `npm i notistack@next` to use a version compatible with MUI v5 beta. If you're using MUI v5-rc, you'll have to wait for #423  to merge first.
