### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by aress31** [iamhosseindhv/notistack#427]
`Material UI` supports `dark` and `light` background colors variant for `success, warning, etc` out of the box, could the library be improved in a way that the `SnackbarProvider` has to be wrapped inside the `ThemeProvider` and will automatically read the theme colours rather than hardcoding them, because so far it does not seem to me that there is a support for `dark/light` mode.

**Comment by iamhosseindhv** [comment]
As per my comment https://github.com/iamhosseindhv/notistack/pull/429#issuecomment-927327383
