### ISSUE TITLE
Upgrade to MUI v5

### ISSUE THREAD

**Issue by chasoft** [iamhosseindhv/notistack#430]
Hi,

I'm looking for an upgrade for MUI v5. I've just upgraded my project and it showed

```
error - ./node_modules/notistack/dist/notistack.esm.js:4:0
Module not found: Can't resolve '@material-ui/core/Slide'
```

Does notistack has any plan to upgrade? Thank!

**Comment by chasoft** [comment]
Just replaced with https://www.npmjs.com/package/notistack/v/2.0.1-alpha.5

problem solved!

**Comment by iamhosseindhv** [comment]
I should use `npm i notistack@next` and not alpha. Alpha is v2 version of notistack. `next` is compatible with MUI v5

**Comment by kkaplita** [comment]
> I should use `npm i notistack@next` and not alpha. Alpha is v2 version of notistack. `next` is compatible with MUI v5

In dev mode notistack works... but in production build (dist folder) imports are still wrong.
