### ISSUE TITLE
Support for MUI v5

### ISSUE THREAD

**Issue by kkaplita** [iamhosseindhv/notistack#431]
In stable version of MUI v5.0.0 snackbars not woking. You are using imports with `@material-ui` instead `@mui`

**Comment by Herobone** [comment]
If you have a look in the next branch, you can see that they are aware of this issue and working on it

**Comment by iamhosseindhv** [comment]
As mentioned before, you can use a compatible version of notistack with MUI v5 by `npm i notistack@next`.

**Comment by kkaplita** [comment]
> As mentioned before, you can use a compatible version of notistack with MUI v5 by `npm i notistack@next`. Now that MUI v5 is the stable release, I'll be moving this into master so that it can be downloaded by `npm i notsitack@latest`

In dev mode notistack works... but in production build (dist folder) imports are still wrong.

**Comment by iamchathu** [comment]
@iamhosseindhv can we use latest with mui v5 now?

**Comment by iamhosseindhv** [comment]
@iamchathu Yes. You can download the latest version (`v2.0.2`) which is compatible with v5.
