### ISSUE TITLE
closeSnackbar() doesn't work when transitionDuration option has the appear property

### ISSUE THREAD

**Issue by LarryRyan0824** [iamhosseindhv/notistack#433]
When calling closeSnackbar() with the key used for the notification, and you are using the transitionDuration with the appear property, closeSnackbar() doesn't work during the appear transition state.

## Expected Behavior
Notistack should stop the appear animation, and close the notification.

## Steps to Reproduce
If you setup your options like: 
`transitionDuration: { enter: 325, appear: 3000, exit: 195 }`,
the closeSnackbar() will not work during the appear part of the transition. If you make it 10_000, it won't work for that 10 seconds. If you remove "appear: 3000", it will work. Also if you make the "exit" prop like 5000, and test it, you can call closeSnackbar() while mid-animation.

| Tech         | Version |
|--------------|---------|
| Notistack |  v1.0.10  |
| React         |v17.0.2 |
| Browser      |  ALL |

**Comment by iamhosseindhv** [comment]
Sorry for the tardy response. I can only help with a reproduction example
