### ISSUE TITLE
Version chaos

### ISSUE THREAD

**Issue by trickreich** [iamhosseindhv/notistack#438]
![image](https://user-images.githubusercontent.com/16644200/134877534-d566a45a-dae8-43f6-90c6-6d2551a01a3a.png)

This is really confusing at the moment..
Can you pls give an overview for the versions?

**Comment by iamhosseindhv** [comment]
* Version 1s up to `v1.0.10` supports material v4.
* Those with `next` tag (e.g. `1.0.6-next.3`) supported material v5 (while it was in alpha/beta/rc stage).
* Now that material v5 is the stable release, notistack v2 (i.e. `v2.0.2`) is out, which is exactly the same code as 1.0.6-next.3, but published as `latest`.


I appreciate there's room for confusion, but the only thing people need to know is [what's in the README](https://github.com/iamhosseindhv/notistack#getting-started):

> Use your preferred package manager:
```
npm install notistack
yarn add notistack
```
> If you're using Material-UI version 4.x.x or lower, download a compatible version of notistack using:
```
npm install notistack@latest-mui-v4
yarn add notistack@latest-mui-v4
```

Once more people download `latest`, I might remove `next` tag so it becomes less confusing.

**Comment by trickreich** [comment]
Thanks for the quick response!
It was just confusing that the first Version of 2 was 2.0.2
