### ISSUE TITLE
Variant overriding doesn't work with SnackProvider

### ISSUE THREAD

**Issue by h0tw4t3r** [iamhosseindhv/notistack#440]
## Expected Behavior

```jsx
<SnackProvider classes={{ variantSuccess: myStyledClass }}>...</SnackProvider>
```
This should override the success variant, it worked before the transition to mui5
## Current Behavior

It just doesn't add the overriden class to `Snackbar-Item`.

## Steps to Reproduce

Link: https://codesandbox.io/s/crazy-glade-60o24?file=/App.js

Just try to override it, nothing else

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.2  |
| React        |     17    |
| Browser      |    Any     |

**Comment by sm3sher** [comment]
I can confirm that this is not working since [v2.0.2](https://github.com/iamhosseindhv/notistack/releases/tag/v2.0.2)

**Comment by sm3sher** [comment]
A temporary dirty fix would be to override the classes (`SnackbarItem-variantSuccess`, `.SnackbarItem-variantError`, ...) in your css.

**Comment by tkmin** [comment]
@sm3sher could you give me example of how to override with css, please?
I'm having exact same problem right now..

**Comment by sm3sher** [comment]
@tkmin basically I've added this to my App.css
```css
.SnackbarItem-variantSuccess {
  background-color: #409944 !important;
}
```
Warning, error and info can be styled the same way.

**Comment by tkmin** [comment]
> @tkmin basically I've added this to my App.css
> 
> ```css
> .SnackbarItem-variantSuccess {
>   background-color: #409944 !important;
> }
> ```
> 
> Warning, error and info can be styled the same way.

Thank you, you saved my day~!
I was using version 1.x.x
updated to ^2.0.2,
problem resolved.

**Comment by sm3sher** [comment]
You're welcome, it's still just a hotfix.
Waiting for an actual solution.

**Comment by iamhosseindhv** [comment]
Fix is published as `v2.0.3` (latest). You should be able to do either of option 1 or 2 from below to achieve what you need @h0tw4t3r.

Thanks for sharing your solution @joshrathke. I'm aware what the root of the question was here, was more trying to help Pantelis find the answer to their question.

You have the following options to override variant styles. Let me know if you're having any issues.

#### Option 1 - styled - [codesandbox](https://codesandbox.io/s/quirky-mayer-yu96m?file=/App.js)
```jsx
import { SnackbarProvider } from "notistack";
import { styled } from "@mui/material";

const StyledSnackbarProvider = styled(SnackbarProvider)`
  &.SnackbarItem-variantSuccess {
    background-color: orange;
  }
`;

export default () => {
  return (
    <StyledSnackbarProvider>
      <MyApp />
    </StyledSnackbarProvider>
  );
};
```

#### Option 2 - makeStyles
```jsx
import { SnackbarProvider } from 'notistack';
import { makeStyles } from "@mui/styles";

const useStyles = makeStyles({
  overriddenError: {
    backgroundColor: "blue !important", // <-- note !important
  }
});


export default () => {
  const classes = useStyles();
  return (
    <SnackbarProvider
        classes={{
            variantError: classes.overriddenError,
        }}
    >
      <MyApp />
    </SnackbarProvider>
  );
};

```


#### Option 3 - notistack v3 (alpha)

Download notistack v3 using `npm i notistack@alpha` (in alpha) which gives you full control. Instead of trying to override styles, you make your own snackbars. Here's an example: https://codesandbox.io/s/pedantic-shaw-y3nis
Take a look at `ThemeResponsiveSnackbar.tsx` and change the styles as you wish.

On v3, you can also define custom variants:

```tsx
<SnackbarProvider
    Components={{
        success: MyCustomSuccessNotification,
        reportComplete: ReportComplete,
    }}
>
</SnackbarProvider>

interface ReportCompleteProps extends CustomContentProps {
    allowDownload: boolean;
}

const ReportComplete = React.forwardRef((props: ReportCompleteProps, ref) => {
    const {
        // You have access to notistack props, options 👇🏼
        variant,
        message
        // as well as your own custom props 👇🏼
        allowDownload,
    } = props;

    // 
})

enqueueSnackbar('Your report is ready to download', {
   variant: 'reportComplete',
   persist: true,
   allowDownload: true, // <-- pass any additional options
})
```

**Comment by pantelispanayiotou** [comment]
> Option 1 - styled - [codesandbox](https://codesandbox.io/s/quirky-mayer-yu96m?file=/App.js)

Thank you for the examples. However this example works only for the variants. What i am trying to achieve is control the paddings of SnackbarContainer-top or SnackbarContainer-bottom and this is not working.

**Comment by iamhosseindhv** [comment]
It's not possible to use `styled(SnackbarProvider)` to override SnackbarContainer styles. This is a limitation, otherwise I would've published a fix.  You're left with option 2,3 or to use global css styles.
