### ISSUE TITLE
Snacks whose 'persist' prop is true, does not go away on route change

### ISSUE THREAD

**Issue by alivtar** [iamhosseindhv/notistack#441]
## Expected Behavior
The snacks that are marked as `persist: true` should go away on change of route.

## Current Behavior
snacks that are marked as `persist: true` do not go away on change of route.

## Your Environment
|--------------|---------|
| Notistack | v1.0.9  |
| React        | 17.0.2  |
| Browser      | chrome |

**Comment by iamhosseindhv** [comment]
Hey @alivtar, there's no way for notistack to know route has changed, also it may not be the desired behaviour for other users. You can close snackbars on route change yourself. See [Dismiss programmatically](https://iamhosseindhv.com/notistack/demos#dismiss-programmatically) section of the docs.
