### ISSUE TITLE
Show a countdown in message

### ISSUE THREAD

**Issue by freelanx** [iamhosseindhv/notistack#443]
I am not sure if I can ask this here because is more a question or request rather then an issue, but if not please delete it.

We just reach to notistack looking for a solution and it looks like a great tool for us. But we miss one thing that will be very useful for us.

We will like to implement a countdown, in some of our error messages (toast), i.e. "There was an error with the connection. We will retry in X seconds."
We are beginners using React and we try to do this with other options (no notistack) using own states with useEffect and it can become a bit complicate to do this stackable.

So, we discover notistack, that solves the majority of our problems but we are unable to solve this. We navigate trough the props, but with no luck. 

Is there an "esay" way to use a timer inside the message or make message dynamic for the same toast?

**Comment by iamhosseindhv** [comment]
Sorry for the tardy response. Is this something you're still interested in? Let me know and we can figure out a way to achieve what you want.

**Comment by aress31** [comment]
@iamhosseindhv, this is something I am interested in and that would work nicely with the `undo` example for `actions` in the doc at https://notistack.com/features/basic.

For instance an action with the backend that can be aborted/undone in the next 10 seconds, I would want to show a countdown next to the action to feedback users on how long they have to revert the action.
