### ISSUE TITLE
I want to intercept the error of axios, but it can't work properly

### ISSUE THREAD

**Issue by BaiShaojie123123** [iamhosseindhv/notistack#445]
## Expected Behavior

`react axio axiosInstance.interceptors.response.use((error)=>{
 const { enqueueSnackbar } = useSnackbar()
        enqueueSnackbar(error.msg)
})`

`import {SnackbarProvider} from 'notistack';
ReactDOM.render(<SnackbarProvider><App /></SnackbarProvider>, document.getElementById('root'))`

## Current Behavior

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:14906)
    at useContext (react.development.js:1504)
    at useSnackbar (useSnackbar.ts:5)
    at axios.js:49
## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.2  |
| React        |      17.0.2   |
| Browser      |   chrome      |
| react-dom|     17.0.2    |
| material|     5.0.3   |

**Comment by iamhosseindhv** [comment]
As suggested by the error message, you can't use any hooks (including `useSnackbar`) outside of a functional component. Refer to #30 so find a solution which allows you to call `enqueueSnackbar` in places like axios interceptor.
