### ISSUE TITLE
Add relevant props to snackbar action

### ISSUE THREAD

**Issue by kykungz** [iamhosseindhv/notistack#446]
My goal is to customize the snackbar's `action` so that it can behave conditionally according to the passed snackbar options.

Example:
```tsx
<SnackbarProvider
  action={(key, options) =>
    options.variant === 'success' ? (
      <div>success only action</div>
    ) : (
      <div>normal action</div>
    )
  }
>
  {children}
</SnackbarProvider>
```

## Expected Behavior

Customize snackbar's `action` according to its options such as `variant` or `autoHideDuration`

## Current Behavior

Snackbar's `action` cannot be conditionally rendered by any options. `action` function props only provide the `key` value.

## Context

I'm having a problem when trying to add a dismiss button to all snackbars. As the `"default"` variant has a black background in light mode, and white background on dark mode, I have to adjust the dismiss icon color to show correctly in each theme mode.

```tsx
<SnackbarProvider
  ref={notistackRef}
  action={(key, options) => (
    <IconButton
      // Render icon color according to MUI theme
      sx={{ color: theme => theme.palette.mode === 'light' ? 'white' : 'black' }}
      size="small"
      onClick={onClickDismiss(key)}
    >
      <CloseIcon fontSize="small" />
    </IconButton>
  )}
>
  {children}
</SnackbarProvider>
```

However, in dark mode, only the `"default"` variant has its background changed (from black to white), other variants such as `"success"` or `"info"` still use the same background color.

![Screen Shot 2564-10-15 at 17 25 48](https://user-images.githubusercontent.com/9304909/137473382-2f5bdb7e-91a8-431c-ac47-e9619e06ff6b.png)

Resulting in `"success"` variant having a black dismiss button on dark mode, which is unusual.

![Screen Shot 2564-10-15 at 17 25 36](https://user-images.githubusercontent.com/9304909/137473401-52df0a73-a619-44d2-b875-5bb1154e3945.png)

My goal is to only adjust the dismiss button color of the `"default"` variant in dark mode. Thus, `options` should also be passed to the `action` function, so that users can customize its styles accordingly.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.2  |
| React        |   v17.0.2      |
| Browser      |    Chrome v94.0.4606.81     |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
I agree with you both, and I've been working to bring this to life.
Closing due to being dup of #242
