### ISSUE TITLE
React Unique key prop warning

### ISSUE THREAD

**Issue by aburomaissae** [iamhosseindhv/notistack#45]
I'm getting this warning with notistack where it complains about the key prop missing 
`Warning: Each child in an array or iterator should have a unique "key" prop.`
I tried to add it in options with 
`                                  this.props.enqueueSnackbar('Done', 
                                    { 
                                      variant: 'success',
                                      key: 'random-string',
                                    }
`
but the key from options is not used

**Comment by iamhosseindhv** [comment]
You should omit the key option. Notistack handles passing unique keys for snackbars.

**Comment by aburomaissae** [comment]
Thank you for your prompt answer

at first I did not put any key and the warning was fired
what I meant by putting it is that I tried to work around this issue

**Comment by iamhosseindhv** [comment]
@aburomaissae. If you're still facing this issue please provide a sandbox and I'll try to help. 

You can start from [here](https://codesandbox.io/s/github/iamhosseindhv/notistack/tree/master/examples/simple-example??hidenavigation=1&module=%2FApp.js). How do you make sure that the warning is coming from notistack?

**Comment by Maaartinus** [comment]
Maybe this helps someone. I faced the same problem and it was caused by me using
```
<SnackbarProvider maxSnack={7} action={[button]}>
        <MyThing/>
</SnackbarProvider>
```
where the single element array was the culprit. It most probably comes from https://material-ui.com/demos/snackbars/#customized-snackbars,

Using just `action={button}` solves it.

**Comment by larissa-n** [comment]
Thank you @Maaartinus, that fixed it!
@iamhosseindhv : maybe it would help to update [https://iamhosseindhv.com/notistack#action-for-all-snackbars](https://iamhosseindhv.com/notistack#action-for-all-snackbars) (which still has the single element array).
Thank you!

**Comment by iamhosseindhv** [comment]
@larissa-n Thanks. Docs have been [updated](https://iamhosseindhv.com/notistack#action-for-all-snackbars).
