### ISSUE TITLE
Closing a persisted message does not clear the persist flag

### ISSUE THREAD

**Issue by RALifeCoach** [iamhosseindhv/notistack#453]
I enqueue 1 message with persist true. I close the message using closeSnackbar(key) in my action method.

I enqueue another message and close it, several times.

I start seeing the following message:
**WARNING - notistack: Reached maxSnack while all enqueued snackbars have 'persist' flag. Notistack will dismiss the oldest snackbar anyway to allow other ones in the queue to be presented.**

**Comment by iamhosseindhv** [comment]
Closing as this issue hasn't received any upvotes. Thanks for reporting though @RALifeCoach
