### ISSUE TITLE
Typo in SnackbarItem.tsx

### ISSUE THREAD

**Issue by LR-Coop** [iamhosseindhv/notistack#454]
Hello!

I haven't seen this cause issues, but there is a typo in SnacbkarItem.tsx. 

![image](https://user-images.githubusercontent.com/63616094/140378962-76e07f25-7252-47a4-9a23-a9e76c573463.png)

Line 113 should be INSTRUCTED.

**Comment by saeedhemmati** [comment]
@LR-Coop 

Thanks for your feedback, it's fixed in PR #455.

**Comment by LR-Coop** [comment]
@saeedhemmati thank you!
