### ISSUE TITLE
Updating snackbar content and actions

### ISSUE THREAD

**Issue by simplenotezy** [iamhosseindhv/notistack#456]
Is there a way to provide updates to the notification, after it has been issued, without having to issue a new notification?

Say I wish to change a notification message after it is shown.

Currently I persist a notification and I wish to change the content.

Is this done with portal, or is there another smart way?

Let me know if this is specific enough, or if you need more info.

**Comment by communityFabian** [comment]
Would be also interested in an option to edit the content of an already enqueued snackbar with an existing key.

**Comment by iamhosseindhv** [comment]
Dup #234 

Long story short, it's not possible atm. I also think it's a good feature but I don't have time to implement it as there are other higher priority issues. PR's are always welcome

**Comment by isemilia** [comment]
Any updates on this issue? It's still relevant in 2024
