### ISSUE TITLE
Custom snackbars have no way of receiving variant value

### ISSUE THREAD

**Issue by Jakkc** [iamhosseindhv/notistack#457]
It seems custom snackbars don't have any support for variants at present. Or perhaps I'm missing something.

To get any value from custom snackbar functionality it is absolutely essential that developers can read the variant value, so that we can style our custom snackbar with error, success, warning variants.

**Comment by manelio** [comment]
Agree. This library is awesome, but I think it's a bit "overtyped" at customizing variants. Styles and icons for new variants should be easily customizable, but the code is too tied to having 5 variants: 'default' | 'error' | 'success' | 'warning' | 'info'.

**Comment by lucasNeuhauss** [comment]
Definitely. Here's my hacky solution in the meantime:

```js
// A utility function to reuse throughout the app, anything will do
const addNotification = useCallback(
    (args) => {
      const {message, variant, ...snackbarOptions} = args;

      // One way of passing the variant variable up to the custom component
      return enqueueSnackbar(`${variant}-${message}`, { 
        variant,
        ...snackbarOptions
      });
    },
    [enqueueSnackbar]
  );
```

```js
<SnackbarProvider
      maxSnack={3}
      content={(key, colorAndMessageString) => {
        const color = colorAndMessageString.split('-')[0];
        const message = colorAndMessageString.split('-')[1];

        return <Alert id={key} color={color}>{message}</Alert>;
      }}
    >
    {children}
</SnackbarProvider>
```

**Comment by Abolfazl2647** [comment]
@Jakkc & @manelio  i created a pull request [here](https://github.com/iamhosseindhv/notistack/pull/464) i hope solve this problem. i am facing this issue too.

**Comment by iamhosseindhv** [comment]
@manelio Have you tried notistack v3 downloadable by `npm i notistack@alpha`? I think it perfectly addresses your need. Read the [migration guide here](https://github.com/iamhosseindhv/notistack/blob/545a05b7cf9c67ef2ee0310d3b1b93989914f0f7/MIGRATION.md#8-new-components-prop). Note it's not the stable release.
