### ISSUE TITLE
Return (event, reason) in onClose callback

### ISSUE THREAD

**Issue by zsh1313** [iamhosseindhv/notistack#46]
onClose callback only return (key) at the moment, but it will be very useful if the original (event, reason) are also returned.
The benefits being that passing the (event, reason) in the custom onClose callback is like below

1. knows the exact reason about the closing.
2. The material-ui only has two reasons at the moment, but it could have more reasons in the future
3. With event parameter, we can identify where the notification is from, therefore knows which case is this closing about. Say I have a single global (centra) notification component (say named NOTIFIER) with notistack, any component (say 30 components) in the application may fire a notification through NOTIFIER with their own action. And I may have another global component to post-process when user clicks the notification action. With the event parameter, we can identify the case (or another word which origin component) where this notification was fired.

some discussion has gone through this in [Allow "onClose" and "onExited" callbacks](https://github.com/iamhosseindhv/notistack/pull/21). The changes to the code as mentioned by @iamhosseindhv looks good
```
if (reason === 'clickaway') return;
if (singleOnClose) singleOnClose(event, reason, key);
onClose(event, reason, key);
```
(and event will get passed to onExited callback as well)

**Comment by iamhosseindhv** [comment]
Thanks for opening the issue. This will be in the next release
