### ISSUE TITLE
Lack of release log, updating Notistack deps to Mui5 breaks builds

### ISSUE THREAD

**Issue by IcarusHU** [iamhosseindhv/notistack#460]
Dear developers,

We've updated Notistack from 1.0.10 to 2.x, and due to the lack of release logs, our build broke, took about half a day to find out, what is causing the problem. 
I think you should really add at least a breaking changes comment to your release logs maybe? Would be a bit more practical.

**Comment by iamhosseindhv** [comment]
I agree CHANGELOG should clearly state breaking change for v2. Apologies for the time wasted 👍🏼
