### ISSUE TITLE
Unable to use with material -ui 4.11

### ISSUE THREAD

**Issue by yashaswinibprasad87** [iamhosseindhv/notistack#462]
Help appreciated with an example to use with material ui 4.11,
 as throws an error though mentioned in the documentation that it supports earlier versions

## Steps to Reproduce
yarn add notistack@latest-mui-v4

Error:
Failed to compile.

./node_modules/notistack/dist/notistack.esm.js
Module not found: Can't resolve '@material-ui/core/ClickAwayListener' 

Please provide the fix or solution to work

**Comment by TheSmartHyena** [comment]
I had the same issue, i "solved" it, by removing the TransitionComponent. It's maybe a feature only available with mui-v5.

**Comment by yashaswinibprasad87** [comment]
> I had the same issue, i "solved" it, by removing the TransitionComponent. It's maybe a feature only available with mui-v5.

Can you share the example

**Comment by nhayfield** [comment]
having same issue

**Comment by TheSmartHyena** [comment]
The documentation: 
```javascript
import Slide from '@material-ui/core/Slide';

<SnackbarProvider
    anchorOrigin={{
        vertical: 'bottom',
        horizontal: 'left',
    }}
    TransitionComponent={Slide}
>
    <App />
</SnackbarProvider>


const message = 'Your notification here';
props.enqueueSnackbar(message, {
    anchorOrigin: {
        vertical: 'bottom',
        horizontal: 'left',
    },
    TransitionComponent: Slide,
});
````


How it works for me: 

```javascript
import { SnackbarProvider } from 'notistack';

<SnackbarProvider
    maxSnack={3}
    anchorOrigin={{
        vertical: 'bottom',
        horizontal: 'left',
    }}
>
    ...
</SnackbarProvider>
```

```javascript
import { useSnackbar } from 'notistack';
...
const { enqueueSnackbar } = useSnackbar();

enqueueSnackbar(translate('success.uploadDocument'), {
     variant: 'success',
});
```


without this line => ```javascript     TransitionComponent: Slide ```

works fine

**Comment by iamhosseindhv** [comment]
Here's a working codesandbox example https://codesandbox.io/s/affectionate-zhukovsky-rru90

@material-ui/core: 4.12.3
notistack: "1.0.10

Please provide a reproduction if you believe this issue is not resolved
