### ISSUE TITLE
Provide example code for redux-toolkit integration

### ISSUE THREAD

**Issue by Big-Zude** [iamhosseindhv/notistack#463]
Was reading the docs and only redux/mobx examples are available. When you visit the official redux docs it says and I quote "Redux Toolkit is our official recommended approach for writing Redux logic. It wraps around the Redux core and contains packages and functions that we think are essential for building a Redux app. Redux Toolkit builds in our suggested best practices, simplifies most Redux tasks, prevents common mistakes, and makes it easier to write Redux applications."

I suggest a redux-toolkit example to be added to notistack docs as it can greatly help different developers including myself who is currently having difficulties implementing notistack in a typescript+redux-toolkit project. 

Any suggestions of how to implement this are most welcome

**Comment by iamhosseindhv** [comment]
Hey @Big-Zude , what difficulty are you having integrating notistack with your react project? An example scenario preferably with code samples is appreciated
