### ISSUE TITLE
Add support for `variant` in the `content` callback

### ISSUE THREAD

**Issue by alettieri** [iamhosseindhv/notistack#467]
It would be nice if we could receive the `variant` in the content callback, that way the consuming component has the ability to display the proper content type based on the variant. 

See PR: #466

**Comment by iamhosseindhv** [comment]
Dup #457. 
Hey @alettieri,

Have you tried notistack v3 downloadable by `npm i notistack@alpha`? I think it perfectly addresses your need. Read the [migration guide here](https://github.com/iamhosseindhv/notistack/blob/545a05b7cf9c67ef2ee0310d3b1b93989914f0f7/MIGRATION.md#8-new-components-prop). Note that it's not a stable release yet.

**Comment by alettieri** [comment]
> Dup #457. Hey @alettieri,
> 
> Have you tried notistack v3 downloadable by `npm i notistack@alpha`? I think it perfectly addresses your need. Read the [migration guide here](https://github.com/iamhosseindhv/notistack/blob/545a05b7cf9c67ef2ee0310d3b1b93989914f0f7/MIGRATION.md#8-new-components-prop). Note that it's not a stable release yet.

Thanks @iamhosseindhv I haven't tried it, didn't realize it existed. Great to see that progress is being made toward supporting something like this. How long before this change becomes release ready?
