### ISSUE TITLE
How I change the alert icon from enqueueSnackbar

### ISSUE THREAD

**Issue by bylly1** [iamhosseindhv/notistack#469]
I want to change alert icon without add extra props to `SnackbarProvider`

This is my code

``` js
 #####  SnackbarUtilsConfigurator.js
export const SnackbarUtilsConfigurator = () => {
 useSnackbarRef = useSnackbar();
 return null;
}

export const snackbarActions = {
 toast(msg, variant='default') {
  useSnackbarRef.enqueueSnackbar(msg, variant);
 }
}

```

``` js
###### index.js
<SnackbarProvider>
  <SnackbarUtilsConfigurator />
  <App />
</SnackbarProvider>
```

From the component i want to change error alert Icon

``` js
if(error === 500){
  snackbarActions.toast(
  "Error 500",
  {
   variant: 'error',
   anchorOrigin: {
     variant: 'bottom',
     horizontal: 'left
   },
   icon: ... I want to add something like this
 )
}

```

**Comment by TkaczykAdam** [comment]
[bump] I fully agree, my project has the same problem

**Comment by iamhosseindhv** [comment]
Have you tried notistack v3 downloadable by `npm i notistack@alpha`? You should be able to achieve this by creating a custom snackbar. Read the [migration guide here](https://github.com/iamhosseindhv/notistack/blob/545a05b7cf9c67ef2ee0310d3b1b93989914f0f7/MIGRATION.md#8-new-components-prop).

You should be able to create your own snackbar and have access to all the props. Let me know if the guide above is not clear.
