### ISSUE TITLE
Do really default notistack's styles are nested in current version (2.0.3)?

### ISSUE THREAD

**Issue by robert-orlinski** [iamhosseindhv/notistack#470]
Hi!

First thing: thank you for the great work, done while making notistack library. I am glad for all of this!

Second: I know, I am not using the template dedicated to bug issues but I feel that the topic I want to write about is not strictly related to any bug but to the way in which the library is written.

---

Going down to business. The thing is, that all default styles which snackbars provided by `notistack` are based on, are nested under the root element - this is visible in styles defined in: `src/SnackbarItem/SnackbarItem.tsx` for instance:

```jsx
// ...
[`&.${classes.wrappedRoot}`]: {
    position: 'relative',
    transform: 'translateX(0)',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
},
[`.${classes.contentRoot}`]: {
    ...theme.typography.body2,
    backgroundColor,
    color: theme.palette.getContrastText(backgroundColor),
    alignItems: 'center',
    padding: '6px 16px',
    borderRadius: '4px',
    boxShadow:
        '0px 3px 5px -1px rgba(0,0,0,0.2),0px 6px 10px 0px rgba(0,0,0,0.14),0px 1px 18px 0px rgba(0,0,0,0.12)',
},
// ...
```

Because of this (if I am right) there is no way to override those styles using custom classes if we don't mirror this nesting (for example we will write `variantSuccess` class like `successClass { '$snackbarRoot &': { foo: 'bar' } }` - this one is syntax is from MUI `createStyles()` function) or use `!important` - both those solutions are not good nor comftable.

Do I do something wrong or this is just like this and in this version I have to define custom styles like this (as I saw in version 3 there are [plans to implement different styling solution](https://github.com/iamhosseindhv/notistack/issues/421))?

Thank you in advance for all answers!

**Comment by iamhosseindhv** [comment]
I'm sure you've done a great job explaining, but it's still not quite clear what you're trying to achieve. How would you expect to override styles in an ideal world? Could you write a code snippet of that?
