### ISSUE TITLE
Does notistack require @mui/material?

### ISSUE THREAD

**Issue by VincentThomas06** [iamhosseindhv/notistack#471]
## Expected Behavior
 >That notistack should display the "notistack-component" in the bottom left.

## Current Behavior

    I get an error saying that "@mui/material/ClickAwaylistener" is not found

Whole error:
```
ERROR in ../../../node_modules/notistack/dist/notistack.esm.js 4:0-40
Module not found: Error: Can't resolve '@mui/material/Slide' in 'C:\Users\vincent\projects\projects\node_modules\notistack\dist'

ERROR in ../../../node_modules/notistack/dist/notistack.esm.js 5:0-57
Module not found: Error: Can't resolve '@mui/material/styles' in 'C:\Users\vincent\projects\projects\node_modules\notistack\dist'

ERROR in ../../../node_modules/notistack/dist/notistack.esm.js 6:0-46
Module not found: Error: Can't resolve '@mui/material/Collapse' in 'C:\Users\vincent\projects\projects\node_modules\notistack\dist'

ERROR in ../../../node_modules/notistack/dist/notistack.esm.js 7:0-44
Module not found: Error: Can't resolve '@mui/material/SvgIcon' in 'C:\Users\vincent\projects\projects\node_modules\notistack\dist'

ERROR in ../../../node_modules/notistack/dist/notistack.esm.js 8:0-64
Module not found: Error: Can't resolve '@mui/material/ClickAwayListener' in 'C:\Users\vincent\projects\projects\node_modules\notistack\dist'

```

## Steps to Reproduce

Just check this codesandbox link out!

Link:

1. https://codesandbox.io/s/twilight-glitter-hokoy?file=/src/App.tsx

## Context
I'm just trying to get it to work with my project and if you guys require @mui/material, in my opinion its a bit wierd because its quite a big component library. Why do you guys want to use it for just a snackbar? Am i missing something?

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.3  |
| React        |  v17.0.2       |
| Browser      |  brave / chrome / firefox       |

**Comment by iamhosseindhv** [comment]
Hey @VincentThomas06 , this library initially started to provide additional functionality to material-ui's Snackbar component, and it has been like that for a while. Hence why `mui` is a `peerDependency` of this project.

But you don't have to use MUI along with notistack. You can download notistack v3 `npm i notistack@alpha` without the need to have mui installed. I'm a bit busy with moving houses but I will be publishing a stable release of v3 quite soon.

Let me know if you have any further questions.

**Comment by VincentThomas06** [comment]
> Hey @VincentThomas06 , this library initially started to provide additional functionality to material-ui's Snackbar component, and it has been like that for a while. Hence why `mui` is a `peerDependency` of this project.
> 
> But you don't have to use MUI along with notistack. You can download notistack v3 `npm i notistack@alpha` without the need to have mui installed. I'm a bit busy with moving houses but I will be publishing a stable release of v3 quite soon.
> 
> Let me know if you have any further questions.

Ok, i understand now. One question though. Is the alpha version as 'good' as the material version? What i mean is, will i miss out on anything in the alpha version?
