### ISSUE TITLE
index.d.ts file minor update for mui v5

### ISSUE THREAD

**Issue by neporshiso** [iamhosseindhv/notistack#473]
Hey Hossein -

Inside the index.d.ts file for notistack, the Transition Component type in the SnackbarProps interface is currently, TransitionComponent?: React.ComponentType<TransitionProps>.

However, in material-ui v5, https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Snackbar/Snackbar.d.ts#L100-L102, it's TransitionComponent?: React.JSXElementConstructor<TransitionProps & { children: React.ReactElement<any, any> }>.

Could this be updated to TransitionComponent?: React.ComponentType<TransitionProps> | React.JSXElementConstructor<TransitionProps & { children: React.ReactElement<any, any> }>;

for compatibility with mui v4 and mui v5 projects?

**Comment by iamhosseindhv** [comment]
Nice job @neporshiso I'll get this published asap

**Comment by cgarrovillo** [comment]
Is this merged yet?

**Comment by iamhosseindhv** [comment]
This issue is fixed in #474 and published as `npm i notistack@2.0.5`

**Comment by iamhosseindhv** [comment]
This issue is fixed in #474 and published as `npm i notistack@2.0.5`
