### ISSUE TITLE
Update docs to emphasise how TransitionComponent: Grow works with custom snackbar

### ISSUE THREAD

**Issue by alextompkins** [iamhosseindhv/notistack#475]
This occurs when you use the `TransitionComponent` and `content` paramaters at the same time. When using the standard notistack snackbars, you can customise the transition animation by providing `TransitionComponent`. However this doesn't work properly when you also provide a custom snackbar via `content`.

## Expected Behavior
The provided `TransitionComponent` applies correctly to the custom snackbar content and is the _only_ Transition in its Virtual DOM hierarchy. 

## Current Behavior
The default `Collapse` transition is used instead, and the transition provided to `TransitionComponent` is also nested further underneath it in the hierarchy, like so:
![image](https://user-images.githubusercontent.com/18250951/154167429-2463c9f8-6375-41db-be26-78111cccedbe.png)

## Steps to Reproduce
Link: https://codesandbox.io/s/notistack-transitioncomponent-not-working-with-custom-snackbar-content-p53m6f?file=/SnackbarConsumer.tsx

## Context
I need to customise the snackbar content to fit a certain design. In particular, the text of the message must be center-aligned within the entire snackbar, which is not currently possible using styles applied to the snackbar root. There doesn't seem to be any way to style the message or action containers via the `classes` prop either (you can only style `root`). Therefore I decided to just use a custom snackbar content, but having a fade transition is also a required part of the design. 

## Your Environment
| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.10 |
| React        | 17.0.2 |
| Browser      | Firefox |

**Comment by alextompkins** [comment]
Heads up for anyone else with the same problem, I've figured it out. As mentioned in the MUI docs, the child element of a <Transition> (in this case the custom content) must have a `style` prop that it forwards to the inner DOM element. 

See https://mui.com/components/transitions/#child-requirement

Perhaps there could be some more documentation about this in the section on custom snackbar content?

**Comment by iamhosseindhv** [comment]
Nice catch. I have been a victim of missing that part of MUI docs myself. I'll keep the issue open until I update the relevant parts of the [documentation website](https://iamhosseindhv.com/notistack)

**Comment by EricJin9012** [comment]
Same here too.
Any solution yet?

**Comment by andyngdz** [comment]
For who is facing this issue by using the `content` prop. This is how I fix it, in your custom component, you need to extract the `style` and assign it to the first element. The `style` is passed down by the `Grow` component


This is my custom component:

```
// MyCustomComponent.tsx
....

const { style, ....yourRestProps } = props;

return <div style={style}>...</div>
```

This is my SnackbarProvider looks like:

```
<SnackbarProvider
  domRoot={document.body}
  content={key => <MyCustomComponent key={key} id={key} />}
  TransitionComponent={Grow as React.ComponentType}
  preventDuplicate
  disableWindowBlurListener
>
  {children}
</SnackbarProvider>
```

**Comment by andyngdz** [comment]
For who is facing this issue by using the `content` prop. This is how I fix it, in your custom component, you need to extract the `style` and assign it to the first element. The `style` is passed down by the `Grow` component


This is my custom component:

```
// MyCustomComponent.tsx
....

const { style, ....yourRestProps } = props;

return <div style={style}>...</div>
```

This is my SnackbarProvider:

```
<SnackbarProvider
  domRoot={document.body}
  content={key => <MyCustomComponent key={key} id={key} />}
  TransitionComponent={Grow as React.ComponentType}
  preventDuplicate
  disableWindowBlurListener
>
  {children}
</SnackbarProvider>
```

**Comment by iamhosseindhv** [comment]
This has been added to the documentation website under [child-requirements](https://notistack.com/v2.x/examples/advanced/custom-component#child-requirements)
