### ISSUE TITLE
use custom mui5 Alert component as default

### ISSUE THREAD

**Issue by hbinkle** [iamhosseindhv/notistack#477]
Currently a custom component `SnackbarItem` is used by default.
That custom component does not regard the mui theme palette colors like `theme.palette.warning` etc.
There is now the `<Alert/>` from mui which properly uses th mui theme: https://mui.com/components/alert/

## Expected Behavior
use the `<Alert/>` from mui instead of a custom `SnackbarItem`

## Current Behavior
custom `SnackbarItem` with hard coded colors which can't properly by adjusted by mui theming mechanisms

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.3  |
| React        |v17.0.2 |
| Mui       |v5.4.0   |

**Comment by iamhosseindhv** [comment]
Hi @hbinkle , not re-using mui Alert component is intentional. Although you can customise your snackbars to use `<Alert/>` by default. Let me know if you're having issues achieving that.

**Comment by hbinkle** [comment]
@iamhosseindhv , thanks for your reply.
We came across the new Components feature in the alpha version and decided to use that one as very easy solution:
```typescript
import { Alert, AlertColor } from '@mui/material';
import { SnackbarProvider, CustomContentProps, SnackbarKey } from 'notistack';
import React from 'react';
import { forwardRef, ReactNode } from 'react';

type CloseSnackbarAction = (key?: SnackbarKey) => void;

const ThemeResponsiveSnackbarComp = forwardRef<HTMLDivElement, CustomContentProps & { component: React.ReactNode }>(
  (props, forwardedRef) => {
    const { message, variant, component, persist, action } = props;
    const closeAction = action as CloseSnackbarAction;
    return (
      <Alert ref={forwardedRef} severity={variant as AlertColor} onClose={persist ? () => closeAction() : undefined}>
        {component ? component : message}
      </Alert>
    );
  },
);

const ThemeResponsiveSnackbar = React.memo(ThemeResponsiveSnackbarComp);

export function Messaging(props: { children: ReactNode }) {
  return (
    <SnackbarProvider
      dense
      hideIconVariant
      preventDuplicate={true}
      maxSnack={2}
      anchorOrigin={{
        horizontal: 'center',
        vertical: 'bottom',
      }}
      Components={{
        info: ThemeResponsiveSnackbar,
        success: ThemeResponsiveSnackbar,
        error: ThemeResponsiveSnackbar,
        warning: ThemeResponsiveSnackbar,
      }}
    >
      {props.children}
    </SnackbarProvider>
  );
}
```

**Comment by jaballogian** [comment]
> @iamhosseindhv , thanks for your reply. We came across the new Components feature in the alpha version and decided to use that one as very easy solution:
> 
> ```ts
> import { Alert, AlertColor } from '@mui/material';
> import { SnackbarProvider, CustomContentProps, SnackbarKey } from 'notistack';
> import React from 'react';
> import { forwardRef, ReactNode } from 'react';
> 
> type CloseSnackbarAction = (key?: SnackbarKey) => void;
> 
> const ThemeResponsiveSnackbarComp = forwardRef<HTMLDivElement, CustomContentProps & { component: React.ReactNode }>(
>   (props, forwardedRef) => {
>     const { message, variant, component, persist, action } = props;
>     const closeAction = action as CloseSnackbarAction;
>     return (
>       <Alert ref={forwardedRef} severity={variant as AlertColor} onClose={persist ? () => closeAction() : undefined}>
>         {component ? component : message}
>       </Alert>
>     );
>   },
> );
> 
> const ThemeResponsiveSnackbar = React.memo(ThemeResponsiveSnackbarComp);
> 
> export function Messaging(props: { children: ReactNode }) {
>   return (
>     <SnackbarProvider
>       dense
>       hideIconVariant
>       preventDuplicate={true}
>       maxSnack={2}
>       anchorOrigin={{
>         horizontal: 'center',
>         vertical: 'bottom',
>       }}
>       Components={{
>         info: ThemeResponsiveSnackbar,
>         success: ThemeResponsiveSnackbar,
>         error: ThemeResponsiveSnackbar,
>         warning: ThemeResponsiveSnackbar,
>       }}
>     >
>       {props.children}
>     </SnackbarProvider>
>   );
> }
> ```
> 
> It works very well. When do you plan to release that alpha?

I use try to use this code but the Alert component does not inherit my custom theme for success, info, warning, and error colors.
My custom theme has different colors but it seems that using this code still produces the same `Alert` background colors from the default MUI theme.
For example, my success color is `#388E3C` but the success Alert component (using this code) still shows the default success color from the MUI theme `#2E7D32`.

**Comment by mikew** [comment]
Just throwing my contender for using mui's `Alert` into the mix:

```tsx
const NotistackMuiAlert = forwardRef<HTMLDivElement, CustomContentProps>(
  (props, forwardedRef) => {
    const {
      id,
      message,
      action: componentOrFunctionAction,
      variant: notistackVariant,
      hideIconVariant,
      style,
      className,
    } = props

    const severity = notistackVariant === 'default' ? 'info' : notistackVariant
    const action =
      typeof componentOrFunctionAction === 'function'
        ? componentOrFunctionAction(id)
        : componentOrFunctionAction

    return (
      <Alert
        ref={forwardedRef}
        severity={severity}
        icon={hideIconVariant ? false : undefined}
        action={action}
        style={style}
        className={className}
        variant="filled"
        sx={(theme) => ({
          boxShadow: theme.shadows[8],
        })}
      >
        {message}
      </Alert>
    )
  },
)

<SnackbarProvider
  Components={{
    default: NotistackMuiAlert,
    info: NotistackMuiAlert,
    success: NotistackMuiAlert,
    error: NotistackMuiAlert,
    warning: NotistackMuiAlert,
  }}
>
  {props.children}
</SnackbarProvider>
```

The difference with the one above:

- "supports" the `default` variant (spoiler: it just uses the `info` severity)
- `action` isn't a simple `onClose`, it's a `ReactNode`
- Doesn't support the extra `component` prop, since `message` is already a `ReactNode`
- You may want to play with the elevation used in `boxShadow`
