### ISSUE TITLE
Two snackbars enqueued before redirect

### ISSUE THREAD

**Issue by JeronimoMendes** [iamhosseindhv/notistack#480]
## Expected Behavior

Should enqueue 1 snackbar, and show it on "/".

## Current Behavior

It enqueues 2 snackbars on "/".

## Steps to Reproduce

```js
const Page = () => {
  const {enqueueSnackbar} = useSnackbar();
  
  enqueueSnackbar("Test")
  
  return (
	<Redirect to="/" />
  )
}
```

## Context

I'm trying to enqueue a snackbar when an user tries to access a private page. If the user tries to access the private page, he'll be redirected to "/" and shown a snackbar informing that he can't access that page.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | 2.0.3  |
| React        |     17.0.2    |

**Comment by iamhosseindhv** [comment]
Hey @JeronimoMendes
This is the expected behaviour given how React works. I think you may want to do the following instead?

```tsx

const Page = () => {
  const {enqueueSnackbar} = useSnackbar();
  
  useEffect(() => {
      // show a snackbar when user lands on the "Page"?
      enqueueSnackbar("Test")
  }, [])
  
  return (
	<Redirect to="/" />
  )
}


```
