### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by suren-atoyan** [iamhosseindhv/notistack#481]
Please update peer dependencies in order to support `React` version 18+

**Comment by iamhosseindhv** [comment]
Thanks @suren-atoyan . I'll release an update asap

**Comment by iamhosseindhv** [comment]
You can download the new release as `v2.0.4`

**Comment by suren-atoyan** [comment]
> You can download the new release as `v2.0.4`. Let me know if you're facing any issues.

Everything is okay; thank you for the quick response!
