### ISSUE TITLE
How should I directly call notistack to prompt

### ISSUE THREAD

**Issue by FairyWorld** [iamhosseindhv/notistack#483]
Instead of how to use notistack in the component, I want to conduct a global processing in the response interceptor of Axios to display the intercepted errors. How should I directly call notistack to prompt. If it is handled separately, you can use notistack to prompt in the component, but each request must be handled separately, which is more troublesome

```
// This is a global interceptor
_axios.interceptors.response.use(
  (res) => {
    if (res.data.success) {
        // success
    }
  },
  (error) => {
    // How should I directly call notistack to prompt
    return Promise.reject(error)
  }
)
```

**Comment by MonstraG** [comment]
This sounds like you're trying to display a notistack outside of a compontent, and there is an issue and a solution for that:
https://github.com/iamhosseindhv/notistack/issues/30#issuecomment-542863653

**Comment by iamhosseindhv** [comment]
Closing as dup of #30
