### ISSUE TITLE
Issue with Events for the Snackbar Action

### ISSUE THREAD

**Issue by smartlightning** [iamhosseindhv/notistack#492]
Hello all,
I'm facing a dead-end after spending most of yesterday trying to fix an issue with Mouse-Events and hooks for the snackbar action. onMouseEnter and onMouseLeave Events are not executed properly for my Button component. I'm also using hooks to change the state, as soon as somebody hovers over the action button.
[Here's my CodeSandbox](https://codesandbox.io/s/snackbar-rxjs-mnzf9d?file=/src/CustomSnackbar.js) with my issue. 
I'd be extremely grateful to the community for your help.
Chris

**Comment by iamhosseindhv** [comment]
Hi @smartlightning, you were almost there. You're action should've been its own component. Example: https://codesandbox.io/s/snackbar-rxjs-forked-ph7tgm

Also have a look into `npm i notistack@alpha`, it will make it much easier to display custom snackbars. https://notistack.com/examples/advanced/custom-component

**Comment by smartlightning** [comment]
Thanks so much @iamhosseindhv . Great answer.
