### ISSUE TITLE
Best way to customize position of different notifications

### ISSUE THREAD

**Issue by slothtoday** [iamhosseindhv/notistack#493]
If, on one of my app's pages, I have to position the different notifications in different places, what would be the best place to do it? Suppose for a particular info notification I'm positioning it near the form but for a success notification it is near the dialog box.
Can `domRoot` prop be managed through state or I'll have to separate the providers and their anchor points for every different position?

**Comment by jgabriel98** [comment]
You can use the style props `top` `left` `right` and `bottom `, like this
```js
    <SnackbarProvider
        style={{ top: distanceYouWant }}
        anchorOrigin={{ horizontal: 'center', vertical: 'top' }}
        >
```
or
```js
const options = {
      style:{{ top: distanceYouWant }}
      content: (key, msg) => (
        <Alert key={key}>
          {msg}
        </Alert>
      )
    };
enqueueSnackbar(message, options);
```

**Comment by iamhosseindhv** [comment]
You can use `domRoot` to show snackbar within a div (and not within window/screen which is the default behaviour). See the homepage of [documentation website](https://notistack.com/). You can see how using `domRoot` I'm displaying snackbars inside a card.

<img width="1102" alt="Screenshot 2022-10-16 at 17 13 58" src="https://user-images.githubusercontent.com/26996372/196046181-739b06f8-505b-4368-87eb-56dba40aa056.png">


You can update domRoot prop using state, but also there's nothing stopping you from having multiple SnackbarProviders. 
 For example you can wrap you form inside a `SnackbarProvider` with some `domRoot`.
