### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by dylanahoang** [iamhosseindhv/notistack#494]
I'd like to use this library on native ios and android apps. Are there any alternative libraries or are there any plans to support this in the future? Thanks!

## Expected Behavior
works on react native

## Current Behavior
```
Unable to resolve module @mui/material/Slide from /Users/dylan/Documents/GitHub/ambrook.com/mobile/apps/AmbrookApp/node_modules/notistack/dist/notistack.cjs.production.min.js: @mui/material/Slide could not be found within the project or in these directories:
  /Users/dylan/Documents/GitHub/ambrook.com/mobile/apps/AmbrookApp/node_modules/@mui/material
  ```
## Steps to Reproduce

Use in react native typescript code.

**Comment by iamhosseindhv** [comment]
I would love to support react-native and Svelte #508 , but unfortunately don't have enough spare time to commit to it and build it.
