### ISSUE TITLE
Multiple snackbars get cleared at same time (v3 / beta)

### ISSUE THREAD

**Issue by what-is-a-crow** [iamhosseindhv/notistack#495]
In the v3 / beta version of notistack, there is an issue with subsequent snackbars getting dismissed when prior snackbars are dismissed.

## Steps to Reproduce
When I trigger a snackbar
And I trigger another snackbar right before the first is dismissed

## Expected Behavior
The second snackbar is dismissed after the full timeout

## Actual Behavior
The second snackbar is dismissed along with the first snackbar (almost immediately after appearing) 

[Minimal CodeSandbox reproduction](https://codesandbox.io/s/modern-star-w3lh4g?file=/src/App.js) - click "Show snack" once and wait the full 5 seconds.

**Comment by iamhosseindhv** [comment]
I can confirm actual behaviour is not matching the expected behaviour. I will look into this, in the meantime, any help regarding finding the bug is greatly appreciated

**Comment by iamhosseindhv** [comment]
Thanks for reporting. This is fixed and published as `v3.0.0-alpha.5`
