### ISSUE TITLE
`v3` all opened snackbars are getting closed at once

### ISSUE THREAD

**Issue by nichita-pasecinic** [iamhosseindhv/notistack#496]
## Expected Behavior
Snackbars should close in the reverse order they was opened 

## Current Behavior
All snackbars are being closed at the same time

## Steps to Reproduce

Link:

1. https://codesandbox.io/s/pedantic-shaw-y3nis

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v3  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
Dup #495. We will track progress there.
