### ISSUE TITLE
import closeSnackbar - v3 Actions

### ISSUE THREAD

**Issue by jacokok** [iamhosseindhv/notistack#505]
import { closeSnackbar } from 'notistack' not working on v3 anymore.

## Expected Behavior
To be able to import closeSnackbar from notistack in order to use  it in actions.

## Current Behavior
import fails

## Steps to Reproduce
With example below. Should be able to closeSnackbar from actions. But without import it is not possible.
```tsx
// add action to all snackbars
import { closeSnackbar } from 'notistack' // This import does not work anymore

<SnackbarProvider
  action={(snackbarKey) => (
    <button onClick={() => closeSnackbar(snackbarKey)}>
      Dismiss
    </button>
  )}
>
    <App />
</SnackbarProvider>
```

| Tech         | Version |
|--------------|---------|
| Notistack | 3.0.0-alpha.7 |

**Comment by k-shimada-vxc** [comment]
I'm facing the same issue on 2.0.5
How can I resolve this?

**Comment by jacokok** [comment]
Thank you @k-shimada-vxc  this is exactly what I needed.
