### ISSUE TITLE
Code example in documentation doesn't work

### ISSUE THREAD

**Issue by ackinc** [iamhosseindhv/notistack#506]
The "An action can also be globally passed to all Snackbars" code example shown [here](https://notistack.com/v2.x/examples#actions) contains the line `import { closeSnackbar } from 'notistack'`, which fails because notistack does not export `closeSnackbar`.

## Expected Behavior
Code example should work

## Current Behavior
Code example doesn't work

## Steps to Reproduce
Codesandbox: https://codesandbox.io/s/bold-mendeleev-4iv8d2

The codesandbox fails with an error ("_notistack.closeSnackbar is not a function") when "Dismiss" is clicked on any of the snackbars

## Context
I'm trying to pass a "dismiss" action globally to all snackbars

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.5  |
| React | v17.0.2 |
| Webpack |v5.70.0  |

**Comment by iamhosseindhv** [comment]
Thanks for reporting this @ackinc ❤️. Documentation website has now been updated to show how you can apply an `action` globally: https://notistack.com/v2.x/examples#actions
