### ISSUE TITLE
Custom Transition causes error "handleEnteredSnack Cannot be called with undefined key"

### ISSUE THREAD

**Issue by w90** [iamhosseindhv/notistack#507]
Has anyone got custom transitions working in 3.0.0 alfa? Like Grow for example?
I migrated from v2, where it worked, now it's broken.

**Comment by homerchen19** [comment]
I got the same issue even if I just wrote `TransitionComponent={Slide}`

**Comment by ddemoss222** [comment]
Can confirm this is still an issue.

**Comment by iamhosseindhv** [comment]
I'm not sure why you were getting the error described in the issue title, but you could definitely be able to use custom transitions in v3 alpha. As [doc website](https://notistack.com/features/transition) says:
>  If you already have Material-UI as a dependency in your project, you can simply use [MUI transitions](https://mui.com/material-ui/transitions).

Please open a new issue if you're having any issues.

**Comment by homerchen19** [comment]
Confirmed the issue is fixed by https://github.com/iamhosseindhv/notistack/pull/518 Thank!
