### ISSUE TITLE
Notistack incompatible with MUI className generator

### ISSUE THREAD

**Issue by ThiloAschebrock** [iamhosseindhv/notistack#510]
When one uses MUI 5 with notistack version 2 and applies the ClassName generator of MUI, see https://mui.com/material-ui/experimental-api/classname-generator/, it will break some styles, e.g., customization based via `class` are no longer applied and the snackbar is no-longer responding to pointer events since `pointer-events: all` is no longer applied.

## Expected Behavior
Notistack should not break when applying the classname generator and should still allow for interaction.

## Current Behavior
Notistack nreaks when applying the classname generator and no longer allows interaction with pointer events, i.e., to close the snack or to select and copy the message.

## Steps to Reproduce

See code sandbox at https://codesandbox.io/s/compassionate-lehmann-dbgk96?file=/src/App.tsx

## Context

ClassName generator of MUI is currently the only way to avoid class name collisions in MUI 5 with other parts of the App, e.g., with micro-frontends.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.5  |
| React      |  18.0.0 |
| Browser  | Chrome 104  |
| MUI        |   5.10.2    |

**Comment by iamhosseindhv** [comment]
Dup #389
