### ISSUE TITLE
How to change the default background color of default variant (e.g. Error variant)

### ISSUE THREAD

**Issue by w90** [iamhosseindhv/notistack#511]
I can see how to change the icons to custom icons, it's well covered in the docs.
But can't find anything about changing the background colors of default variants.
I do not want to create a custom overriding component, just change the bg color of existing variants.
Thanks for any help.

**Comment by w90** [comment]
I ended up creating custom notifications just for that.

**Comment by datotec-petry** [comment]
Use a styled SnackbarProvider just like that:

`const StyledSnackbarProvider = styled(SnackbarProvider)<SnackbarProviderProps>(
  ({ theme }) => ({
    "&.SnackbarItem-variantInfo": {
      backgroundColor: theme.palette.info.main,
    },
    "&.SnackbarItem-variantError": {
      backgroundColor: theme.palette.error.main,
    },
    "&.SnackbarItem-variantWarning": {
      backgroundColor: theme.palette.warning.main,
    },
    "&.SnackbarItem-variantSuccess": {
      backgroundColor: theme.palette.success.main,
    },
  })
);`

**Comment by iamhosseindhv** [comment]
@ datotec-petry 's solution is suitable for your case (i.e. you JUST want a background colour change.)

**Comment by iamhosseindhv** [comment]
Note above solution works on notistack v2. If you're using notistack v3, refer to [overriding styles](https://notistack.com/features/customization#override-styles) section of the docs

**Comment by twistezo** [comment]
For now should be `'&.notistack-MuiContent-info'` and it should be noticed in readme. Moreover, since the library is based on MUI, it should use its theme by default.
