### ISSUE TITLE
disableWindowBlurListener={false} not working when enqueueSnackbar() is called in the background

### ISSUE THREAD

**Issue by AlexKarajohn** [iamhosseindhv/notistack#515]
## Expected Behavior

When `disableWindowBlurListener` is `default (false)` then the `autoHideDuration` timer should pause when window is blurred.

## Current Behavior

When `enqueueSnackbar` is called async and the window is blurred the timer does not pause.

## Steps to Reproduce
Link: https://codesandbox.io/s/strange-borg-zq68ex?file=/MessageButtons.js

1. click on any button to create a snackbar
2. you have 5000ms to blur the window
3. wait for the snackbar to appear.
4. it will vanish after 5000ms of appearing (even with the window being blurred)

## Context
Pretty straightforward. Persist any background created snackbar until the user refocuses the window. (coming from http req / WS or w/e)

## Your Environment
Forked demo codesandbox and recreated.

| Tech         | Version |
|--------------|---------|
| Notistack | v1.?.?  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
This is a valid point but unfortunately I don't have time to implement it and can't prioritise it over other features as this issue hasn't had much engagement from notistack users. PRs are welcome
