### ISSUE TITLE
Mui Theme does not change styling of Snackbar

### ISSUE THREAD

**Issue by Kai-W** [iamhosseindhv/notistack#517]
## Expected Behavior
Mui theme not changes styling of Snackbar . E.g borderRadius and colors should be read from theme and applied to Snackbar

## Current Behavior
BorderRadius and Colors are hardcoded in Snackbar

## Steps to Reproduce
Link: https://codesandbox.io/s/thirsty-surf-kc7tv5?file=/src/App.js

1. Create custom Theme with custom colors (e.g. error, info, warning, log...) or custom borderRadius
2. Place Theme Provider around Snackbar
3. enqueueSnackbar e.g. with variant e.g. error

## Context
I have a themed app and wanted to use notistack without need to restyle based on the theme.

## Your Environment
| Tech         | Version |
|--------------|---------|
| Notistack | ^2.0.5  |
| React        |  ^18.2.0       |
| MaterialUI |  ^5.10.3        |

**Comment by iamhosseindhv** [comment]
Hey @Kai-W 

Decoupling notistack from MUI (and its `theme`) is intentional. Take a look at [this example](https://github.com/iamhosseindhv/notistack/tree/alpha/examples/custom-snackbar-example) to see how you can update snackbar's stylings based on mui theme.

In the example above, snackbar styles change based dark/light theme modes.

**Comment by Kai-W** [comment]
@iamhosseindhv 
but @mui/material is a required peerDependency. It`s confusing to require it on one side and then decoupling notistack from Mui on the other side. In some places ther are values that are read from the mui theme: 
https://github.com/iamhosseindhv/notistack/blob/master/src/SnackbarItem/SnackbarItem.tsx#L30
Notistack should either support mui features like the theme or remove mui completely from notistack. The current state is a confusing hybrid in between.
