### ISSUE TITLE
Five Warning open snackbar componet.

### ISSUE THREAD

**Issue by Hugobrr** [iamhosseindhv/notistack#523]
I try create a personalized component with receive an internalization ID, instead of default message and type of snackbar. Using alpha version but receive this warning.

## Expected Behavior
Run with out Warning

## Current Behavior
Warnings:

1.  Received `false` for a non-boolean attribute `persist`.
2. React does not recognize the `anchorOrigin` prop on a DOM element.
3.  React does not recognize the `autoHideDuration` prop on a DOM element.
4. React does not recognize the `hideIconVariant` prop on a DOM element.
5.  React does not recognize the `iconVariant` prop on a DOM element.

## Steps to Reproduce

Link:

1. https://codesandbox.io/s/elated-microservice-opo0o6

## Your Environment
My tsconfig.json: 
`{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSources": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "sourceRoot": "/",
    "strict": true,
    "strictNullChecks": true,
    "target": "es6",
    "typeRoots": [
      "./node_modules/@types",
      "./@types"
    ],
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ]
  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js",
    "scripts"
  ],
  "include": [
    "src"
  ]
}`

| Tech         | Version |
|--------------|---------|
| Notistack | v3.0.0  |
| React        |  v18.2.0       |
| Browser      |  Brave V 1.44.112       |

Brave details [Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)](https://brave.com/latest/)

My routes index: 
```
export const Constants: ConstantsProp = {
  snackbarProp: {
    maxSnack: 1,
    anchorOrigin: {
      vertical: 'top',
      horizontal: 'center',
    },
    autoHideDuration: 10000,
  },
};
...
    <SnackbarProvider
        Components={{
          snackIntl: SnackbarIntl,
        }}
        {...Constants.snackbarProp}
      >
      ....
       </SnackbarProvider>
```

My componet 
```
import type { BaseVariant, CustomContentProps } from 'notistack';
import { SnackbarContent, useSnackbar } from 'notistack';
import CloseIcon from '@mui/icons-material/Close';
import { forwardRef, useCallback } from 'react';

import { FormattedMessage } from 'react-intl';

import { IconButton } from '@mui/material';

import Stack from 'components/Stack';

import type { LocaleIds } from 'types/LocaleIds';

import styles from './styles';

declare module 'notistack' {
  interface VariantOverrides {
    snackIntl: {
      type: BaseVariant;
      intl: LocaleIds;
    };
  }
}

interface SnackbarIntlProps extends CustomContentProps {
  intl: LocaleIds;
  id: string;
  type: BaseVariant;
}

export enum variantEnum {
  SUCCESS = 'success',
  DEFAULT = 'default',
  ERROR = 'error',
  WARNING = 'warning',
  INFO = 'info',
}

export const VARIANT_TYPES: BaseVariant[] = [
  'default',
  'error',
  'success',
  'warning',
  'info',
];

const SnackbarIntl = forwardRef<HTMLDivElement, SnackbarIntlProps>(
  (props, ref) => {
    const { intl, id, type, ...other } = props;
    const { closeSnackbar } = useSnackbar();
    const handleDismiss = useCallback(() => {
      closeSnackbar(id);
    }, [id, closeSnackbar]);
    return (
      <Stack direction="row" width="100%" sx={styles[type]}>
        <SnackbarContent ref={ref} {...other}>
          <FormattedMessage id={intl} />

          <IconButton size="small" onClick={handleDismiss}>
            <CloseIcon fontSize="small" />
          </IconButton>
        </SnackbarContent>
      </Stack>
    );
  },
);
SnackbarIntl.displayName = 'SnackbarIntl';
export default SnackbarIntl;

```

**Comment by iamhosseindhv** [comment]
@Hugobrr The issue is spreading `...other` to `SnackbarContent` which will end up getting passed to a `div` element.

```jsx
const { intl, id, type, anchorOrigin, ...other } = props; // <-- get anchorOrigin out
```

**Comment by mikhail-fedosenko** [comment]
Hm, I've followed the documentation example:

```tsx
const ReportComplete = React.forwardRef<HTMLDivElement, ReportCompleteProps>((props, ref) => {
  const {
    // You have access to notistack props and options 👇🏼
    id,
    message,
    // as well as your own custom props 👇🏼
    allowDownload,
    ...other
  } = props

  return (
    <SnackbarContent ref={ref} role="alert" {...other}>
      {message}
    </SnackbarContent>
  )
})
```
registered my own component and getting same errors (React does not recognize ....).

My code:
```tsx
import { Alert } from '@mui/material';
import {
  closeSnackbar,
  type CustomContentProps,
  SnackbarContent,
} from 'notistack';
import React from 'react';

export const AlertSnackbar = React.forwardRef<
  HTMLDivElement,
  CustomContentProps
>((props, ref) => {
  const { id, message, variant, ...other } = props;

  console.log({ other });
  return (
    <SnackbarContent ref={ref} role={'alert'} {...other}>
      <Alert
        variant={'filled'}
        severity={variant !== 'default' ? variant : undefined}
        onClose={() => closeSnackbar(id)}
      >
        {message}
      </Alert>
    </SnackbarContent>
  );
});

export function SnackbarProvider({ children }: PropsWithChildren) {
  return (
    <NotistackSnackbarProvider
      autoHideDuration={5000}
      Components={{
        success: AlertSnackbar,
        info: AlertSnackbar,
        warning: AlertSnackbar,
        error: AlertSnackbar,
        default: AlertSnackbar,
      }}
    >
      {children}
    </NotistackSnackbarProvider>
  );
}
```

I suppose the docs are wrong and you need _only_ pass the following props (as stated in another docs page: https://notistack.com/features/customization#child-requirements ):
- Forward the ref using React.forwardRef
- Forward the style
- Be a single element (React.Fragment is not allowed)


So, fixed component will look like:
```tsx
export const AlertSnackbar = React.forwardRef<
  HTMLDivElement,
  CustomContentProps
>((props, ref) => {
  const { id, message, variant, className, style } = props;

  return (
    <SnackbarContent
      ref={ref}
      role={'alert'}
      className={className}
      style={style}
    >
      <Alert
        variant={'filled'}
        severity={variant !== 'default' ? variant : undefined}
        onClose={() => closeSnackbar(id)}
      >
        {message}
      </Alert>
    </SnackbarContent>
  );
});
```

I suggest the docs gets fixed...
