### ISSUE TITLE
Can't seem to get dynamic imports working alongside Notistack 3

### ISSUE THREAD

**Issue by stevenkeith85** [iamhosseindhv/notistack#524]
Followed the suggested method here:
https://github.com/vercel/next.js/issues/4957

Get a message about not setting up the forward ref correctly.

I'm trying to pass the forward ref'd component to SnackbarProvider.

Any examples of how I should be doing this?

Thanks

**Comment by iamhosseindhv** [comment]
Sorry @stevenkeith85 - I've gotten to this late - Let me know if you're still experiencing this issue.
