### ISSUE TITLE
closeSnackbar doesn't work in the project but works fine in codesandbox.

### ISSUE THREAD

**Issue by olindv** [iamhosseindhv/notistack#527]
`closeSnackbar` doesn't work for Custom Components as expected.

## Expected Behavior

The SnackBar should be closed.
## Current Behavior

I did everything according to the documentation, but I don't understand why my code doesn't work (I mean - my snackbars doesn't want to close). My situation confuses me a little, since the code that is in my project does not work, unlike the similar code that I transferred to the code sandbox.
## Steps to Reproduce

Link:

1. This work for me fine - https://codesandbox.io/s/falling-dawn-slnz1p?file=/src/Informer.tsx:887-894
2. The same code in my project doesn't work. I guess it's related with `SnackbarProvider`. It's look something like that: 
```
import { ThemeProvider } from '@mui/material/styles';
import { SnackbarProvider } from 'notistack';
import { InformerToast } from 'components';

<ThemeProvider>
      <SnackbarProvider
        maxSnack={5}
        Components={{
          informerToast: InformerToast,
        }}
      >
        <Layout>
          {children}
        </Layout>
      </SnackbarProvider>
</ThemeProvider>
```
In all other respects, my code is identical to the one in the sandbox
## Context

For multiple snackbars, I need the ability to close the one I want.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v3.0.0-alpha.11  |
| React        |    17.0.0     |
| Browser      |    Chrome     |
| etc.         |         |

**Comment by olindv** [comment]
Solved the issue by passing the handler to `enqueueSnackbar`

**Comment by iamhosseindhv** [comment]
Hey @olindv , glad you found a solution. It would also benefit other people if you could share a code snippet of the solution.
