### ISSUE TITLE
Deduplicate enqueueSnackbar with options.key

### ISSUE THREAD

**Issue by koooge** [iamhosseindhv/notistack#528]
Hi there,
enqueueSnackbar options' `key` does not deduplicate snackbars and got `Warning: Encountered two children with the same key` error. Is it intended? https://notistack.com/api-reference#enqueuesnackbar-options

## Expected Behavior

I expected notistack deduplicates snakcbars with options.key such as  `preventDuplicate` with the message. I think react is more like aiming for declarative, then these kinds of method are often called multiple times. So I expect enqueueSnackbar prevent duplicate with key as well.

## Current Behavior

Got several snackbars with `Warning: Encountered two children with the same key` console errors. `options.key` does nothing. 
 
## Steps to Reproduce

```js
      // Call here multiple times
      enqueueSnackbar(button.message, {
        variant: button.variant,
        key: "some identical key"
      });
 ```
 
Link:

1. code sandbox: https://codesandbox.io/s/focused-bouman-xml4yq?file=/MessageButtons.js:1084-1200
2.
3.
4.

## Context

This is similar to #234 but I only expect to deduplicate.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.8  |
| React        |   v18.2.0     |
| Browser      |     chrome  107  |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
Hey @koooge - `preventDuplicate` prevents duplicated by comparing Snackbar **messages**. But if you pass your own `key`, then it tried to dedup using the key. This is also mentioned in the [documentation](https://notistack.com/features/basic#prevent-duplicate). Please let me know if you're not experiencing the expected behaviour.

**Comment by koooge** [comment]
Hi @iamhosseindhv , then please check code sandbox I created. 

> code sandbox: https://codesandbox.io/s/focused-bouman-xml4yq?file=/MessageButtons.js:1084-1200

**Comment by iamhosseindhv** [comment]
@koooge - In the example you provided, you're not passing `preventDuplicate`. Checkout the [docs](https://notistack.com/features/basic#prevent-duplicate).

Here's a working example:
https://codesandbox.io/s/blissful-violet-4s6z2f?file=/App.js:164-180

In short - you need to either add `preventDuplicate` to `SnackbarProvider` (to apply this globally) or to `enqueueSnackbar` function.
