### ISSUE TITLE
Custom variants - help required

### ISSUE THREAD

**Issue by Hatish** [iamhosseindhv/notistack#53]
Thank you for this wonderful library.

I am trying to implement custom variants as follows:
https://iamhosseindhv.com/notistack#custom-variants

I have tried in this sandbox, with no success:
https://codesandbox.io/s/l7p579l5nm

If you have a working sandbox of this example, that would be very helpful.

Thank you for your time.

**Comment by iamhosseindhv** [comment]
@Hatish Glad you like the library. You should pass your stylings using `classes`. For more info see [overriding with classes](https://material-ui.com/customization/overrides/#overriding-with-classes) in material-ui docs.

```javascript
import React from 'react';
import { withStyles } from '@material-ui/core/style';
import { SnackbarProvider } from 'notistack';
import MessageButtons from './MessageButtons';

const styles = {
  success: { backgroundColor: "#7d7c7d" },
  info: { backgroundColor: "#D71920" }
};


const App = ({ classes }) => (
  <SnackbarProvider
    maxSnack={3}
    classes={{
      variantSuccess: classes.success,
      variantInfo: classes.info
    }}
  >
    <MessageButtons />
  </SnackbarProvider>
);

export default withStyles(styles)(App);
```
