### ISSUE TITLE
Centre snackbar with respect to a component

### ISSUE THREAD

**Issue by pranay1208** [iamhosseindhv/notistack#533]
I am using NotiStack for a portal that contains an open drawer in desktop mode. Due to the drawer taking up ~20-30% of the screen space on the left, all the page content occupies the remaining space.

The page somewhat resembles this style 

![image](https://user-images.githubusercontent.com/47204059/208579557-9172ffb6-7eb3-414d-a164-abea148db9eb.png)

The problem I am facing is that some headings are centred within the content root component, which means they are not in the centre of the page. When I queue up a notification to show up in the top-center, it will show up in the exact centre of the entire page, which is slightly to the left of the "centred" headings

E.g. if my entire page is 100px wide and the drawer takes up 20px, then my centred headings are at the 60px mark, but the notification spawns at the 50px mark.

Is there any way where I can mark the notifications to be centred with respect to the content component? 

Edit - I am using notistack 2.0.8 on React v17

**Comment by iamhosseindhv** [comment]
Hi @pranay1208 - Look at this example were snackbars are displayed relative to a container and not window.
https://codesandbox.io/s/inspiring-lamport-kzesxk?file=/App.js


<img width="728" alt="Screenshot 2023-03-04 at 19 37 11" src="https://user-images.githubusercontent.com/26996372/222925485-18afb987-4c14-43ed-8dac-aaab7fb3d4a7.png">
