### ISSUE TITLE
No "Component" prop on SnackbarProvider in TS

### ISSUE THREAD

**Issue by nirtz-appcharge** [iamhosseindhv/notistack#534]
## Expected Behavior
I should be able to add a Component prop in order to replace the original notification.

## Current Behavior
No `Component` prop

## Steps to Reproduce
`npm i` notistack with TS and try adding a `Component` prop to the `SnackbarProvider` component

## Context

index.d.ts of notistack
```
export interface SnackbarProps extends StandardProps<React.HTMLAttributes<HTMLDivElement>, SnackbarClassKey> {
    /**
     * The anchor of the `Snackbar`.
     * @default { horizontal: left, vertical: bottom }
     */
    anchorOrigin?: SnackbarOrigin;
    /**
     * The number of milliseconds to wait before automatically calling the
     * `onClose` function. By default snackbars get closed after 5000 milliseconds.
     * Set autoHideDuration to 'null' if you don't want snackbars to automatically close.
     * Alternatively pass `persist: true` in the options parameter of enqueueSnackbar.
     * @default 5000
     */
    autoHideDuration?: number | null;
    /**
     * @ignore
     * Properties applied to ClickAwayListener component
     */
    ClickAwayListenerProps?: Partial<ClickAwayListenerProps>;
    /**
     * Aria attributes applied to snackbar's content component
     */
    ariaAttributes?: React.AriaAttributes;
    /**
     * If `true`, the `autoHideDuration` timer will expire even if the window is not focused.
     * @default false
     */
    disableWindowBlurListener?: boolean;
    /**
     * The number of milliseconds to wait before dismissing after user interaction.
     * If `autoHideDuration` property isn't specified, it does nothing.
     * If `autoHideDuration` property is specified but `resumeHideDuration` isn't,
     * we use the default value.
     * @default autoHideDuration / 2 ms.
     */
    resumeHideDuration?: number;
    /**
     * The component used for the transition. (e.g. Slide, Grow, Zoom, etc.)
     * @default Slide
     */
    TransitionComponent?: React.JSXElementConstructor<TransitionProps & { children: React.ReactElement<any, any> }>;
    /**
     * The duration for the transition, in milliseconds.
     * You may specify the duration with an object in the following shape:
     * ```js
     * transitionDuration={{ enter: 300, exit: 500 }}
     * ```
     * @default { enter: 225, exit: 195 }
     */
    transitionDuration?: { appear?: number; enter?: number; exit?: number };
    /**
     * Properties applied to Transition component (e.g. Slide, Grow, Zoom, etc.)
     */
    TransitionProps?: TransitionProps;
}
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v2.0.8  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by LucianABC** [comment]
This seems to still be an issue, I can't pass down my own custom components. Is this being fixed?

**Comment by IkboljonMe** [comment]
nothing new(

**Comment by henningta** [comment]
Looks like the code was updated at some point, and the documentation is outdated. Digging into the TS definitions, I see a new `content` prop, which appears to have replaced the `Components` prop:

```typescript
// src/index.d.ts

export type SnackbarKey = string | number;
…
export type SnackbarMessage = string | React.ReactNode;
…
export type SnackbarContentCallback = React.ReactNode | ((key: SnackbarKey, message: SnackbarMessage) => React.ReactNode);

…

/**
 * Replace the snackbar. Callback used for displaying entirely customized snackbar.
 * @param {string|number} key key of a snackbar
 */
content?: SnackbarContentCallback;
```

Problem now is only the key and message are being passed along to the content component. I don't see a way of getting the variant or other props/info into a custom component in the current design. 

I'd consider this aspect of it a bug unless there's some other way of passing those props to custom snackbars.

**Comment by IkboljonMe** [comment]
Thanks, it worked)

**Comment by iamhosseindhv** [comment]
You got it the other way around folks. `content` prop is the old way of doing it using notistack v2 (installed by `npm i notistack`). 

`Components` prop is the new way of doing it which is more flexible, with better TS support and it’s a new feature introduced in  notistack v3 which is an alpha release (installed by `npm i notistack@alpha`)

notistack v3 will soon be published as the `latest` stable release.

**Comment by iamhosseindhv** [comment]
Sorry for the confusion. Let me know it you have any questions

**Comment by guisartori** [comment]
hello guys! Thanks for that. I didn't found an alert about it in documentation. For example: "if you are using TS and want to use Components prop, make sure to install notistack@alpha version". Thanks!
