### ISSUE TITLE
miss export `closeSnackbar`

### ISSUE THREAD

**Issue by bluelovers** [iamhosseindhv/notistack#536]
## Expected Behavior

```
import { enqueueSnackbar, closeSnackbar } from 'notistack'
```

## Current Behavior

`closeSnackbar` not export in index

## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.?.?  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
Hey @bluelovers  - I believe you're looking at v3 (alpha) documentation but your notistack version is v1.

You can update notistack to v3, or refer to [documentation for v2](https://notistack.com/v2.x/getting-started) or below.

<img width="320" alt="Screenshot 2023-03-04 at 19 16 55" src="https://user-images.githubusercontent.com/26996372/222924717-c7a13ac4-54c5-4968-a0aa-dfbe8344d700.png">
