### ISSUE TITLE
Jest and react-testing-library: Is there any solution about removing beforeAll Notistack on testing or not to wait it or expect

### ISSUE THREAD

**Issue by UmrzoqScope3** [iamhosseindhv/notistack#537]
Jest and react-testing-library: Is there any solution about removing beforeAll Notistack on testing or not to wait it or expect

## Steps to Reproduce

Link:

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.?.?  |
| React        |         |
| Browser      |         |
| etc.         |         |

**Comment by iamhosseindhv** [comment]
Hey @UmrzoqScope3  - Unfortunately the issue is lacking key information / sample code / reproduction. I may be able to help given more info.
