### ISSUE TITLE
Open notification outside of a component

### ISSUE THREAD

**Issue by fires3as0n** [iamhosseindhv/notistack#540]
Hello, I wonder how to "extremely easy" open a notification not from the component, e.g. in Axios interceptor or SWR api handler.
Thanks.

**Comment by engrwaqasali** [comment]
+1
open snackbar outside react, without hook

**Comment by yudielcurbelo** [comment]
It can be done using an alpha version `3.0.0-alpha.11`

Import
`import {enqueueSnackbar} from 'notistack';`

Use
`enqueueSnackbar({message: 'Some message.', variant: 'success'});`

**Comment by iamhosseindhv** [comment]
Thanks @yudielcurbelo - Using notistack v3 (`npm i notistack@alpha`) you can call `enqueueSnackbar` from outside of a React component.

**Comment by iamhosseindhv** [comment]
Note that v3 is now the stable release. Simply do `npm install notistack@latest`
