### ISSUE TITLE
Customize page offsets

### ISSUE THREAD

**Issue by marc-at-brightnight** [iamhosseindhv/notistack#543]
Hi,

I'm looking to increase the offsets from the page. I think this is has been referenced in a previous issue but was unable to find the solution. For top right anchored snackbars, I'd like to increase the top offset so snackbars appear below the appbar.

Please let me know if this is a supported use case and if so, what best practices are. Thanks!

![image](https://user-images.githubusercontent.com/76454594/221320777-2fff40a6-e33e-418e-9aec-bcb29b014a2b.png)

**Comment by iamhosseindhv** [comment]
Hi @marc-at-brightnight  - You can use the `classes` prop in `SnackbarProvider`. `containerRoot` the class name. Look at this example:
https://codesandbox.io/s/objective-dream-grfqm?file=/src/AppProvider.js

**Comment by marc-at-brightnight** [comment]
> Hi @marc-at-brightnight - You can use the `classes` prop in `SnackbarProvider`. `containerRoot` the class name. Look at this example: https://codesandbox.io/s/objective-dream-grfqm?file=/src/AppProvider.js

Hi @iamhosseindhv , thanks for the quick reply.

I am using MUI v5 and Snackbar v2. The code example you sent had outdated dependencies. The following adjusted code worked for me. I ended up using `tss-react` but I'm sure there's a handy way to solve it with `@emotion` too. 

It might be helpful to add this to the docs, since it's a fairly common use case and I'm sure I'm not the only one who has struggled with this.

```
import { makeStyles } from 'tss-react/mui';

const useSnackbarStyles = makeStyles()(() => ({
  root: { marginTop: 40 },
}));

function App(): JSX.Element {
  const { classes } = useSnackbarStyles();

  return (
    <SnackbarProvider classes={{ containerAnchorOriginTopRight: classes.root }}>
      <App />
    </SnackbarProvider>
}
```

**Comment by kei969777** [comment]
the latest version:
import {makeStyles} from '@mui/styles';
....

<SnackbarProvider
                    classes={{
                        containerAnchorOriginTopRight: makeStyles(() => ({
                            root: {marginTop: 50},
                        }))().root
                    }}
/>

.....

**Comment by andreaswilli** [comment]
`makeStyles` was [deprecated in 2021](https://v6.mui.com/system/styles/basics/). Is there a supported way to do this?

**Comment by kommandantee** [comment]
> `makeStyles` was [deprecated in 2021](https://v6.mui.com/system/styles/basics/). Is there a supported way to do this?

Create a style.css file as
`.notistack-SnackbarContainer {
  top: 84px !important;
}`

Then import it where you have used,
`import "./style.css";`
