### ISSUE TITLE
Notistack not working on Node 16 and above

### ISSUE THREAD

**Issue by paragwaghela-bh** [iamhosseindhv/notistack#544]
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/88309017/222633579-68ee2f85-066f-48c3-920a-f9d19505e83f.png)
Type Error : Cannot Read property of null(reading useContext)

**Comment by iamhosseindhv** [comment]
Hi @paragwaghela-bh Unfortunately I'm not able to help without a reproduction example. Ensure you're wrapping your app inside `SnackbarProvider` to have access to the context. If the issue persists, please provide a minimal reproduction example.
