### ISSUE TITLE
ReactNode can no longer be used as a snackbar message

### ISSUE THREAD

**Issue by sodenn** [iamhosseindhv/notistack#548]
I noticed that it is no longer possible to use a `ReactNode` as a snackbar message after updating to v3. In v2 there was a `SnackbarMessage` that could be `string` or a `ReactNode`. This was useful for displaying formatted text in an easy way:

```jsx
enqueueSnackbar(<>That was <strong>easy!</strong></>);
```

Is there another way to do this in v3?

**Comment by iamhosseindhv** [comment]
Thanks for reporting - this has been published as `v3.0.1`.
