### ISSUE TITLE
Pass additional prop(s) using SnackbarProvider

### ISSUE THREAD

**Issue by vlrmprjct** [iamhosseindhv/notistack#571]
Hello,

my question is about passing additional props ( `additionalProp` )  using SnackbarProvider and a customized component.
It is intended to add a global translation object for example.

In this simplifyed example below the `additionalProp` is not existing in the CustomSnack props:
```
<SnackbarProvider
    additionalProp="whatever"   // <=== This one is not present @ CustomSnack props
    className="whatever-class"  // <=== This one is present @ CustomSnack props
    Components={{
        success: CustomSnack,
    }
>
    {/* something more */}
</SnackbarProvider>
```

I tried this but this returns an error:
```
<SnackbarProvider
    className="whatever-class"
    Components={{
        success: (someProps) => <CustomSnack  { ...someProps } additionalProp="whatever" />,
    }
>
    {/* something more */}
</SnackbarProvider>
```

The error msg is:
`notistack - Custom snackbar is not refForwarding`

<img width="800" alt="image" src="https://github.com/iamhosseindhv/notistack/assets/1859497/19010026-3275-4119-a7cb-94d787db5687">

Is there a way or workaround to add an additional prop ?
Maybe I am doing something wrong. A hint would be great.

Thx.

**Comment by iamhosseindhv** [comment]
Hey @vlrmprjct - As described in the [docs](https://notistack.com/features/customization#child-requirements), one of the requirements for the custom component is to use `React.forwardRef`. This should fix the react error regarding ref.

As to passing custom props through SnackbarProvider, unfortunately it's not on the roadmap and won't be added any time soon. Sorry about that!
