### ISSUE TITLE
Make snackbar offset from view customisable

### ISSUE THREAD

**Issue by iamhosseindhv** [iamhosseindhv/notistack#58]
Issue to fix problems of this nature: #57 #48

**Comment by JoeHetfield** [comment]
any work around about this? for set the offset to zero.

**Comment by iamhosseindhv** [comment]
This for sure will be added in future releases, however there're others feature/issues that take priority for now.

**Comment by raymondsze** [comment]
Any release schedule? Would like to have the offset feature.

**Comment by duongdev** [comment]
Any option to auto set `dense={true}` on mobile and `dense={false}` on desktop?

**Comment by iamhosseindhv** [comment]
No support from notistack. But of course it can be done wherever you're wrapping your app inside a `SnackbarProvider` @duongdev

**Comment by dhythm** [comment]
For someone's help, I just put a style like
```
const useStyles = makeStyles((theme) => ({
  // ...
  collapseWrapper: {
    marginTop: 4,
    marginBottom: 4,
  },
}))
```
to the props 'classes' of SnackProvider. (The default margin is 6px both)
Then, I could change the margin between the snackbars.

**Before**
![Screen Shot 2021-01-20 at 8 57 07](https://user-images.githubusercontent.com/10891318/105108414-86d0f900-5afd-11eb-93ef-0478c456304a.png)

**After**
![Screen Shot 2021-01-20 at 8 56 02](https://user-images.githubusercontent.com/10891318/105108350-6143ef80-5afd-11eb-8ace-f3ed2ec67d24.png)
