### ISSUE TITLE
use closeSnackbar in SnackbarProvider

### ISSUE THREAD

**Issue by ashanren** [iamhosseindhv/notistack#60]
Is it possible to add the closeSnackbar function to the action of the Snackbar Provider so i don't have to  do it for every individual instance?

For Example, I just tried the following,

```

return (
  <SnackbarProvider 
    autoHideDuration = {null}                                                                                                                            
    maxSnack = {3} 
    action = {[
      <IconButton key="close" color="inherit" onClick = {this.props.closeSnackbar(this)}><CloseIcon/></IconButton>
  ]}
  >
    <Login />
  </SnackbarProvider>
);


```

and i got an error saying that `this.props.closeSnackbar is not a function`.

**Comment by iamhosseindhv** [comment]
You can omit `onClick` part of the action and just pass the Icon button as an action. Default behaviour of action button is to dismiss/close the snackbar.

**Comment by dalborgo** [comment]
```
  <SnackbarProvider 
                                  maxSnack={3}
                                  anchorOrigin={{
                                    vertical: 'bottom',
                                    horizontal: 'right'
                                  }}
                                  action={(
                                    <Button>
                                      Close
                                    </Button>
                                  )}
                >
                  <App/>
</SnackbarProvider>
```

Sorry but I can't get the default behaviour.

**Comment by iamhosseindhv** [comment]
@dalborgo the answer above is for previous versions of notistack. In the latest version there is no default behaviour and you have explicitly define an `onClick` event handler. Please refer to iamhosseindhv.com/notistack for example code. Let me know if you still had problems.

**Comment by dalborgo** [comment]
ok thanks. Can I ask you if there is a way to close the notistack with a "click away"?

**Comment by iamhosseindhv** [comment]
You should be able to do something like this: @dalborgo 
```javascript
props.enqueueSnackbar('my mesage', {
     onClose: (event, reason, key) => {
          if (reason === 'clickaway') {
                this.props.closeSnackbar(key)
          }
     }
});

// OR
<SnackbarProvider
    onClose={(event, reason, key) => {
          if (reason === 'clickaway') {
           this.props.closeSnackbar(key)
          }
     }}
>
```

**Comment by chapati23** [comment]
I think this should be re-opened, for me the default behavior also broke and I don't know how to get it back.

This no longer works:

```jsx
<SnackbarProvider action={<Button>Dismiss</Button>}>
```

I also can't do this because `useSnackbar` only works within the provider of course:

```jsx
const { closeSnackbar } = useSnackbar()
...
return (
  <SnackbarProvider action={<Button>Dismiss</Button>}>
  ...
```

What's the right way to get a default `Dismiss` button for all snackbars in the latest version?

**Comment by iamhosseindhv** [comment]
@chapati23  `useSnackbar` can only be called inside body of a function component. So could great this action and pass it the action
```javascript
const DismissAction = ({ id }) => {
    const { closeSnackbar } = useSnackbar()
    return (
        <Fragment>
            <Button onClick={() => alert(`Show more data for key: ${id}`)}>More</Button>
            <Button onClick={() => closeSnackbar(id)}>Close</Button>
        </Fragment>
    )
}

<SnackbarProvider
    action={key => <DismissAction id={key} />}
>
    <App />
</SnackbarProvider>
```

**Comment by dalborgo** [comment]
Thank you @iamhosseindhv. Now I able to close the Snackbar globally. Have you any suggestions about the globally closing by "clickaway"?

Both this solutions don't work correctly (the reason is null):

```
props.enqueueSnackbar('my mesage', {
     onClose: (event, reason, key) => {
          if (reason === 'clickaway') {
                this.props.closeSnackbar(key)
          }
     }
});

// OR
<SnackbarProvider
    onClose={(event, reason, key) => {
          if (reason === 'clickaway') {
           this.props.closeSnackbar(key)
          }
     }}
>
```

**Comment by chapati23** [comment]
I see. To be honest, I think the DX was better before when the default action was to dismiss the snackbar. Creating a wrapper component just to be able to use the hook feels a bit weird.

But nevertheless: your suggested approach works, thank you :)

**Comment by iamhosseindhv** [comment]
@chapati23 I agree it is weird. It's just a trade off we had to make to allow multiple action for a snackbar.

**Comment by iamhosseindhv** [comment]
@dalborgo atm I can't seem to come up with a solution. I'll post a solution as soon as I find one.

**Comment by TrejGun** [comment]
Can't find solution without some buttons inside snackbar to close it with onclick..
should be an option to use all snackbars as clickable button\region, 
smth. like that: 
<SnackbarProvider 
   action={id => (onClick={closeSnackbar(id)}>
or just
<SnackbarProvider 
   onClick={closeSnackbar(id)}>

**Comment by iamhosseindhv** [comment]
@TrejGun Assuming this is a class component:

```js
const providerRef = React.createRef()

<SnackbarProvider
    ref={this.providerRef}
    action={(id) => {
		<button onClick={() => this.providerRef.closeSnackbar(id)}>dismiss</button>
    }}
>

    <App />
</SnackbarProvider>

**Comment by Vasiliy-Grishanin** [comment]
For those who use Typescript + MUI:
```Typescript
const CloseSnackbarAction = ({ id }: any) => {
  const { closeSnackbar } = useSnackbar()
  return (
    <IconButton style={{marginTop: "0.1em"}} onClick={() => {closeSnackbar(id)}}>
      <CloseIcon/>
    </IconButton>)
}
```
```Typescript
<SnackbarProvider maxSnack={3} anchorOrigin={{vertical: 'bottom', horizontal: 'center'}}
      style={{fontSize: "larger", whiteSpace: "nowrap", flexWrap: "nowrap"}}
      action={key => <CloseSnackbarAction id={key} />} >
      <App/>
</SnackbarProvider>
```

**Comment by alexmasyukov** [comment]
If you want to use differrent actions in a component

**use:**
```
 enqueueSnackbar('Delete it?', {
      variant: 'default',
      action: deleteAction(deleteEvent),
    });
```

**action**
```
type DeleteAction = (yesCb: () => void, noCb?: () => void) => (snackbarId: SnackbarKey) => ReactNode;

export const deleteAction: DeleteAction = (yesCb) => (snackbarId) => {
  const { closeSnackbar } = useSnackbar();

  return (
    <>
      <button onClick={() => {
          yesCb();
          closeSnackbar(snackbarId);
      }}>
        Yes
      </button>
      <button
        onClick={() => {closeSnackbar(snackbarId)}}
      >
        No
      </button>
    </>
  );
};
```
