### ISSUE TITLE
[Question] Example on how to position the toast relative to a parent container

### ISSUE THREAD

**Issue by martinmckenna** [iamhosseindhv/notistack#66]
I'm wondering how exactly one would go about positioning the toast relative to a container div, rather than entire body.

In our project, we've tried creating our own refs and even changing where in the DOM tree the Provider component was initialized but nothing seems to work

**Comment by iamhosseindhv** [comment]
> I'm trying to apply CSS class directly to `<Snackbar />` element. One example of it would be changing elements position property from fixed to absolute (ie. I'm trying to position snackbars relative to container, not window). https://github.com/iamhosseindhv/notistack/issues/11#issuecomment-431651078

@BornaP Appreciate if you could help regarding this.

**Comment by iamhosseindhv** [comment]
Closed due to inactivity
