### ISSUE TITLE
Material UI v3.2.0 warnings

### ISSUE THREAD

**Issue by pantharshit00** [iamhosseindhv/notistack#7]
If you run this on material UI 3.2.0 which introduced the new typography v2 you get a certain error.

Sandbox: https://codesandbox.io/s/vm8rj9lkqy

But even after I enable nextStyling in the theme I get nesting warning because the package is then trying to render a `<div>` inside a `<p>` tag.

Warning after enabling the new typography

![image](https://user-images.githubusercontent.com/22195362/46913134-5e183b80-cfa5-11e8-9160-29cace9eb8f0.png)

Upgrading to v3.2 should fix this, or we may explicitly make that p tag heading or  div, not much work if you want I may make a PR

**Comment by iamhosseindhv** [comment]
Thanks for pointing this out. Updating your notistack version to the latest (`v0.3.4`) will make the warnings go away. 

Mui-Snackbar uses a Typography with `variant="body1"` internally. New version of notistack overrides this to `variant="subtitle1"`. The appearance stays the same though.
