### ISSUE TITLE
Release major version

### ISSUE THREAD

**Issue by VincentLanglet** [iamhosseindhv/notistack#73]
In Semantic Versioning a `0.x.x` version is a beta. I think this library is quite complete and should be release as a stable version 1.0.0. It can be now or after a few more PR.

This will give more confidence in its use.

**Comment by iamhosseindhv** [comment]
Thanks for pointing that out @VincentLanglet. 

I'm in the process of making the decision to eliminate this package's dependency on material-ui Snackbar. Regardless of whether we go that route or not, `v1.0.0` will be released after I write some tests for notistack.

**Comment by VincentLanglet** [comment]
@iamhosseindhv Hi !
I am quite interested in the possible willingness to remove this project from material-ui. I think this package can be really useful for material-ui users. Where does this idea come from ? Do you plan to stop maintaining this library ?

**Comment by iamhosseindhv** [comment]
Of course not, I'll be maintaining notistack and keep adding new useful features. Not only material-ui users, but anyone using React can be a potential user of the package,. IF I eliminate the dependency, I'll keep all the features and API from material Snackbars and will try to keep the project in sync with material snackbars.

At the end of the day it really depends how many users are there that like the idea of notistack but are not a material user.

**Comment by VincentLanglet** [comment]
Ok ! I knew others library like `react-toastr` or `toastr` but I prefer this one because of the material-ui integration. Of course if this can work with both material-ui and others snackbar, it can be use by more people.
