### ISSUE TITLE
Breaks in production but runs perfect in development

### ISSUE THREAD

**Issue by jlei523** [iamhosseindhv/notistack#74]
I'm using Next.js combined with Material UI.

For someone reason, notistack runs perfectly on my local development but the css is completely messed up in production. I don't see any errors anywhere.

**Comment by iamhosseindhv** [comment]
@jlei523 That's a weird behaviour which is similar to this:
production build - classnames conflicts https://github.com/mui-org/material-ui/issues/8223#issuecomment-412349569 

I had the same issue in my projects in nextjs and material. If you're using the material-nextjs example, go to `getPageContext.js` and add a prefix to your classnames: 
```javascript
const createPageContext = () => ({
    theme,
    // This is needed in order to deduplicate the injection of CSS in the page.
    sheetsManager: new Map(),
    // This is needed in order to inject the critical CSS.
    sheetsRegistry: new SheetsRegistry(),
    // The standard class name generator.
    generateClassName: createGenerateClassName({
        // to prevent classnames from colliding
        productionPrefix: 'haka',
    }),
});

```

Please share some code in case this didn't solve your issue.

**Comment by jlei523** [comment]
Fixed!!!

**Comment by iamhosseindhv** [comment]
@jlei523 Happy to hear that ❤️
