### ISSUE TITLE
ContentProps not passed to material-ui component

### ISSUE THREAD

**Issue by selyon** [iamhosseindhv/notistack#75]
I'm trying to style the snackbar, but passing something like this:
ContentProps: { classes: { root: classes.snackbarContent } }
inside the enqueueSnackbar method doesn't work.

 Thank you for your help

**Comment by iamhosseindhv** [comment]
Why not?

In the example below I set all snackbar backgrounds to be red: https://codesandbox.io/s/24pz1p9l2y
```javascript

const styles = {
  // ...
  content: {
      backgroundColor: 'red !important',
  }
};

this.props.enqueueSnackbar(button.message, {
    ContentProps: {
        classes: {
            root: this.props.classes.content,
        }
    }
});
```
