### ISSUE TITLE
Directly import SnackBarItem

### ISSUE THREAD

**Issue by milieu** [iamhosseindhv/notistack#76]
Hello,

I am not sure if I am opening this issue simply because I don't understand how imports work with npm packages.

I would like to reuse the SnackBarItem internally used by notistack, so I have uniformity across a "static" SnackBarContent displayed within a Material UI Dialog, and the other notistack SnackBar notifications in my app.

Is this already possible? Or does SnackBarItem need to be added to the top-level index.js in src for this to work?

**Comment by iamhosseindhv** [comment]
@milieu For your use case, you should be able to import `SnackbarItem` by doing something like:

```javascript
import SnackbarItem from 'notistack/build/SnackbarItem';
```

let me know if this didn't answer your question.
