### ISSUE TITLE
Suggestions -  React Hook

### ISSUE THREAD

**Issue by ayepRahman** [iamhosseindhv/notistack#77]
Hi there, will you be updating the use of withSnackbar to react hook anytime soon? =) 

```
const { useSnackbar } from 'notistack'

const [ enquerySnackbar ] = useSnackbar();
```

**Comment by iamhosseindhv** [comment]
@ayepRahman Thanks for the suggestion. There is discussion PR for this https://github.com/iamhosseindhv/notistack/pull/17

Not sure about "anytime soon". but definitely in the next major release.
