### ISSUE TITLE
How to obtain the current number of snack?

### ISSUE THREAD

**Issue by raymondsze** [iamhosseindhv/notistack#80]
I would like to make a Scroll to Top Button that always above all the snack-bars. Therefore, I need a way to know how many snackbar are currently stacked.

## Expected Behavior

Should able to get snack from the consumer.

## Current Behavior

unable to get snack from the consumer.

**Comment by iamhosseindhv** [comment]
@raymondsze Thanks for opening the issue. 

Currently there's no way of knowing number of snacks and I don't think there ever will be.

You could however display a fab or any button "below" snackbars in the futures releases. For example, you'd have a button in the bottom-right corner, and you could display snackbars on top of fab by passing an `offset`. In that case your issue would be similar to #58.
