### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by shandye2** [iamhosseindhv/notistack#81]
I follow the example implementation. however, it doesnt work.
I got error below.

![53253987_1222145504618869_8208339838810718208_n](https://user-images.githubusercontent.com/14047529/53338034-9bbaa700-393d-11e9-9637-5b2ab043110a.png)

I have these codes:
App.js
![untitled](https://user-images.githubusercontent.com/14047529/53338137-e9371400-393d-11e9-9421-766d4bab2d4f.png)

DefaultPage.js
![untitled](https://user-images.githubusercontent.com/14047529/53338254-33b89080-393e-11e9-93e2-afd9a464d12d.png)

![untitled](https://user-images.githubusercontent.com/14047529/53338335-5f3b7b00-393e-11e9-9839-87645834fcf4.png)

I dont know what i have missed.

**Comment by iamhosseindhv** [comment]
@s7dhansh I can't see why it wouldn't work as this code is very similar to our [sandbox](https://codesandbox.io/s/x3qvk259zo) example while our example works fine.

I'm sure I can help if you provide a reproduction code and share the sandbox link here.

**Comment by iamhosseindhv** [comment]
Closed due to inactivity. Feel free to reopen.
