### ISSUE TITLE
Material UI v4 support

### ISSUE THREAD

**Issue by duongdev** [iamhosseindhv/notistack#82]
Hi, do you have any plans to support material-ui v4 in the near feature?

**Comment by xiaoxiangmoe** [comment]
https://github.com/iamhosseindhv/notistack/blob/039f3f705db61217b7ac3515bcac97a7b1ddc2e9/src/SnackbarItem/SnackbarItem.styles.js#L15-L17


```
Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * 2` with `theme.spacing(2)`.
```

**Comment by iamhosseindhv** [comment]
We will for sure support v4 and this will be fixed in the next release. Thanks for reporting.
