### ISSUE TITLE
[Req] "ref" support for withSnackbar HOC.

### ISSUE THREAD

**Issue by jhrinoa** [iamhosseindhv/notistack#84]
"ref" cannot be used a component that gets wrapped with withSnackbar HOC.
(Example: https://codesandbox.io/s/lp8ml9m52m)

I am wondering whether the next version of notistack can support ref using forwardRef.

If you agree, please note that React document suggest that this change should be a major version change.
https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

**Comment by iamhosseindhv** [comment]
Thanks for pointing this out @jhrinoa. Fix is now on master and will be published in the [next](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md) major release.
