### ISSUE TITLE
[Request] Add support for a progress|updatable variant

### ISSUE THREAD

**Issue by ShivamArora** [iamhosseindhv/notistack#88]
Please provide an updatable variant where we can display the progress of an ongoing operation without enqueuing another snackbar to the stack.

## Expected Behavior
The `enqueueSnackbar` already returns a key for the snackbar making it dismissable.

We should be able to update the snackbar message using the same key as well.

## Current Behavior
There doesn't exist any such support the update the snackbar message yet.

## Context
I want to display the progress of an ongoing operation like a file upload.

**Comment by iamhosseindhv** [comment]
Thanks @ShivamArora for opening the issue. This for sure will be added to project. Idea and partial implementation can be found here: https://github.com/iamhosseindhv/notistack/pull/50
