### ISSUE TITLE
[Question] Is it possible to position multiple snackbars and not have gaps?

### ISSUE THREAD

**Issue by joelgb2194** [iamhosseindhv/notistack#89]
When I try to create more than 2 snack bars in different anchorOrigins, there's a gap based on the snackbar array position. Is there a way to have different queues for each possible positioning location so that you could theoretically have one location for a specific set of notifications maybe like non auto dismissing snackbars and another location for auto dismissal?

This is what happens when I want to do bottom left and bottom center. There's a gap under the error snackbar: 
![a7ab67667a5876ed3b0e81c4a111e349](https://user-images.githubusercontent.com/6456841/53978512-6b130400-40d9-11e9-8c41-66f955a08f71.png)

**Comment by iamhosseindhv** [comment]
Although I've been facing the same problem in the documentation website for [this](https://iamhosseindhv.com/notistack#material-props) example, I think adding support for it will lead to bad UX. 

Displaying snackbars on different positions will lead to **stacking** them on different positions, which is extremely annoying. 

Although I agree displaying 1 snackbar at a time but on different positions **is** tolerable. Which you can achieve by setting `maxSnack` to 1.
