### ISSUE TITLE
Upgrade to new material-ui version

### ISSUE THREAD

**Issue by JakubPetriska** [iamhosseindhv/notistack#9]
Hi, just a question, do you plan to upgrade this library to new version of `material-ui`? Using this with `material-ui` 3.x causes nasty warning due to new naming of typography variants.
![screenshot from 2018-10-19 15-29-00](https://user-images.githubusercontent.com/5531859/47221049-be4b1b00-d3b3-11e8-95ea-77847795ff2f.png)

**Comment by iamhosseindhv** [comment]
What's the notistack version that you're using?

**Comment by iamhosseindhv** [comment]
Closed due to inactivity.

**Comment by JakubPetriska** [comment]
Sorry for inactivity. This happens on version 0.3.7
