### ISSUE TITLE
Unmet Peer Deps 

### ISSUE THREAD

**Issue by theonlydaleking** [iamhosseindhv/notistack#93]
notistack@0.5.0" has unmet peer dependency "@material-ui/core@^3.2.0".

happy to push a PR to move material to deps and out of peerDeps if you like. 

## Expected Behavior

`yarn install notistack` - then adding to the project, should work as docs describes

## Current Behavior

  After steps to reproduce, react fails with - can't find RootRef (a material-ui core) 

## Steps to Reproduce

- yarn create react-app tmp 
- cd tmp 
- yarn add notistack 
- add in following code as per docs
```
import { SnackbarProvider } from 'notistack';

<SnackbarProvider maxSnack={3}>
    <App />
</SnackbarProvider>
```
- Module not found: Can't resolve '@material-ui/core/RootRef

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | latest  |
| React        |   latest      |
| Browser      |    na     |

**Comment by iamhosseindhv** [comment]
@theonlydaleking Notistack is an extension material-ui's Snackbar. So people who are already using material-ui can leverage notistack. I believe `material-ui` must be a peer dependency.
