### ISSUE TITLE
console error when styling variantDefault

### ISSUE THREAD

**Issue by intergalactic-overlords** [iamhosseindhv/notistack#95]
When styling variantDefault by using material ui classes, I get the following error in the console: 

```Warning: Material-UI: the key `variantDefault` provided to the classes property is not implemented in SnackbarItem.
You can only override one of the following: root,anchorOriginTopCenter,anchorOriginBottomCenter,anchorOriginTopRight,anchorOriginBottomRight,anchorOriginTopLeft,anchorOriginBottomLeft,base,lessPadding,variantSuccess,variantError,variantInfo,variantWarning,message.```

The snackbar receives styling, so it works, but somehow the error is thrown.

## Expected Behavior
styled default snackbar and no errors

## Current Behavior
styled default snackbar and errors

## Steps to Reproduce
Link: https://codesandbox.io/s/2014qr4vvn

1. add variantDefault to the classes property of SnackbarProvider
2. run the code in the browser and look at the console

## Context
I'm trying to style the default snackbar. And I don't want errors in my console.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.5.0  |
| React        |    16.7.0     |
| Browser      |   Firefox & Chrome      |

**Comment by iamhosseindhv** [comment]
@intergalactic-overlords notistack doesn't have `variantDefault`. You can use material-ui classes keys for styling normal snackbars (the ones with default variant).

You can see a full list of available keys here: https://material-ui.com/api/snackbar/#css

**Comment by intergalactic-overlords** [comment]
But variantSuccess, variantError, variantInfo, variantWarning are not mentioned as well on that material-ui page and it is possible to use them. 
And when I use variantDefault, it's possible to change the styling (see the codesandbox). Or am I missing something here?

**Comment by intergalactic-overlords** [comment]
Ok, I understand now. When adding `variantDefault`, it somehow adds that class, and I am somehow possible to use it (material ui magic??), but it throws an error. But I should actually use `base`.

**Comment by dalborgo** [comment]
```
classes={{
    root: classes.yourStylings,
}}
```

I have tried to change the "default variant" background color.

But I get this effect...

![20190515204629](https://user-images.githubusercontent.com/12909806/57801104-467b7e00-7753-11e9-8411-2a3c3b238567.png)

It doesn't seem to apply to the SnackBarContent.

**Comment by iamhosseindhv** [comment]
have you tried passing classes through `ContentProps`?

```javascript
ContentProps={
    classes={{ root: classes.myRedBackgroundColor }}
}

```

**Comment by dalborgo** [comment]
Ty @iamhosseindhv 

This works.
`
 ContentProps={
                                {
                                  classes: {
                                    root: classes.myRedBackgroundColor
                                  }
                                }
                              }
`

The only problem is that rule overrides the other variants styles.

I didn't find a way to set a red background as default and a black for the 'error' one.

**Comment by iamhosseindhv** [comment]
how about this one? @dalborgo 
```javascript
ContentProps={{ 
    classes: {
        root: classes.myRedBackgroundColor,
        variantError: classes.yourBlackgroundColor,
    } 
}}

```
