### ISSUE TITLE
Warning: `NaN` is an invalid value for the `bottom` css style property.

### ISSUE THREAD

**Issue by ip4422** [iamhosseindhv/notistack#98]
I put 2 different message into queue
    this.props.enqueueSnackbar('Successfully fetched the data.', {
      variant: 'success',
      autoHideDuration: 7000,
    })
    this.props.enqueueSnackbar('Error fetched the data.', {
      variant: 'error',
      autoHideDuration: 7000,
    })

## Expected Behavior
In console should not be any warnings or errors

## Current Behavior
When I put 2 message in queue first time i got in console this message
Warning: `NaN` is an invalid value for the `bottom` css style property.
    in div (created by Snackbar)
    in ClickAwayListener (created by Snackbar)
    in Snackbar (created by WithStyles(Snackbar))
    in WithStyles(Snackbar) (created by SnackbarItem)
    in RootRef (created by SnackbarItem)
    in SnackbarItem (created by WithStyles(SnackbarItem))
    in WithStyles(SnackbarItem) (created by SnackbarProvider)
    in SnackbarProvider
    in Provider

## Steps to Reproduce
Link:

1. https://codesandbox.io/s/nrlzl23w1m

## Context
When I put 2 message in queue first time i got in console this message. On second enqueue warning not occure

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.5.1  |
| React        |  16.4.2       |
| Browser      |    Chrome 72.0.3626.121     |

**Comment by iamhosseindhv** [comment]
Thanks @ip4422. Since both snackbars were enqueued immediately after one another, `height` was undefined. We use a `48` as fallback now since in most cases that's the snackbar height.
